### ISSUE TITLE
show_in_notebook not working

### ISSUE THREAD

**Issue by houzy** [marcotcr/lime#1]
Hi, Marco Tulio Ribeiro:
      I have installed your reps on my macbook pro, and run the tutorials. Everything is ok but the show_in_notebook shows nothing, what I can see is just output:
      \<IPython.core.display.HTML object\>
      I don't know why this happend.

**Comment by marcotcr** [comment]
Hello,
I'm sorry it doesn't work! Would you please tell me:
1. what python version are you using?
2. what notebook version are you using?
3. Can you please try exp.save_to_file('/tmp/temp.html'), and then open the /tmp/temp.html file to see if it renders correctly?
Thanks,

**Comment by houzy** [comment]
Thanks for your reply!
What I used：
notebook:
jupyter 4.1.0
python:
Python 2.7.10
exp.save_to_file('/tmp/temp.html') and open /tmp/temp.html file by browser, it works fine, I can see the figure in the browser.

**Comment by marcotcr** [comment]
I wasn't able to replicate the problem. Would you please share your notebook?
Also, this may be a longshot, but do you happen to have doctest on?
Thanks,

**Comment by houzy** [comment]
I'm sorry for my mistake! I run the jupyter in the console mode, and get the strange result. Now, I run the example in the jupyter notebook, and it works fine! Thank you.

**Comment by marcotcr** [comment]
Great : )

**Comment by paix120** [comment]
For people coming here in the future: I was having trouble with it on Windows, and @marcotcr fixed the issue in the last few days, so if you're getting an error with show_in_notebook, and you're on a Windows machine, update to the latest version (currently 0.1.1.15) and see if that solves the problem for you like it did for me!
