### ISSUE TITLE
explainer on a pipeline

### ISSUE THREAD

**Issue by gsvijayraajaa** [marcotcr/lime#100]
Hi,

I have a model pipeline :

```
Pipeline(steps=[('vect', DictVectorizer(dtype=<type 'numpy.float64'>, separator='=', sort=True,
        sparse=False)), ('est', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features=0.6, max_leaf_nodes=None,
            min_impurity_split=1e-0...estimators=10, n_jobs=1, oob_score=False, random_state=4,
            verbose=0, warm_start=False))])
```

I have a test data vector in the form of a dictionary. I am trying to 

`exp.explain_instance(data,model.predict_proba,num_features=3836,num_samples=595)`

exp is  the explainer object.

Since, model is a pipeline with < vectorizer and Random forest > . The model expects a dict as an input whereas the explain_instance expects a numpy array. How do I fit both?

**Comment by marcotcr** [comment]
The current code doesn't really support this case. To make it work, you would have to decouple the vectorizer step and do it beforehand on data before calling explain_instance (i.e. not use a pipeline).
Sorry
