### ISSUE TITLE
How to apply LIME to word vectors and find meaningful keyword?

### ISSUE THREAD

**Issue by HowardNTUST** [marcotcr/lime#102]
Thank you for contributing such a great work to machine learning algorithms. 
I'd like to know how to apply Lime to find out the meaningful "keywords" for each observation(let's say an article) through word vectors generated by GloVe, word2vec ,etc. 

My idea about this is:
0.Let's say we have 200 word-vector-size of word vectors
1.Select interpretable word vectors for individual predictions from article text classifiers with Lime
2.Get the keywords based on selected word vectors, for example, only the 25th word vectors are selected and cosine similarity is applied to that, such that the keywords with the word(s) I want to have the similarity with are selected within the 25th word vectors instead of whole matrix of 200 word-vector-size of word vectors. for more example, please reference [glove-word-vectors.ipynb](https://github.com/spro/practical-pytorch/blob/master/glove-word-vectors/glove-word-vectors.ipynb)

Hopefully, I could have some suggestions from you.

By the way, the ipynbs you made in this repo elaborately demonstrated how tf-idf works with Lime, which is perfectly understandable.  I wonder if you also could kindly detail how [embedding_forest.py](https://github.com/marcotcr/lime-experiments/blob/master/embedding_forest.py) works with an example and how meaningful keywords could be selected for each observation through word vectors. Thank you for considering my requests.

**Comment by marcotcr** [comment]
I don't think I understand the question, primarily because I don't think saying something like 'This document was predicted as 1 because of word vector 183' gives users any insight.

When I've used word vectors in the past, I've abstracted them from LIME and still explained based on words (this is the distinction between interpretable representation and model representation in the paper) - i.e. even if the model is acting on embeddings, the explanations are still real words. Does this make sense?

**Comment by HowardNTUST** [comment]
Thank you for reply! I've solved my questions with your instructions of [word embedding experiment](https://github.com/marcotcr/lime-experiments/issues/4). Only to find the two-class result generated by your word embedding model is somewhat different from two-class by tf-idf. And f1-score of  the two-class result by embedding model declined by more or less 5%. 

So, Can these results tell something meaningful? or I may have missed something when generating word embedding model?

[twoclass by tf-idf; id=test set 83; f1-score = 0.92](doc/images/twoclass.png)
<img src="https://raw.githubusercontent.com/marcotcr/lime/master/doc/images/twoclass.png" width=900 />

[twoclass by word2vec; id=test set 83; f1-score = 0.87](https://github.com/HowardNTUST/lime-q/blob/master/2017-09-11%2009-43-23%20%E7%9A%84%E8%9E%A2%E5%B9%95%E6%93%B7%E5%9C%96.png)
<img src="https://raw.githubusercontent.com/HowardNTUST/lime-q/master/2017-09-11%2009-43-23%20%E7%9A%84%E8%9E%A2%E5%B9%95%E6%93%B7%E5%9C%96.png" width=900 />

**Comment by HowardNTUST** [comment]
The word2vec code I adapted from your lime experiment repo was uploaded [here](https://github.com/HowardNTUST/lime-q), and the [w2v_lime.py](https://github.com/HowardNTUST/lime-q/blob/master/w2v_lime.py) is the main .py file that I generated word2vec result above.

**Comment by marcotcr** [comment]
> 1.Can these results tell something meaningful?

Well, the first figure shows that the tf-idf model is heavily relying on header stuff (NNTP, Posting, Host, etc). The second figure shows that the influence of words is more dispersed for the word2vec model (for this particular example, at least).

> 2.or I may have missed something when generating word embedding model?

This was not meant to be a state of the art model using word embeddings, I just used it to illustrate that we can explain these models using words, even if they use embeddings. This is the same if you use a good model (e.g. we explained [this model](https://arxiv.org/abs/1511.08198) in follow up work)

> 3.According to the f1-score reported below, Can I say tf-idf method is better than word embedding ones in this case ?

Better at what? It is certainly better at predicting stuff on the 20ng dataset. Is it better in the real world? I would say that the explanation at least shows that the tf-idf method is bad, while it does not show anything about the word2vec model.

**Comment by ColeCola** [comment]
Dear @marcotcr  I couldn't add LIME package in my notebook, do you have any suggest about it ?

**Comment by marcotcr** [comment]
Sounds like you did not install it appropriately. Maybe your notebook is using a different version of python than the one you used to install lime.

**Comment by ColeCola** [comment]
I have already installed appropriately. My Notebook version 5.5.0,  that can be problem for lime package? Which notebook version is suitable for it ?

**Comment by marcotcr** [comment]
Check if you installed lime on the kernel you are using. I just checked with notebook 5.6.0, and it works

**Comment by JINHXu** [comment]
Hi,

i have a relevant question: how to use `make_pipeline` with BERT embeddings though? my direct input to the model is also word embeddings, but only they are already extracted in another job (due to the long runtime of large amount of data), what do i pass to `make_pipeline`? I used `simpletransformers` to extract word embeddings (it took something like 8 hours on 4 PGUs). Any ideas on this? Thank you!
