### ISSUE TITLE
Installing lime on Windows

### ISSUE THREAD

**Issue by sedeh** [marcotcr/lime#105]
Hello,

What is your recommendation for installing lime on Windows?

I first tried:

`pip install lime`

and got the following error: `TypeError: string argument expected, got 'NoneType'`.

Next, I tried:

```
git clone https://github.com/marcotcr/lime.git
python setup.py install
```

The installation worked fine without throwing any error. `import lime` works fine but `import lime.lime_tabular` throws an error: `ImportError: No module named 'lime.lime_tabular'`.

I've Win64 and Python 3.5.3.

**Comment by sedeh** [comment]
Okay. Doing `cd lime` and then doing `python setup.py install` from there seems to work.

**Comment by cpoptic** [comment]
I'm also getting this error. 
`pipenv install lime`
'pipenv shell'
'jupyter notebook'

'import lime' works fine, but 
'import lime.lime_tabular' fails for some reason.  Yields the error:

ModuleNotFoundError: No module named 'lime.lime_tabular'

Windows 10, x64, and Python 3.6.3.

Why would lime import with no problem but lime.lime_tabular throws an error?
