### ISSUE TITLE
Error in using `entropy` discretization

### ISSUE THREAD

**Issue by hardianlawi** [marcotcr/lime#108]
I am trying to create a `LimeTabularExplainer` instance using `entropy` discretization.

However, I got the error `AttributeError: 'module' object has no attribute 'tree'` because of this line `dt = sklearn.tree.DecisionTreeClassifier(criterion='entropy', max_depth=3)`.

How do I make it work without changing the script?

**Comment by marcotcr** [comment]
We were missing an import in that discretizer. Fixed in 0.1.1.24, please update your version.
