### ISSUE TITLE
LIME Image: change superpixel segmentation parameters

### ISSUE THREAD

**Issue by FlorentPajot** [marcotcr/lime#109]
Quickshift is curretly used to perform image segmentation through its skimage implementation. Tuning parameters of Quickshift algorithm should be made available to the user, making it more flexible depending on the input image analyzed. Moreover, new algorithms like the ones already available in skimage should be added to offer several options for segmenting.

**Comment by FlorentPajot** [comment]
New parameters could be added to LimeImageExplainer.explain_instance() to handle quickshift tuning parameters, leaving quickshift as default option.

**Comment by marcotcr** [comment]
Yes, this would be a good candidate for an easy PR :)

**Comment by FlorentPajot** [comment]
Yes, I'm working on it :)

**Comment by marcotcr** [comment]
Thanks for doing the PR!
