### ISSUE TITLE
 Any plans to add a feature to aggregate the explanations for multiple instances?

### ISSUE THREAD

**Issue by himalayajung** [marcotcr/lime#11]
Thanks for this awesome package.
A feature to aggregate the explanations from multiple instances that blends well with as_html() and other visualization functions would be really helpful. For example, in Titanic dataset, it would be nice to see the overall explanation for male passengers. 
Plus, a feature to automatically selecting the representative samples using some metric would be helpful too.

**Comment by marcotcr** [comment]
I do have a technique in the paper to select representative instances to show to the user. This and the first thing you suggested require us to compute explanations for every example in some validation set, which usually takes a long time.
I will try to add some code on top of LIME to do this, maybe next week.
Thanks for the feedback : )

**Comment by AlJohri** [comment]
hi @marcotcr, just wanted to check if the SP-LIME algorithm (Submodular pick algorithm) you described is implemented in this package. I think this would be extremely for our use case.

Thanks!

**Comment by marcotcr** [comment]
Argh, sorry I never got to it. It's really simple, and it's implemented [here](https://github.com/marcotcr/lime-experiments/blob/8fd31c7c81facb240fdf728a50d029af8c452af5/compare_classifiers.py#L20) assuming explanations are precomputed. It's just a matter of me finding the time to make a pretty interface for it.

**Comment by AlJohri** [comment]
Awesome, this is a great start! I will look into this next week.

**Comment by marcotcr** [comment]
closed by #206
