### ISSUE TITLE
Create new PyPi release

### ISSUE THREAD

**Issue by echo66** [marcotcr/lime#114]
Greetings @marcotcr ! 

Are you planning on creating a new PyPi release soon?

**Comment by marcotcr** [comment]
Are there any recent changes that would warrant a new release? I usually create a new release whenever I fix some bug or add some significant feature.

**Comment by echo66** [comment]
The random state thing was, actually, a very important issue. Without having control over random states, it will make it harder to have reproducible results.

**Comment by marcotcr** [comment]
Just created 0.1.1.25
