### ISSUE TITLE
Unstable explanations when no random seed is assigned in LIME explain_instance

### ISSUE THREAD

**Issue by PeiYiTan** [marcotcr/lime#119]
Greetings, Marco. 

I have been playing LIME a bit, noticed  there is no random seed assignment in the explain_instance function. Without assigning a fixed random seed, the perturbed instances vary over each explain_instance runs which leads to different set of top-k features may be selected and unstable inconsistent linear regression effect estimates. 
Especially if we want to compare the differences in local explanation between different test instances, without applying the same set of random instances to compute the distances/weights, the comparison may not be reliable.  
    
In your simple regression example https://marcotcr.github.io/lime/tutorials/Using%2Blime%2Bfor%2Bregression.html , explain_instance produces different results over multiple runs. 

Perhaps I misunderstood something, please comment your reason on not to assign a random seed in explain_instance.

Thank you.
Pei-Yi Tan

**Comment by marcotcr** [comment]
We recently added support for random seeds ([here](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L112), for example).
Does this solve your problem?

**Comment by PeiYiTan** [comment]
Thanks for your reply. I have uploaded the most current LIME python package. In the same simple regression example https://marcotcr.github.io/lime/tutorials/Using%2Blime%2Bfor%2Bregression.html , 
I inserted the random_state =54321 seed number in  
explainer = lime.lime_tabular.LimeTabularExplainer(train, feature_names=boston.feature_names, class_names=['price'], categorical_features=categorical_features, verbose=True, mode='regression', random_state=54321)
Then ran the code below a few times, each time the feature explanation are somewhat different. 
i = 25
exp = explainer.explain_instance(test[i], rf.predict, num_features=5)
exp.show_in_notebook(show_table=True)

Attached are the screen shots of the i=25 feature explanation from two consecutive runs.

![exp25](https://user-images.githubusercontent.com/16402811/32458543-bdeb0884-c2fa-11e7-89b7-51195a448558.JPG)
![exp25_1](https://user-images.githubusercontent.com/16402811/32458544-be291c96-c2fa-11e7-98f2-d71e40d7d466.JPG)

It raises another question; if setting a random seed will actually stabilize the local feature explanation, which random seed produced results are the most trustworthy? Should user run explain_instance several  times, each with a different random seed, and take the average estimate and provide confidence interval of the feature effect from the multiple runs?

**Comment by marcotcr** [comment]
Yes, even if you set the random seed you should get different results every time you run LIME (unless you set the random seed before each run).
LIME explanations are the result of a random sampling process, so we shouldn't expect to get the exact same explanation every time. If you want more confidence in the explanation, just increase the number of samples instead of running it multiple times and taking an average.

**Comment by vaibhav2509** [comment]
Is there a way to assign random seed value to explain instance function of LIME explainer?

**Comment by hamed-ayoobi** [comment]
> Is there a way to assign random seed value to explain instance function of LIME explainer?

Although, it might not make sense to have the same random (?) sampling every time, you can change the code if you want to have the random_state argument in the explain_instance function. This way you always have the same samples.

You can add the random_state argument and the following line of code to the explain_instance function in the lime_tabular.py:

```python
    def explain_instance(self,
                         data_row,
                         predict_fn,
                         labels=(1,),
                         top_labels=None,
                         num_features=10,
                         num_samples=5000,
                         distance_metric='euclidean',
                         model_regressor=None,
                         random_state=None): #the random_state argument is added
        """Generates explanations for a prediction.

        First, we generate neighborhood data by randomly perturbing features
        from the instance (see __data_inverse). We then learn locally weighted
        linear models on this neighborhood data to explain each of the classes
        in an interpretable way (see lime_base.py).

        Args:
            data_row: 1d numpy array or scipy.sparse matrix, corresponding to a row
            predict_fn: prediction function. For classifiers, this should be a
                function that takes a numpy array and outputs prediction
                probabilities. For regressors, this takes a numpy array and
                returns the predictions. For ScikitClassifiers, this is
                `classifier.predict_proba()`. For ScikitRegressors, this
                is `regressor.predict()`. The prediction function needs to work
                on multiple feature vectors (the vectors randomly perturbed
                from the data_row).
            labels: iterable with labels to be explained.
            top_labels: if not None, ignore labels and produce explanations for
                the K labels with highest prediction probabilities, where K is
                this parameter.
            num_features: maximum number of features present in explanation
            num_samples: size of the neighborhood to learn the linear model
            distance_metric: the distance metric to use for weights.
            model_regressor: sklearn regressor to use in explanation. Defaults
                to Ridge regression in LimeBase. Must have model_regressor.coef_
                and 'sample_weight' as a parameter to model_regressor.fit()
            random_state: an integer or numpy.RandomState that will be used to
                generate random numbers. If None, the random state will be
                initialized using the internal numpy seed.

        Returns:
            An Explanation object (see explanation.py) with the corresponding
            explanations.
        """
        #Add this line and the random_state argument
        self.random_state = check_random_state(random_state) 
        #The rest of the code will stay the same.

```
Now you can call the explainer.explain_instance(data, model.predict, random_state=1) function and have the same samples every time.
