### ISSUE TITLE
the code below may have some problem

### ISSUE THREAD

**Issue by porcobosso** [marcotcr/lime#12]
code in class LimeTabularExplainer function __data_inverse(line 264) may have some problem

```
#type of inverse_column is int
inverse_column = np.random.choice(values, size=num_samples, replace=True, p=freqs)
#and will cast float into int,numbers after decimal will lost
inverse_column[0] = data[0, column]
```

**Comment by marcotcr** [comment]
This code only applies to categorical features, and we assume that all categorical features are encoded as integers. Maybe I should make this more explicit.
