### ISSUE TITLE
LimeTabularExplainer: "TypeError: unhashable type: 'slice'"

### ISSUE THREAD

**Issue by Aladdin109** [marcotcr/lime#120]
Dear collegues!

I try to launch LimeTabularExplainer with Random Forest classifier (2-class prediction), but recieve TypeError.
Features only numerical (float).
What do i do wrong?

Code and error below.

Many thanks.
==========================================
import lime
import lime.lime_tabular
predict_gb = lambda x: clf.predict_gb(x).astype(float)
train_float_features=list(X_train.columns)
explainer = lime.lime_tabular.LimeTabularExplainer(X_train, feature_names=train_float_features, class_names=['0','1'])

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-128-9e04996a8ed3> in <module>()
      1 explainer = lime.lime_tabular.LimeTabularExplainer(X_train, feature_names=train_float_features, training_labels=None, 
----> 2                                                    class_names=[0,1])

~\AppData\Local\Continuum\anaconda3\lib\site-packages\lime\lime_tabular.py in __init__(self, training_data, mode, training_labels, feature_names, categorical_features, categorical_names, kernel_width, verbose, class_names, feature_selection, discretize_continuous, discretizer, random_state)
    162                 self.discretizer = QuartileDiscretizer(
    163                         training_data, self.categorical_features,
--> 164                         self.feature_names, labels=training_labels)
    165             elif discretizer == 'decile':
    166                 self.discretizer = DecileDiscretizer(

~\AppData\Local\Continuum\anaconda3\lib\site-packages\lime\discretize.py in __init__(self, data, categorical_features, feature_names, labels, random_state)
    123         BaseDiscretizer.__init__(self, data, categorical_features,
    124                                  feature_names, labels=labels,
--> 125                                  random_state=random_state)
    126 
    127     def bins(self, data, labels):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\lime\discretize.py in __init__(self, data, categorical_features, feature_names, labels, random_state)
     44 
     45         # To override when implementing a custom binning
---> 46         bins = self.bins(data, labels)
     47         bins = [np.unique(x) for x in bins]
     48 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\lime\discretize.py in bins(self, data, labels)
    128         bins = []
    129         for feature in self.to_discretize:
--> 130             qts = np.array(np.percentile(data[:, feature], [25, 50, 75]))
    131             bins.append(qts)
    132         return bins

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   1962             return self._getitem_multilevel(key)
   1963         else:
-> 1964             return self._getitem_column(key)
   1965 
   1966     def _getitem_column(self, key):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py in _getitem_column(self, key)
   1969         # get column
   1970         if self.columns.is_unique:
-> 1971             return self._get_item_cache(key)
   1972 
   1973         # duplicate columns & possible reduce dimensionality

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\generic.py in _get_item_cache(self, item)
   1641         """Return the cached item, item represents a label indexer."""
   1642         cache = self._item_cache
-> 1643         res = cache.get(item)
   1644         if res is None:
   1645             values = self._data.get(item)

TypeError: unhashable type: 'slice'

**Comment by eliorc** [comment]
How did you solve this?

**Comment by Aladdin109** [comment]
It's easy. You need to use *.values or np.arrays. I didn't notice it in the source at the first time. 

explainer = lime.lime_tabular.LimeTabularExplainer(**X_train.values**, feature_names=train_float_features, class_names=['0','1'])
