### ISSUE TITLE
Any way to get the explanation in table format?

### ISSUE THREAD

**Issue by Silence-Cloud** [marcotcr/lime#125]
Hi, this is an awesome package, just wondering if there is a way to save the file into a table ( excel, text etc.) format rather than html, it would be helpful when I got a large number of features and require further analysis

**Comment by marcotcr** [comment]
Do you mean saving the explanation as a table? We don't offer that, but it should be very easy to convert the output of explanation.as_list() into whatever table format you want.

**Comment by TheMLman** [comment]
Hi @marcotcr , I'm also trying to save the output of explanation in a tabular format. I used explanation.as_list() to save features with weights but I also need a table with actual feature values as in the output of explanation.show_in_notebook

My goal is to append top 5 features to each observation in my dataset to later create interactive visualization in Tableau with explanations for each observation. I wrote a loop that builds an explainer for an instance, saves output as a list and then does it for all other observations in the dataset. However, I can't figure out how to save a table with feature names and values in addition to weights.

Can you please advise if there is any way to do it?

**Comment by marcotcr** [comment]
You should have the feature values from the instance you are using as first parameter to the explanation function. If you are having trouble mapping the names back to feature indices in the original data, `explanation.as_map()[label]` gives you a map from feature index to explanation weight, maybe this will help you.
