### ISSUE TITLE
Documentation of linear regression results

### ISSUE THREAD

**Issue by s123343** [marcotcr/lime#127]
Hello,

I am new to LIME and I do not think the documentation for using LIME in the linear regression example is sufficient to explain the results. It only contains code. 
Does anyone know where I can find information that can help me interpret results of the tabular data in the example or maybe tell me how to interpret the results from the example here so I can use it on my own linear regression data. How does the negative and positive features influence the model? For linear regression, are the weights of the negative and positive features coefficients to the model?

I would also like to use LIME for random forest, decision tree, and neural networks and I would like to know how to interpret the results correctly for those as well.  Any information is appreciated.

Thanks in advance!

**Comment by marcotcr** [comment]
Regression is tricky. Which part of the regression example was unclear, in particular?

**Comment by s123343** [comment]
How to interpret the output for a regression problem when you use the

.show_in_notebook(show_table=True)

function.


Thank you!

________________________________
Fra: Marco Tulio Correia Ribeiro <notifications@github.com>
Sendt: 14. december 2017 19:48:04
Til: marcotcr/lime
Cc: Thanh Thien Nguyen; Author
Emne: Re: [marcotcr/lime] Documentation of linear regression results (#127)


Regression is tricky. Which part of the regression example was unclear, in particular?

**Comment by marcotcr** [comment]
In general terms in the example in [this notebook](https://marcotcr.github.io/lime/tutorials/Using%2Blime%2Bfor%2Bregression.html), the explanation is stating that "6.99 < LSTAT <= 11.43" (i.e. the feature value for LSAT is in this range) yields a positive influence (i.e. increases) on the output of the black box model with respect to other values. That is, if you set LSTAT outside the range for the same instance, the predicted value will likely go down. Same thing but in reverse for the other features in the explanation.

**Comment by s123343** [comment]
Thanks you. And how should I intrepret the weights?

________________________________
Fra: Marco Tulio Correia Ribeiro <notifications@github.com>
Sendt: 14. december 2017 22:03:59
Til: marcotcr/lime
Cc: Thanh Thien Nguyen; Author
Emne: Re: [marcotcr/lime] Documentation of linear regression results (#127)


In general terms in the example in this notebook<https://marcotcr.github.io/lime/tutorials/Using%2Blime%2Bfor%2Bregression.html>, the explanation is stating that "6.99 < LSTAT <= 11.43" (i.e. the feature value for LSAT is in this range) yields a positive influence (i.e. increases) on the output of the black box model with respect to other values. That is, if you set LSTAT outside the range for the same instance, the predicted value will likely go down. Same thing but in reverse for the other features in the explanation.

**Comment by marcotcr** [comment]
Like you would interpret the weights of a linear regression model (in this case, with categorical features). This explanation is a linear regression model built to approximate the black box model in the neighborhood of the prediction.

**Comment by Sandy4321** [comment]
this link code has error

https://marcotcr.github.io/lime/tutorials/Using%2Blime%2Bfor%2Bregression.html

explainer = lime.lime_tabular.LimeTabularExplainer(train, feature_names=boston.feature_names, class_names=['price'], categorical_features=categorical_features, verbose=True, mode='regression')
 
 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-7f0086557ce4> in <module>()
----> 1 explainer = lime.lime_tabular.LimeTabularExplainer(train, feature_names=boston.feature_names, class_names=['price'], categorical_features=categorical_features, verbose=True, mode='regression')
 
C:\Anaconda3\lib\site-packages\lime\lime_tabular.py in __init__(self, training_data, mode, training_labels, feature_names, categorical_features, categorical_names, kernel_width, verbose, class_names, feature_selection, discretize_continuous, discretizer, random_state)
    148         self.mode = mode
    149         self.categorical_names = categorical_names or {}
--> 150         self.categorical_features = categorical_features or []
    151         self.feature_names = feature_names or [str(i) for i in range(training_data.shape[1])]
    152 
 
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by marcotcr** [comment]
Fixed

**Comment by gulatisimran** [comment]
> Like you would interpret the weights of a linear regression model (in this case, with categorical features). This explanation is a linear regression model built to approximate the black box model in the neighborhood of the prediction.

hi @marcotcr.
Can you please help me understand these statement for REGRESSION model(keras neural networl), for the explanation value:-
'feature <= 0' , -90
'feature <= 0', -500
'feature <= 0' , 90
'feature <= 0', 500

[FYI my experimentation is related to only positive values for the numerical 'feature' 
i have only 'feature'>= 0 in my training/test data]

Thanks in advance!
