### ISSUE TITLE
Lime output contradicts model predictions

### ISSUE THREAD

**Issue by MaksMshn** [marcotcr/lime#131]
Hello,

I have trained a tiny neural network that takes an output of VGG-16 classification and uses it to classify whether an image contains a cat or a dog (VGG-16 output is more detailed and contains breed info as well). The model is simple enough to be interpretable without lime: cat breeds have positive weights on the first neuron and negative on the second. The situation is reversed for dogs.

However, when I try to use lime to explain cat predictions it gives unexpected outputs:
![cat_out](https://user-images.githubusercontent.com/6176998/34090787-2a3e6d68-e3c2-11e7-849e-c8584b0e3a14.png)
The dog predictions seem to work fine:
![dog_out](https://user-images.githubusercontent.com/6176998/34090804-4e33f030-e3c2-11e7-9eaf-804d2b666280.png)

To set up explainer I followed the tabular data tutorial, but it's still likely that I did something wrong. I have uploaded the notebook that allows one to reproduce the issue here: https://github.com/MaksMshn/Lime_issue

Thank you,
Maksim

**Comment by marcotcr** [comment]
The problem is just in displaying the outputs. We made an assumption (poorly documented, sorry) that if there are only two classes, the user will always get a prediction for class 1 (to maintain consistency in the color when displaying it). Just replace:
```
exp = explainer.explain_instance(vgg_out, catdog_model.predict, top_labels=1)
```
with:
```
exp = explainer.explain_instance(vgg_out, catdog_model.predict)
```
And your cat explanations will look right as well : ).

**Comment by MaksMshn** [comment]
That worked! Thanks for help.
