### ISSUE TITLE
Is there any way to use an explainer on mixed data?

### ISSUE THREAD

**Issue by hannahlindsley** [marcotcr/lime#133]
I have a model that uses raw text and additional features.
The LimeTextExplainer seems to need exclusively raw text, and the LimeTabularExplainer seems to need exclusively numeric values. Is there any way to explain a model with mixed data?

I've got a sklearn pipeline working fine, but I'd really like to see what features, textual or otherwise, have contributed.

Sample data:

[ [ "tree", 1]
  [ "i like toys", 0]
  [ "nope", 22] ]

To run toy code: 
https://github.com/hannahlindsley/textie/blob/dev/tutorials/xgboost-text-classifier.ipynb

**Comment by marcotcr** [comment]
Sorry, this is not something we support at the moment.
