### ISSUE TITLE
error on importing lime_image module

### ISSUE THREAD

**Issue by wasdee** [marcotcr/lime#136]
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-19-f1f5d72f70ae> in <module>()
      1 get_ipython().magic('load_ext autoreload')
      2 get_ipython().magic('autoreload 2')
----> 3 from lime import lime_image

~/anaconda/lib/python3.6/site-packages/lime/lime_image.py in <module>()
     11 
     12 from . import lime_base
---> 13 from .wrappers.scikit_image import SegmentationAlgorithm
     14 
     15 

ModuleNotFoundError: No module named 'lime.wrappers'
```

This is happen on my Anaconda Environment python3.6, MacBook Pro.

**Comment by wasdee** [comment]
I understand some clues.
1. I try to install this via 
`pip install lime`
and
`pip install git+https://github.com/marcotcr/lime`
None works.

2. run direct from the source works(git clone)

My guess is the setup file is incorrect.

**Comment by marcotcr** [comment]
You are right, the setup file was incorrect.
It should be fixed in the latest version, please reopen the issue if it is not fixed.
