### ISSUE TITLE
error in file Using lime for regression.ipynb

### ISSUE THREAD

**Issue by Sandy4321** [marcotcr/lime#138]
explainer = lime.lime_tabular.LimeTabularExplainer(train, feature_names=boston.feature_names, class_names=['price'], categorical_features=categorical_features, verbose=True, mode='regression')
 
 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-7f0086557ce4> in <module>()
----> 1 explainer = lime.lime_tabular.LimeTabularExplainer(train, feature_names=boston.feature_names, class_names=['price'], categorical_features=categorical_features, verbose=True, mode='regression')
 
C:\Anaconda3\lib\site-packages\lime\lime_tabular.py in __init__(self, training_data, mode, training_labels, feature_names, categorical_features, categorical_names, kernel_width, verbose, class_names, feature_selection, discretize_continuous, discretizer, random_state)
    148         self.mode = mode
    149         self.categorical_names = categorical_names or {}
--> 150         self.categorical_features = categorical_features or []
    151         self.feature_names = feature_names or [str(i) for i in range(training_data.shape[1])]
    152 
 
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by marcotcr** [comment]
fixed in 7990a8af82fb31d0c599bf73e14854579a8eb9b0
Thanks,

**Comment by Sandy4321** [comment]
super thanks
but this setup file is not working for Windows computer
some how python setup.py install is not working properly 
, sorry 
may you update The lime package  on PyPI
then it will be possible to use 
pip install lime
Thank you very much in advance
