### ISSUE TITLE
pls help fix error in file Using lime for regression.ipynb

### ISSUE THREAD

**Issue by Sandy4321** [marcotcr/lime#139]
I try to use file Using lime for regression.ipynb
 but there is error for this line 
explainer = lime.lime_tabular.LimeTabularExplainer(train, feature_names=boston.feature_names, class_names=['price'], categorical_features=categorical_features, verbose=True, mode='regression')
 
 Error message is 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-7f0086557ce4> in <module>()
----> 1 explainer = lime.lime_tabular.LimeTabularExplainer(train, feature_names=boston.feature_names, class_names=['price'], categorical_features=categorical_features, verbose=True, mode='regression')
 
C:\Anaconda3\lib\site-packages\lime\lime_tabular.py in __init__(self, training_data, mode, training_labels, feature_names, categorical_features, categorical_names, kernel_width, verbose, class_names, feature_selection, discretize_continuous, discretizer, random_state)
    148         self.mode = mode
    149         self.categorical_names = categorical_names or {}
--> 150         self.categorical_features = categorical_features or []
    151         self.feature_names = feature_names or [str(i) for i in range(training_data.shape[1])]
    152 
 
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Thank you very much in advance

**Comment by marcotcr** [comment]
What version of lime do you have installed?

**Comment by wiseyoungbuck** [comment]
I also encountered this issue. It is due to the categorical_features being passed as an numpy array when it expects a list. However, thus behavior used to work, and is used in the example regression notebook. If suggest we change the behavior to enable the usage of numpy arrays or lists.

**Comment by Sandy4321** [comment]
I installed by pip
installation by setup.py is not working for Windows computer 
may you update lime version on for pip installation

**Comment by nicolewhite** [comment]
Sorry guys. I fixed this in https://github.com/marcotcr/lime/pull/137.
