### ISSUE TITLE
ImportError: cannot import name 'lime_image'

### ISSUE THREAD

**Issue by machuck** [marcotcr/lime#141]
importing lime_image got an error:
```

>>> from lime import lime_image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'lime_image'
```

The package installed successfully, and "import lime" works fine
```
>>> import lime
>>> lime.__package__
'lime'
```

The lime_image.py is found:
```
can@r710:~/lime$ find /usr/local/lib/ -name 'lime_image*' -ls
2910800   12 -rw-rw-r--   1 root     root        10573 Jan  3 23:18 /usr/local/lib/python3.6/site-packages/lime-0.1.1.29-py3.6.egg/lime/lime_image.py
4198948   12 -rw-r--r--   1 root     root         9301 Jan  3 23:18 /usr/local/lib/python3.6/site-packages/lime-0.1.1.29-py3.6.egg/lime/__pycache__/lime_image.cpython-36.pyc
```

**Comment by marcotcr** [comment]
What version? I just tried a clean virtualenv install with python3 and it worked.

**Comment by machuck** [comment]
Sorry for the much delayed response. After reinstalling, it worked. I am using v3.6. Thanks again.

**Comment by zpyuan6** [comment]
I meet this problem, when I try lime/doc/notebooks/Tutorial - images - Pytorch.ipynb. I solved it by moving the location of the lime package under my python project. For programmers who just want to try out lime, this may be a solution. BTW, I am using Python v3.6.13 and lime-0.2.0.1
