### ISSUE TITLE
Question: Performance of Linear Model

### ISSUE THREAD

**Issue by BrianMiner** [marcotcr/lime#143]
In the LIME inspired R package it appears that one can extract the fit statistics to see how a choice in meta parameter (e.g. kernel width) impacts the individual observation linear model. Is it possible to extract this information here?

https://cran.r-project.org/web/packages/lime/vignettes/Understanding_lime.html

**Comment by marcotcr** [comment]
There is explanation.score (a variable), but we didn't make it into a method.

**Comment by BrianMiner** [comment]
Score is R-squared?

**Comment by marcotcr** [comment]
Yes. [This](https://github.com/marcotcr/lime/blob/master/lime/lime_base.py#L165) is where it is computed.
