### ISSUE TITLE
Using LIME with images

### ISSUE THREAD

**Issue by kaas66** [marcotcr/lime#150]
Hi!
I have some questions concerning using LIME with images as input:

1) is the division of the image into interpretable components manually or automatically done?

2) I do not really understand what the input to the linear model is in this case, since the input to the original model is an image. Is it just a vector representation of the image, where all the rows in the image are put after each other, or is it something else?

3) If I am correct concerning question 2), i.e. that all pixels in the image are regarded to be independent, isn't it then possible that the super pixels with the highest positive weights will be spread all over the image and not constitute a contiguous region?

**Comment by marcotcr** [comment]
1. It's done automatically, using skimage.segmentation. You can do it yourself if you want, using the `segmentation_fn` parameter.
2. The input to the linear model is a binary vector of length equal to the number of superpixels. A 1 in this vector indicates the superpixel is 'present' (the same as the original image), while a 0 indicates it is 'hidden' (black, gray, average of the superpixel, whatever you choose)
3. It is true that the superpixels in the explanation are not constrained to be contiguous. I could try to enforce that using fused lasso or whatever, but never did.

**Comment by xavihart** [comment]
kk
