### ISSUE TITLE
Is there any way to print text highlights for several labels ? 

### ISSUE THREAD

**Issue by ClementViricel** [marcotcr/lime#151]
Hi ! Thanks you for you project.
I use the function, save_to_file(path, top_labels = n) with n > 1.
This works very well except that I get the highlights only for the first top labels.
Is there any way to catch them all ? :)

Thanks

**Comment by marcotcr** [comment]
Sorry, it's not possible. Since we only show the text once, I don't even know what highlights for all of them would look like, since they could be conflicting and overlapping.
I guess you can always save them one by one : )
