### ISSUE TITLE
Use with non-python classifiers

### ISSUE THREAD

**Issue by jkh1** [marcotcr/lime#154]
Can lime be used with classifiers implemented outside python ? The examples seem to rely on the classifier being available to the python code.

**Comment by marcotcr** [comment]
You need to be able to call the classifier from python. If you have a model implemented in another language, you can still call it through bindings, calling a server, writing data to disk and using a system call, etc. For example, you could try something like:
```
def predict_fn(X):
    open(filename,'w').write(X)
    os.system('./other_classifier %s > %s' % (filename, /tmp/predictions')
    predictions = process(open('/tmp/predictions').readlines())
