### ISSUE TITLE
How to use Lime with the 1-output network

### ISSUE THREAD

**Issue by hainguyenct** [marcotcr/lime#156]
Dear all,
I would like to use Lime to understand how the network works with images.
The network receives images with 3 channels, includes one sigmoid regression giving 1 output which produces a probability.
When I use num_features=10, 
 ```
explanation = explainer.explain_instance(data[0], loaded_model.predict, top_labels=1)
temp, mask = explanation.get_image_and_mask(0,positive_only=True, num_features=10, hide_rest=True)
```
I have the result
![screen shot 2018-02-11 at 20 00 55](https://user-images.githubusercontent.com/17986080/36077074-64fee016-0f66-11e8-8303-0721e0c947ee.jpg)

(The first row includes original images, the second was produced from Lime)
When I use num_features=1
 ```
explanation = explainer.explain_instance(data[0], loaded_model.predict, top_labels=1)
temp, mask = explanation.get_image_and_mask(0,positive_only=True, num_features=1, hide_rest=True)
```
I have the result:
![screen shot 2018-02-11 at 20 00 51](https://user-images.githubusercontent.com/17986080/36077072-55f80a70-0f66-11e8-8ac3-377a0e507572.jpg)

(The first row includes original images, the second was produced from Lime)
I have some questions:

1. When I use num_features=1, the range colored yellow appeared. As I known, this is superpixel, but I do not know why it did not appear when num_features=10? I am wondering whether num_features in image is the number of pixel in superpixel or not?

2. With the model like above and the image, which parameters I should use to show the best visualization?
3. I would like to change color of the border (currently, it is yellow) to some color, e.g pink. How can I do that?

Thank you so much for your help.

**Comment by marcotcr** [comment]
Two comments:
- It seems that the default segmentation is terrible for the kind of images you are using. I would suggest using a different `segmentation_fn` [here](https://github.com/marcotcr/lime/blob/master/lime/lime_image.py#L120).
- The representation you are using to display the images is different than what we assume (check out [this notebook](https://marcotcr.github.io/lime/tutorials/Tutorial%20-%20images.html). When you set hide_rest=True, everything in the image should be gray except for the explanation (which should look the same as in the original image).

Now, to your questions:
1. You can take a look at explanation.local_exp to understand what's going on for those two explanations. The `num_features` parameters is for display only - if the explanation is the same, any superpixel with `num_features=1` should be there when `num_features=10`
2. As mentioned above, you should probably use a different segmentation function and change the display function. It should be clear how to from the examples in the notebook I linked above.
3. That yellow border shouldn't exist in the first place.

**Comment by hainguyenct** [comment]
Thank you so much for your reply. I will try again.
