### ISSUE TITLE
Perturbing text by removing sentences instead of words

### ISSUE THREAD

**Issue by jacobmalmberg** [marcotcr/lime#158]
Instead of removing words and seeing what words have the biggest impact, I tried modifying LIME so that it removes entire sentences. 

Codewise I added to lime_text.py
`from nltk.tokenize import sent_tokenize`

and in the init method for the class IndexedString I inserted
`self.as_list = sent_tokenize(self.raw)`
instead of 
`self.as_list = re.split(r'(%s)|$' % split_expression, self.raw)`

Using this to classify a song, these are the top6 explanations:
`Explanation for class 2
('While money doesn’t talk, it swears.', -0.11857644617364377)
('Graveyards, false gods, I scuff.', 0.09278969676208923)
('As human gods aim for their mark.', 0.0906653554875964)
('Startles your sleeping ears to hear.', -0.06745045357069925)
('Temptation’s page flies out the door.', 0.06080666803811672)
('The handmade blade, the child’s balloon.', -0.05006835139454674)`

Seems to work.

However the "Text with highlighted words" gets a little bit distorted. It seems to offset the highlighting by some characters, but the highlighting always seems to include punctuation. See screenshots below.

![2018-02-13-104606_1416x299_scrot](https://user-images.githubusercontent.com/24483789/36143341-1ed6b80c-10ab-11e8-913e-a95f09ae0cde.png)

![2018-02-13-104702_850x312_scrot](https://user-images.githubusercontent.com/24483789/36143379-3bae4bd4-10ab-11e8-924f-5fe5fab8a0d2.png)

It is hard to understand why this is happening. I have read your paper and I think removing sentences instead of words shouldn't matter. It seems to work, only the highlighting seems off. Any ideas?

**Comment by abevieiramota** [comment]
I think the sentences' start positions calculation also should be adjusted. Current code considers that between two pieces of text(words, or sentences, in your case) there is one character. But I think this is not the case in your example(probably there are spaces before the line break character).
Try this(from https://stackoverflow.com/a/14800487):

```python
from nltk.tokenize.punkt import PunktSentenceTokenizer

self.raw = raw_string
sentences_span = PunktSentenceTokenizer().span_tokenize(self.raw)
self.as_list = [self.raw[begin:end] for (begin, end) in sentences_span]
self.as_np = np.array(self.as_list)
non_word = re.compile(r'(%s)|$' % split_expression).match
self.string_start = np.array([begin for (begin, end) in sentences_span])
```

**Comment by jacobmalmberg** [comment]
It works! Thanks!
