### ISSUE TITLE
Using lime with a RPN network

### ISSUE THREAD

**Issue by alexattia** [marcotcr/lime#159]
Hello,
I would like to know if it's possible to use lime with an RPN network (such as Faster R-CNN or RetinaNet).   

Indeed, I have seen the tutorial for image classification with Keras but I was wondering if you have a similar tutorial/explanations for an object detection model : 
`detections, scores = predict_detection(img_path, model)`
with `detections = [(x1,y1,x2,y2), ...]` , `detections.shape = (n_samples, 4)`  
and `scores = [p1, p2, ...]` , `detections.shape = (n_samples, 1)`   

Thank you very much in advance.

**Comment by marcotcr** [comment]
I don't know what you would explain in that case. I can imagine explaining a function of the output such as the presence / absence of a particular object in the prediction (which can be done) or a function like 'the area of the dog prediction is larger than X', but I don't know how I would go about representing the explanation for the whole structured output.

**Comment by isaacmg** [comment]
I would be interested in this as well. Mainly what are the relevant sub-segments for each region proposal and their impact on overall (region) score.

**Comment by gudovskiy** [comment]
@alexattia I did a project for SSD detector. You can check results here https://github.com/gudovskiy/e2x
