### ISSUE TITLE
The imagenet retrieval address is not working

### ISSUE THREAD

**Issue by nickyongzhang** [marcotcr/lime#160]
Thanks for the wonderful tool first!

I came across with an error when running the ipython notebook 'Tutorial - images' and found that the url address for retrieving imagenet data is not working. It should change to a new address.

>base_url = 'https://raw.githubusercontent.com/tensorflow/models/master/inception/inception/data/'

 to
>base_url = 'https://raw.githubusercontent.com/tensorflow/models/master/research/inception/inception/data/'
 -----
Update: I am sorry that I didn't make it clear when proposing the problem initially. The path issue actually belongs to the related repo 'marcotcr/tf-models', which @marcotcr has actually resolved the problem already in his one commit last Nov. It's kind of weird I came across with the path issue about one month ago.
Anyway, this should not be an issue for others.

Thanks for the wonderful tool again.

**Comment by marcotcr** [comment]
Sorry, where is this in the tutorial?

**Comment by nickyongzhang** [comment]
@marcotcr As said in the updated comment, this is not an issue anymore. I will close the issue.
Sorry for the trouble and accept my sincere thanks.
