### ISSUE TITLE
ValueError: Error when checking : expected input_1 to have shape (None, 128, 128, 1) but got array with shape (10, 128, 128, 3) using explanation = explainer.explain_instance(test_explaination, model.predict)

### ISSUE THREAD

**Issue by naeimbah** [marcotcr/lime#161]
Hi, 
I am trying to explain the predictions of my VGG19 model and get the error below:
KERNEL_SIZE = 3
NUM_CLASSES = 2
LEARN_RATE = 10e-4
EPOCHS = 15
DECAY = LEARN_RATE/EPOCHS
IMG_SIZE = 128
input_shape = [
    128,
    128,
    1,
]
#model.fit --> VGG19 
.
.
pred = Dense(NUM_CLASSES, activation = "softmax", name = 'predictions')(fc)
model = Model(inputs=inputs, outputs=pred, name='vgg19')
model.compile(loss = binary_crossentropy,optimizer=SGD(lr=LEARN_RATE,decay=DECAY,momentum=0.1,),
    metrics = ['accuracy']
)
     I am using one-hot
test_explain.shape = (128, 128) #gray scale 2D
explanation = explainer.explain_instance(test_explain, model.predict)

Traceback (most recent call last):
  File "lime_test.py", line 211, in <module>
    explanation = explainer.explain_instance(test_explain, model.predict)
  File ".../tensorflow/lib/python2.7/site-packages/lime/lime_image.py", line 187, in explain_instance
    batch_size=batch_size)
  File ".../tensorflow/lib/python2.7/site-packages/lime/lime_image.py", line 248, in data_labels
    preds = classifier_fn(np.array(imgs))
  File "/Library/Python/2.7/site-packages/Keras-2.0.5-py2.7.egg/keras/engine/training.py", line 1576, in predict
    check_batch_axis=False)
  File "/Library/Python/2.7/site-packages/Keras-2.0.5-py2.7.egg/keras/engine/training.py", line 139, in _standardize_input_data
    str(array.shape))
**ValueError: Error when checking : expected input_1 to have shape (None, 128, 128, 1) but got array with shape (10, 128, 128, 3)**

I have no idea where this '10' comes from either the '3' , but got array with shape (10, 128, 128, 3)!

**Comment by expectopatronum** [comment]
I currently have the same issue, I guess [this](https://github.com/marcotcr/lime/pull/116) is related. The comment mentions that this works now for shape=2 but is not necessary for shape=1 ... I dont really understand why, since my gray scale images usually have shape [x, y, 1]...

**Comment by marcotcr** [comment]
LIME generate instances in the neighborhood of the image you want to explain. The default batch size for those images is `10`, which is where you get the 10 in (10, 128, 128, 3) from.
As per [this line](https://github.com/marcotcr/lime/blob/master/lime/lime_image.py#L132), we assume that the image is either 3d or 2d (in which case we convert it to 3d). This implies that the predict function must take a 3d RGB image with 3 channels in the last dimension (x, y, 3), while yours takes in (x, y, 1). A quick fix is to fold a conversion function into the predict function, something like:
```
def new_predict_fn(images):
    images = convert_to_1channel(images)
    return model.predict(images)
```
(and use this when explaining)

**Comment by yosepppph** [comment]
Can you write an example of a conversion function?

**Comment by segobrsm** [comment]
Hi! I can't do it either. I want to use explain_instance() on a grayscale image. 

I've tried two ways :

- Giving the image with shape (1, 70, 70, 1) and I have : 
`ValueError: the input array must be have a shape == (.., ..,[ ..,] 3)), got (1, 70, 70, 1)` 
- Giving the image with shape (70, 70) and I have : 
`ValueError: Error when checking input: expected conv2d_4_input to have shape (70, 70, 1) but got array with shape (70, 70, 3)`

Because my CNN is trained on grayscale images. How can I do the image conversion?

**Comment by psyllost** [comment]
Could the image conversion affect the results of the explainer in some way?
