### ISSUE TITLE
Tutorial - Faces and GradBoost:  KeyError: 'Label not in explanation'

### ISSUE THREAD

**Issue by kaisark** [marcotcr/lime#165]
I am running into the folllowing error in the Tutorial - Faces and GradBoost notebook:

from skimage.color import label2rgb
temp, mask = explanation.get_image_and_mask(y_test[0], positive_only=True, num_features=5, hide_rest=False)
fig, (ax1, ax2) = plt.subplots(1,2, figsize = (8, 4))
ax1.imshow(label2rgb(mask,temp, bg_label = 0), interpolation = 'nearest')
ax1.set_title('Positive Regions for {}'.format(y_test[0]))
temp, mask = explanation.get_image_and_mask(y_test[0], positive_only=False, num_features=10, hide_rest=False)
ax2.imshow(label2rgb(3-mask,temp, bg_label = 0), interpolation = 'nearest')
ax2.set_title('Positive/Negative Regions for {}'.format(y_test[0]))

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-13-8f7ea57f7046> in <module>()
      1 from skimage.color import label2rgb
----> 2 temp, mask = explanation.get_image_and_mask(y_test[0], positive_only=True, num_features=5, hide_rest=False)
      3 fig, (ax1, ax2) = plt.subplots(1,2, figsize = (8, 4))
      4 ax1.imshow(label2rgb(mask,temp, bg_label = 0), interpolation = 'nearest')
      5 ax1.set_title('Positive Regions for {}'.format(y_test[0]))

~/.virtualenvs/testpy3/lib/python3.5/site-packages/lime/lime_image.py in get_image_and_mask(self, label, positive_only, hide_rest, num_features, min_weight)
     49         """
     50         if label not in self.local_exp:
---> 51             raise KeyError('Label not in explanation')
     52         segments = self.segments
     53         image = self.image

KeyError: 'Label not in explanation'

**Comment by marcotcr** [comment]
I guess the notebook is assuming the correct label will be in the top 6 predicted by the model, but for some reason your model is not exhibiting this behavior.
You have two options:
1. get explanations for a different label (i.e. replace `y_test[0]` with `simple_rf_pipeline.predict(X_test[0])`)
2. compute explanations for all labels, i.e. replace `top_labels=6` with `top_labels=40`
