### ISSUE TITLE
LIME explainer not showing in Jupyter Lab

### ISSUE THREAD

**Issue by Zohaggie** [marcotcr/lime#167]
Not sure if this is something you can handle on your end or not, but I am testing latest Jupyter Lab and it doesn't display output from the Explainer.

**Comment by marcotcr** [comment]
Sorry, I am not even familiar with Jupyter Lab, so can't help you there. The way we display output is a little weird, as we manipulate the DOM - they may not like that. One (inconvenient) alternative is to save the output to an html using `save_to_file`.
