### ISSUE TITLE
Design of the sampling algorithm for texts

### ISSUE THREAD

**Issue by dolaameng** [marcotcr/lime#17]
I am referring to the implementation of [text sampling method for neighborhood data](https://github.com/marcotcr/lime/blob/master/lime/lime_text.py#L268). My understanding is that it randomly removes a subset of words from the original text. 

Is this a limitation or special design? It seems to me that sometimes a text is classified not only for the presence of certain words, but also for the absence of others. For example, a message might classified as non-insulting not because of the words in it, but the words NOT in it. 

So sampling texts by removing only would result in a narrower space to search in, which could result in a different class distributions even in the vicinity, e.g., all sampled data have positive labels as an extreme case. Appreciate it if you can elaborate on the sampling part.

**Comment by marcotcr** [comment]
This was a conscious choice. While there are cases where the absence of terms explains more than the presence, I think that text explanations become a bit confusing when adding 'absence' explanations.

In the insult example you gave, the way to interpret a 'null' explanation (no words) is 'there is no evidence of insult in this message, and in the absence of such evidence the model predicts non-insult'. Would it be better to explain it as 'none of the following words are in it: [list of 100 insulting words']? Maybe, but I think it becomes too confusing.

**Comment by dolaameng** [comment]
@marcotcr thanks for reply. Yes the difficulty arises when I am thinking about generalizing the model to other data. For example, when using complicated features (e.g., RNN rather than TFIDF) for texts, I am not sure if the sampling-by-removing method would still work, because removing a word might actually result in a complicated disjoint regions in the feature space, and thus the "neighborhood" assumption may not hold any more for the interpretable linear approximation. At least the signs of coefficients would not be directly interpretable as in the TFIDF cases. 

Do you think it would be useful to make sampling a separate class, just like the Explanation class, so that sampling can be customized in different ways for different types of data/feature combination? Thanks!

**Comment by andrewyates** [comment]
@dolaameng I've been thinking along similar lines (i.e., how the sampling procedure affects RNNs). I think it may be reasonable as long as the removed terms are replaced with UNK tokens rather than completely removed. Did you have another sampling procedure in mind?

**Comment by marcotcr** [comment]
I do have the option of replacing the removed term s with UNKs (just set bow=False), and I've used it to explain LSTMs with (I think) good results.
I think I may separate the data types (text, tabular, image) further in a future refactor, to make it easier to plug in different sampling strategies. Do you have other sampling ideas though? I couldn't think of anything other than:
- removing words
- replacing words with UNK
- replacing words with other words (via language model, random words, whatever)

**Comment by dolaameng** [comment]
@andrewyates @marcotcr I agree it is challenging to keep the sampling part flexible and interpretable at the same time.  Considering that the computation of sampling needs to be fast to be useful, many complicated methods (e.g.,language modelling) may already be off the table. 

Actually I am not even sure if the "sampling" and "feature-selection" steps should be decoupled, since both of them depend on the data/tasks, and thus highly correlated to each other.

No I don't really have any better ideas. But in the context of neural networks, it might be interesting to look at the gradient w.r.t inputs to say which parts are contributing to the final predictions. Again it is not something new - I think [deep dreams](https://research.googleblog.com/2015/06/inceptionism-going-deeper-into-neural.html)  by Google was related to this idea. But I am not sure if anyone has done similar things to texts data. The drawback is that its result and interpretation will be specific to your model.

I am happy to see any new explorations.

**Comment by marcotcr** [comment]
Yeah, we're trying to always treat the models as black boxes (so no looking at gradients for now). Anyway, I'm actively working on this, hopefully I'll make some progress soon : ).
For now, I'll close the issue. Thanks for the insightful discussion.
