### ISSUE TITLE
lime_tabular sample data not around X

### ISSUE THREAD

**Issue by yerrick** [marcotcr/lime#170]
Hello, I found lime_tabular.py not sampling data around X but with feature mean/stddev when not using discretizer or with feature frequence when using discretizer. It will sample data in the whole feature space centered in the mean of features but not around the data to explain.

My question is why does the method of lime_tabular not sample data around the point to be explained ? 

Thanks.

**Comment by marcotcr** [comment]
After sampling broadly, instances are weighted according to distance. 
See also #63, #59, #55

**Comment by yerrick** [comment]
Thanks
