### ISSUE TITLE
Is there a way to interpret the text classification results from embedding + 1d CNN

### ISSUE THREAD

**Issue by Jiannan28** [marcotcr/lime#172]
Thx for the great package. 

I am currently using word embedding + 1d cnn for text classification. I would like to know if it's possible to explain the results with lime.

For example, if we want to explain one text (the 31st text in the corpus), is that the right way or I miss something?

from lime.lime_text import LimeTextExplainer
explainer = LimeTextExplainer(class_names=twenty_train.target_names)
idx = 30
exp = explainer.explain_instance(np.array([test_data[idx]]), model.predict, num_features=6, top_labels=2)

Thank you.

**Comment by marcotcr** [comment]
I assume your test_data is already an array of embeddings, or idxs. What you want to do is to use a string as the first parameter in explain_instance, and wrap the predict function into a function that takes in a list of strings and returns prediction probabilities. Something like:
```
def new_predict(x):
    data = strings_to_embeddings(x)
    return model.predict_proba(data)
```
Does this make sense?

**Comment by Jiannan28** [comment]
Marco,

Thank you for quick reply. 

Get your idea. I rewrite my function to this : 
idx = 30
exp = explainer.explain_instance(twenty_test.data[idx], new_predict(twenty_test.data[idx]), num_features=6, top_labels=2)

with the predict function wrapper : 
def new_predict(_text):
    _seq = tokenizer.texts_to_sequences([_text])
    _text_data = pad_sequences(_seq, maxlen=MAX_SEQUENCE_LENGTH)
    return model.predict(_text_data)

So the twenty_test.data[idx] is the raw text, and the new_predict function convert the raw text first to sequence then use the already 1dcnn model (trained with keras) to predict. 

When I call the explainer, I get the error : 'TypeError: 'numpy.ndarray' object is not callable'. I think the reason is that the new_predict I pass is not the right format of model classifier format as required in explain_instance function? a bit confusing about how to rewrite the wrapper to make it eligible for the signature of explain_instance function. 

Thank you in advance for your advice.

**Comment by marcotcr** [comment]
new_predict should take a list of strings rather than a single string, it should look something like:
```
def new_predict(texts):
  _seq = tokenizer.texts_to_sequences(texts)
  _text_data = pad_sequences(_seq, maxlen=MAX_SEQUENCE_LENGTH)
  return model.predict(_text_data)
```



also, you should call it like this:
`exp = explainer.explain_instance(twenty_test.data[idx], new_predict, num_features=6, top_labels=2)`
rather than:
`exp = explainer.explain_instance(twenty_test.data[idx], new_predict(twenty_test.data[idx]), num_features=6, top_labels=2)`

**Comment by Jiannan28** [comment]
Thank you Marco!  I works perfectly, and now I can use it to explain my embedding + 1d CNN or embedding + LSTM results. BTW, if you think necessary to add, I can create an example notebook for this process, coz I think it's very common that users will use LIME to explain the classification results of embedding + 1d CNN or embedding + LSTM. Happy to hear your thoughts.

**Comment by moonlightlane** [comment]
@Jiannan28 Hi there, I just started learning to use LIME and stumbled upon this issue that you opened. I work on recurrent neural models for both text classification and language generation tasks (which is nothing other than a sequential classification task). It would be great and very useful if you could share (via github, for example) a notebook or tutorial of how you incorporate LIME into an existing recurrent model such as LSTM, because I do agree that such usage case is very common. Thanks in advance!

**Comment by marcotcr** [comment]
@richielo Did you figure out what the issue was? texts should be a list where the size is num_samples

**Comment by Jiannan28** [comment]
Hi @marcotcr . First of all, thank you for providing all the great advice. Thanks to your advice, now it's able to use lime to interpret 1d-cnn or rnn prediction results for individual samples. However, if we want to know in general, what are the text features impact the prediction results (similar like feature imp) for all samples, how can we use lime for that? Is there a way / guideline about how to choose the representative individuals from all samples? It seems that sth has been mentioned in your paper, but not that clear for me...

**Comment by marcotcr** [comment]
Yes, but unfortunately I never released code for it. It's section 4 in the [paper](https://arxiv.org/pdf/1602.04938.pdf), also take a look at #11, It's implemented [here](https://github.com/marcotcr/lime-experiments/blob/8fd31c7c81facb240fdf728a50d029af8c452af5/compare_classifiers.py#L20) assuming explanations are precomputed.
Also, if you have a good notebook with a tutorial and you want to share, I'm happy to add it to the list of tutorials.

**Comment by romass12** [comment]
I am getting error : cannot use a string pattern on a bytes-like object
My model has embedding layer at the start so the input shape is n_sample,n_timesteps instead of 3d dimensions

**Comment by harirajeev** [comment]
I found this answer very userful. Just in case anybody needs it.
https://stackoverflow.com/questions/54072496/explaining-cnn-keras-outputs-with-lime
