### ISSUE TITLE
lime_tabular discards local scores and predictions in multiclass problems

### ISSUE THREAD

**Issue by Craigacp** [marcotcr/lime#173]
It looks like lime_tabular and lime_text discard the local model's scores and predictions for all but the last label (line 359 in lime_tabular.py, line 278 in lime_text.py). The previous lines store the intercept and parameters in `ret_exp.intercept[label]` and `ret_exp.local_exp[label]` respectively, but the score and predictions are repeatedly written to the same `ret_exp.score` and `ret_exp.local_pred` variables. Given the label ordering when using `top_labels` I think this means it only stores the score for the least probable of the top n labels, or the last label supplied to `labels`.

**Comment by marcotcr** [comment]
You are right, this is a bug whenever we have more than one label. I have to think if I want to change the interface so that `ret_exp.score` and `ret_exp.local_pred` become dicts (breaking whoever relies on them being floats) or do something else.
Thanks!
