### ISSUE TITLE
TypeError: unhashable type

### ISSUE THREAD

**Issue by Raghavvraj** [marcotcr/lime#174]
Hi,

I am trying to use the LIME package and identify the factors that drive prediction. But i am facing this issue. Would be great if someone can help me out

Thanks
Raghav

explainer = lime.lime_tabular.LimeTabularExplainer(train, 
                                                   feature_names=list(dataset.data), 
                                                   categorical_features=categorical_features, 
                                                   verbose=True, mode='classification')

ERROR:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-98-b26816105749> in <module>()
      2                                                    feature_names=list(dataset.data),
      3                                                    categorical_features=categorical_features,
----> 4                                                    verbose=True, mode='classification')

C:\Users\ragvi\AppData\Local\Continuum\anaconda2\lib\site-packages\lime\lime_tabular.pyc in __init__(self, training_data, mode, training_labels, feature_names, categorical_features, categorical_names, kernel_width, verbose, class_names, feature_selection, discretize_continuous, discretizer, random_state)
    162                 self.discretizer = QuartileDiscretizer(
    163                         training_data, self.categorical_features,
--> 164                         self.feature_names, labels=training_labels)
    165             elif discretizer == 'decile':
    166                 self.discretizer = DecileDiscretizer(

C:\Users\ragvi\AppData\Local\Continuum\anaconda2\lib\site-packages\lime\discretize.pyc in __init__(self, data, categorical_features, feature_names, labels, random_state)
    123         BaseDiscretizer.__init__(self, data, categorical_features,
    124                                  feature_names, labels=labels,
--> 125                                  random_state=random_state)
    126 
    127     def bins(self, data, labels):

C:\Users\ragvi\AppData\Local\Continuum\anaconda2\lib\site-packages\lime\discretize.pyc in __init__(self, data, categorical_features, feature_names, labels, random_state)
     44 
     45         # To override when implementing a custom binning
---> 46         bins = self.bins(data, labels)
     47         bins = [np.unique(x) for x in bins]
     48 

C:\Users\ragvi\AppData\Local\Continuum\anaconda2\lib\site-packages\lime\discretize.pyc in bins(self, data, labels)
    128         bins = []
    129         for feature in self.to_discretize:
--> 130             qts = np.array(np.percentile(data[:, feature], [25, 50, 75]))
    131             bins.append(qts)
    132         return bins

C:\Users\ragvi\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\frame.pyc in __getitem__(self, key)
   1962             return self._getitem_multilevel(key)
   1963         else:
-> 1964             return self._getitem_column(key)
   1965 
   1966     def _getitem_column(self, key):

C:\Users\ragvi\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\frame.pyc in _getitem_column(self, key)
   1969         # get column
   1970         if self.columns.is_unique:
-> 1971             return self._get_item_cache(key)
   1972 
   1973         # duplicate columns & possible reduce dimensionality

C:\Users\ragvi\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\generic.pyc in _get_item_cache(self, item)
   1641         """Return the cached item, item represents a label indexer."""
   1642         cache = self._item_cache
-> 1643         res = cache.get(item)
   1644         if res is None:
   1645             values = self._data.get(item)

TypeError: unhashable type

**Comment by marcotcr** [comment]
is train a dataframe instead of a numpy array?

**Comment by Raghavvraj** [comment]
Thanks, Marco... i think that's the error. Changing it as a Numpy array worked.

Thanks!
