### ISSUE TITLE
Dummy variables question

### ISSUE THREAD

**Issue by matteo8904** [marcotcr/lime#175]
Hi Developers,

I am new to Lime and I really enjoy it.
I have a question regarding the use of dummy variables. 
If I have not misunderstood the method, Lime builds a dataframe with the neighbourhood of a given test point in order to construct the local approximation of the model. At this stage dummy variables are kept constant or are they allowed to vary like any other continuous or categorical feature? 
I have the feeling that for some models it would be very nice to keep fixed some variables and study the local behaviour of the other ones.

Thank you very much in advance for any reply.
All my best,

Matteo.

**Comment by marcotcr** [comment]
Hey, sorry for the delay in responding.
If by dummy variables you mean indicator variables, they are perturbed like any other feature.
If you want to keep certain features fixed while you want to understand other features, you can do it by hiding those features from LIME and writing a wrapper for the predict function that includes them, something like
```
def new_predict_fn(data):
  data = np.hstack((data, other_features))
  return predict_fn(data)
```
