### ISSUE TITLE
Model variables' confidence intervals

### ISSUE THREAD

**Issue by Tagar** [marcotcr/lime#182]
Does LIME provide confidence intervals for variables? 
I was at Strata Conference last month and I think on this presentation https://conferences.oreilly.com/strata/strata-ca/public/schedule/detail/63572 it was mentioned variables' confidence intervals one of the functions of LIME, if I don't miss anything.. 
Looking at the LIME code now and I don't see this functionality.
Is this planned to have this in the future?
A variable can be "important" (ranked on coefficient values), but if small changes on input of this value causes huge fluctuations on model's output, this varaible's contribution confidence can be negative.. 
Thanks!

**Comment by marcotcr** [comment]
No, we don't have confidence intervals for variables. I didn't see the presentation, but maybe he was talking about our [anchor](https://github.com/marcotcr/anchor) explanations, where we use confidence intervals throughout and provide an explanation with probabilistic guarantees, but I don't know.

Sorry!
