### ISSUE TITLE
Problem with getting explanations for regression.

### ISSUE THREAD

**Issue by alexv71** [marcotcr/lime#184]
Hi developers,

I got a strange things when I am working with explanation for regression.
First of all I tried to run your example: **Using lime for regression.ipynb**
When I repeated this cell

_exp = explainer.explain_instance(test[i], rf.predict, num_features=10)
exp.show_in_notebook(show_table=True)_

Every time I got a slightly different results. But I expected, that it should be absolutely the same.

And in my own example I got very different results when I changed num_features.
I used a simple RF regression models with only continuous features, no categorical features.
It is also only two lines of code:

_explainer = lime.lime_tabular.LimeTabularExplainer(df.values, feature_names=feature_names, verbose=True, mode='regression')
exp = explainer.explain_instance(test_example, rf.predict, num_features=10)_
where df is a pandas dataframe, feature names is a column names of this dataframe.

Could you please tell me, what may be wrong? How to obrain a good explanations for regressions, if I have, for instance, about 2000 numerical features?

Thank you so much in advance.

**Comment by lindskogniklas** [comment]
Have you created the explainer with the kwarg random_state set? Otherwise the samples and thereby the results will be different for each run.
explainer = LimeTabularExplainer(training_set, random_state=42)

**Comment by marcotcr** [comment]
> Every time I got a slightly different results. But I expected, that it should be absolutely the same.

LIME uses random samples, it will not be exactly the same unless you fix the random seed (like mentioned above

> And in my own example I got very different results when I changed num_features.

If you have 2000 numerical features and the model is using a lot of those in each prediction, you should expect to get different explanations if you vary the explanation size. The smaller the explanation size (k), the worse the approximation will be, but the easier to read it is.
