### ISSUE TITLE
Sampling categorical features

### ISSUE THREAD

**Issue by echo66** [marcotcr/lime#187]
Greetings!

I was looking into the code and saw this line

https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L415

why is LIME sampling categoricals features using the frequency of each category instead of assigning the same probability for each category?

**Comment by marcotcr** [comment]
That gives us a nice interpretation of what 'off' means for a categorical feature value: you get an average of what happens when the value is not the current value.

**Comment by echo66** [comment]
Sorry but I'm not following your reasoning. In what way creating way more points with a specific category helps you? Why not sampling all categories with the same probability?

**Comment by marcotcr** [comment]
Think about the following feature distribution for 'weight':
'130-150 lb': 40%
'151-160 lb': 20%
'160-180 lb': 39%
'180-200lb': 0.9%
'> 200lb': 0.1%

Let's say that the model is a linear model with some positive coefficient on this feature. What is the effect for a person who weights 155lb? If you sample all categories with the same probability you'll think the effect is VERY high, because you will sample extreme weights with much more frequency than you would expect, and the effect will be computed with respect to that.

**Comment by echo66** [comment]
One think is what I think about the impact of a feature in the real world, another is how the model "sees" it. I have no guarantees about the impact of a set of feature values in the model output, specially if I haven't made any predictions with that model. Also, that assumption introduces bias into the local model training because it seems that you are assuming a partial order between categorical elements, right?

**Comment by marcotcr** [comment]
No, I'm not assuming a partial order, I just did for this example. The point is that for a categorical feature X, we are computing the impact of X=x (X takes a particular value, e.g. Weight > 200lb). This impact is computed w.r.t. some distribution of X != x, and I think it makes more sense to use a distribution based on the original data than an arbitrary uniform distribution.

**Comment by echo66** [comment]
Sorry for the delay, Marco! 

When you say _"I think it makes more sense to use a distribution based on the original data than an arbitrary uniform distribution"_, is that statement based on some previous study? I can easily understand why you want to use a gaussian distribution around the query observation (even though the current implementation samples around the dataset mean but that is kind of easy to fix): you want to focus your sampling procedure around the point to inspect the "local dynamics" (should I use this term?). So, in that case, the mean of the sampling distribution would be the query observation and the variance could be arbitrary, controlled by a parameter like *sampling_width* (wink wink *kernel_width*).

I think I went ta bit offtopic on this. Sorry if that is the case. :|

**Comment by marcotcr** [comment]
> When you say "I think it makes more sense to use a distribution based on the original data than an arbitrary uniform distribution", is that statement based on some previous study? 

No, not a study - there is no 'ground truth' here. The perturbation distribution is a design choice that determines how explanations should be interpreted, and whichever distribution we use must be something we can communicate to users and they can reason about.
> I can easily understand why you want to use a gaussian distribution around the query observation (even though the current implementation samples around the dataset mean but that is kind of easy to fix): you want to focus your sampling procedure around the point to inspect the "local dynamics" (should I use this term?). So, in that case, the mean of the sampling distribution would be the query observation and the variance could be arbitrary, controlled by a parameter like sampling_width (wink wink kernel_width).

For continuous features, there is an option to sample around the examples being explained, see #186.

**Comment by echo66** [comment]
Hey Marco! 

I've been thinking about something related to this issue: when you have a new category, the current approach for categorical sampling will always generate a synthetic sample of the space that won't include any synthetic examples with that new category. This means that (AFAIK) the categorical feature will "ignored" by the local model. In a way, this assumes that the model won't be able to deal with new categories. But that is a very strict assumption since we can use things like feature hashing to deal with unknown categories.

**Comment by marcotcr** [comment]
Yes, we assume that the categories are fixed. I don't know how to relax that assumption - we need to assume something when we are sampling perturbed values. Right now we assume not only that we know what the categories are, but their relative frequency.

**Comment by echo66** [comment]
Thanks for the quick and clear answer, @marcotcr !
