### ISSUE TITLE
Udiscretize function

### ISSUE THREAD

**Issue by mizukasai** [marcotcr/lime#188]
Hello, 

While reading the code, I found it weird that the function udiscretize (in BaseDiscretizer) samples from a normal distribution defined by the data and then limits it to [min,max] if it goes beyond its bounds. Correct me if I'm wrong but it seems to me that this creates a weird distribution (two peaks in min and max).
For me a better way to do it is to use a truncated normal distribution (I found one in scipy : scipy.stats.truncnorm )

**Comment by marcotcr** [comment]
You are right on the peaks. Good suggestion, do you want to do a quick pull request? If not that's fine
: )

**Comment by marcotcr** [comment]
fixed in ec51505acf4f66be7535368e084e59f3e4ac6ff2
