### ISSUE TITLE
"almost" Bag of Words Text models 

### ISSUE THREAD

**Issue by ophiry** [marcotcr/lime#190]
I'm trying to use lime with textual models, these models aren't strictly using bag of words - but they usually have low sensitivity to repetition of words \ patterns

So when using bag of words mode, lime may select words that aren't relevant (only other instances of this word is significant), on the other hand, when not using bag of words important words may be missed.

any ideas how to handle this?

**Comment by marcotcr** [comment]
I don't quite understand why not using bag of words will miss important words. Can you please give an example of what you mean?
