### ISSUE TITLE
Permission to include a LIME picture in our bachelor thesis

### ISSUE THREAD

**Issue by jacobmalmberg** [marcotcr/lime#191]
Hello,

we are currently writing our bachelor thesis about machine learning and LIME and would like permission to include a figure, https://github.com/marcotcr/lime/blob/master/doc/images/twoclass.png, of LIME. Is this ok? It will be published on diva-portal.org under a no-profit license.

Best regards,
Jacob, Alexandra and Marcus

**Comment by marcotcr** [comment]
You can use whatever figures you want, as long as you cite the paper or make a reference to the open source package.
