### ISSUE TITLE
Allowing custom tokenization function in LimeTextExplainer

### ISSUE THREAD

**Issue by gsireesh** [marcotcr/lime#192]
Currently, the `LimeTextExplainer` implicitly tokenizes with a regex that defaults to `\W+`. I'd like to be able to pass a `callable` in that does the tokenization in the same way that my pipeline does - both for consistency between the two, and also so that if my pipeline tokenizes (e.g.) named entities as single tokens, the algorithm would perturb with those in a sensible way. This would be conceptually similar to how `sklearn` allows either strings or callables for parameters.

For example, if I had the sentence "General Mills announced a new product", and my tokenization function returned `['General Mills', 'announced', 'a', 'new', 'product']`, regex tokenization isn't sufficient to replicate how the pipeline actually sees the text. 

I'm happy to submit a PR to do this, but wanted to put this out there before I jumped the gun. It shouldn't be a change that breaks the public API.

**Comment by marcotcr** [comment]
Thanks for the PR. I like the idea of allowing for custom tokenization, but we have to figure out how to reconstruct the string after perturbing instances (I left a comment in the PR. When you fix it, please try running inverse_removing with the new indexed string).
