### ISSUE TITLE
show_in_notebook() does not work in Jupyter Lab

### ISSUE THREAD

**Issue by seansaito** [marcotcr/lime#193]
I'm following the tutorial [here](https://marcotcr.github.io/lime/tutorials/Tutorial%20-%20continuous%20and%20categorical%20features.html) using Jupyter Lab, and the `show_in_notebook` function is not plotting the diagrams as seen in the tutorial. It does work when I use Jupyter Notebook, however.

**Comment by marcotcr** [comment]
Jupyter Lab is still in beta, so I won't even try to support it at the moment. The way we render js in Jupyter Notebook is already a hack : )
