### ISSUE TITLE
LIME discretization? 

### ISSUE THREAD

**Issue by Dilini-Sewwandi-Rajapaksha** [marcotcr/lime#196]
Why does LIME uses discretization?

**Comment by marcotcr** [comment]
Discretization is the default for numerical data, but you can disable it if you want.
It is harder to interpret explanations for numerical features for the following reasons:

1. The values may be in different ranges. We can always standardize the data, but then the meaning of the coefficients changes
2. It's hard to think about double negatives (i.e. negative weight for a negative feature = positive contribution)

See #113
