### ISSUE TITLE
Explain a retrained inceptionv3(with Keras)

### ISSUE THREAD

**Issue by LudwigSchallner** [marcotcr/lime#197]
Hello,

Im trying to adapt the "Images with Keras" Tutorial on my own case.
`explainer = lime_image.LimeImageExplainer()
%%time
explanation = explainer.explain_instance(img, my_model.predict, top_labels=5, hide_color=None, num_samples=1000)`
i get this error message: "sequence argument must have length equal to input rank"

may someone help me?

**Comment by marcotcr** [comment]
Does my_mymodel.predict take in a numpy array with 4 dimensions, where the first is the number of samples and the last correspond to 3 channels?
If you're doing any preprocessing, is that all included in my_model.predict?

**Comment by LudwigSchallner** [comment]
Now it does. Thank you very much :)
