### ISSUE TITLE
NaN and Infinity

### ISSUE THREAD

**Issue by rspadim** [marcotcr/lime#198]
Could be possible using tabular explainer, fit columns with NA or Inifinity?
I have some datasets with NAN and xgb models that allow NAN inputs

**Comment by rspadim** [comment]
the 'problem' is sklearn standard scaller

https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L200

and NaN/Infinity handling 

https://github.com/scikit-learn/scikit-learn/issues/3782

**Comment by marcotcr** [comment]
I don't think we'll support this. Handling NaNs and infinity will be bothersome, and I don't think almost anyone uses models that deal with these.

**Comment by Sam-80** [comment]
Definitely think it would be useful

**Comment by zubinmehta** [comment]
NaNs are definitely useful.
