### ISSUE TITLE
Evaluating a custom VGG-16 model with LIME visualization

### ISSUE THREAD

**Issue by raaju-shiv** [marcotcr/lime#203]
Thanks for this awesome visualization tool. I would like to make use of this tool for visualizing a custom VGG16 model that has only two outputs to classify normal and abnormal chest x rays. I cant usse the default decode_predictions function. My class indices are 0 for abnormal and 1 for normal. Can I use these indices directly in the computation of temp and mask?
Do you have an example of applying LIME visualization to custom models to share? Or can you suggest the modifications to be made to the code to suit my problem requirements? 
Do I have to use plt.imshow(images[0] / 2 + 0.5) and plt.imshow(mark_boundaries(temp / 2 + 0.5, mask))even for my custom VGG16 model?  Thanks and looking forward.

**Comment by marcotcr** [comment]
hopefully you figure it out : )
