### ISSUE TITLE
Regressor XGboost Lime

### ISSUE THREAD

**Issue by kikilou** [marcotcr/lime#204]
Hi! 

I'm trying to explain a regression that I've done with the package "xgboost", with LIME, but it doesn't work and I havn't found any example of such code on the Internet. Do you know if that's even possible? Would you have a simple example that is working? I can make it work when it's a classification issue, but not with regression. 

Thank you!

**Comment by kikilou** [comment]
I have this error when I changed from numeric to factor my variables : 
"Error in xgboost::xgb.DMatrix(as.matrix(newdata)) : 
  'data' has class 'character' and length 120000.
  'data' accepts either a numeric matrix or a single filename.". 

Thank you for your help!

**Comment by marcotcr** [comment]
Sorry, we don't maintain the R code at all. You should ask your question in [the right repository](https://github.com/thomasp85/lime).
