### ISSUE TITLE
LIME explainer for VGG16 network 

### ISSUE THREAD

**Issue by waqarws** [marcotcr/lime#207]
I am using the tutorial code modified for VGG16 network. VGG16 takes image format -255 to 255 whereas the segmentation function expects images of float type between -1 to 1. How do I use the following line of code for VGG16

````
explainer = lime_image.LimeImageExplainer()

explanation = explainer.explain_instance(image, predict_fn, top_labels=5, hide_color=0, num_samples=1000)
````

Here image has to be one format for segmentation algorithm and VGG16 model expects another format.

**Comment by marcotcr** [comment]
One quick and dirty solution is to use the image format expected by skimage, and wrap predict_fn such that it does something like:
```
def new_predict_fn(images):
   images = skimage_to_vgg(images)
   return predict_fn(images)
```
Another option is to pass in a custom segmentation function, take a look at [this](https://github.com/marcotcr/lime/blob/master/lime/lime_image.py#L149) and [this](https://github.com/marcotcr/lime/blob/master/lime/wrappers/scikit_image.py#L90).
