### ISSUE TITLE
Relationship between segmentation algorithm, kernel width, number of features and samples

### ISSUE THREAD

**Issue by ghost** [marcotcr/lime#208]
I have been training a custom model on medical images of 1024*1024 dimensions. As suggested by Marco, I am always using a higher number of samples to avoid issues due to setting a random seed in each run and averaging the results. However,  keep getting different explanations for the same image at different runs. Is there an optimal algorithm, kernel width, feature size and number of samples that the authors propose to avoid much of a deviation in the explanations?

**Comment by marcotcr** [comment]
Are you getting wildly different explanations or minor variations? You should expect minor weight differences, or different features being selected if the feature weights are very small (i.e. borderline irrelevant).
