### ISSUE TITLE
predict_proba and local_pred are different

### ISSUE THREAD

**Issue by kazemia** [marcotcr/lime#209]
Hi,
  I am trying to explain a model with lime. It is a classification problem, where the two classes are 0 and 1. My lime code is:
`explainer = LimeTabularExplainer(X_test.values, mode='classification', feature_names=X_test.columns,kernel_width=2, discretize_continuous=False)`

`exp = explainer.explain_instance(X_test.iloc[whichOBS,:].values, mlp.predict_proba, num_features=X_test.columns.size,labels=range(mlp.classes_.size))`

But when I call predict_proba and local_pred on exp, I get numbers that do not have anything to do with each other:

`exp.predict_proba`
array([0.19117735, 0.80882265])

`exp.local_pred`
array([0.73896437])

From my understanding, since the classes are 0 and 1, exp.local_pred and the second component of exp.predict_proba should be the same, but they are not.

Also, when I multipy the scaled data values with the coefficients from Lime, and sum up for all features and correct for the bias, I get the value of exp.local_pred. Now what should I do to get exp.predict_proba?

This is because I am trying to get feature contributions to the probability of class 1 for each instance, so that I can compare this with the results from treeinterpreter for random forest, which gives exactly that.

Thank you in advance :)

**Comment by marcotcr** [comment]
LIME does not guarantee that the linear model explanation will get the explained instance exactly right (i.e. exp.local_pred is not necessarily going to be equal to exp.predict_proba[1], but it should be close). If you find that it is frequently too far, you can decrease the `kernel_width`. Anyway, these are not directly comparable to treeinterpreter in this way. If you are doing random forests and want exact attribution, I would suggest [shap](https://github.com/slundberg/shap).
