### ISSUE TITLE
Extracting Local Model Coef_

### ISSUE THREAD

**Issue by EoinKenny** [marcotcr/lime#210]
Hi, this is just a followup issue with regards to the local model weights.

I have the following code.

```
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(X_train, y_train)  # Just the Taiwan credit dataset

explainer = lime.lime_tabular.LimeTabularExplainer(X_train, 
                                                   feature_names=feature_names, 
                                                   class_names=['N', "Y"],
                                                   verbose=False, 
                                                   discretize_continuous=False,
                                                   mode='classification')

i = 13
exp = explainer.explain_instance(X_train[i], clf.predict_proba)

total = 0
l = exp.as_map()[1]
l.sort()

for j in range(len(X_train[0])):
    total += X_train[i][j] * (l[j][1])
total + exp.intercept[1]
```

The issue is that my manual calculation of exp.local_pred is never exactly correct. Am I doing something wrong here? It should just be a simple matter of multiplying the input features by the weights plus intercept no?

The training data is just 3 continuous features.

Thanks a lot in advance!

**Comment by EoinKenny** [comment]
``
from sklearn.linear_model import LogisticRegression
``

**Comment by EoinKenny** [comment]
I just found this thread https://github.com/marcotcr/lime/issues/189 so I guess that's the issue I'm having? :)

**Comment by marcotcr** [comment]
In that case they had `discretize_continuous=True`, which it seems you do not.
But as I noted in one of the comments there, the weights are actually relative to the scaled data, so your feature_value column should be scaled. If you've scaled the entries, multiplied by the local pred and added the intercept, you should get a total that is pretty close to the predicted value (although not guaranteed to be exactly the same). If you turn on `verbose=True` in `explain_instance`, you'll see a printout of the original prediction and the explanation approximation.

**Comment by EoinKenny** [comment]
Thanks a lot @marcotcr 

Yes I took the advice in the other thread and scaled the instance properly, it exactly matches up now. My own manual calculation of  `exp.as_map() * scaled instance + exp.intercept` matches what LIME gives perfectly. 

There is something interesting I noticed though, which is that if I do this same procedure on data whilst progressively adding categorical variables the calculation becomes increasingly incorrect. However, if the data is purely continuous features there is no mismatch.

Does LIME generally struggle with categorical features? Can the coefficients still be trusted in this case? (when there are many categorical features) Thanks in advance.

**Comment by marcotcr** [comment]
I'm not sure I understand the question. Are you saying:
1. that the calculation stops matching the information shown when verbose=True, or
2. that the approximation displayed by verbose=True gets worse as you add categorical features
?

**Comment by marcotcr** [comment]
That is not normal. I think there are two bugs in your code:
1.  X_train[i, j] will be a categorical value (an integer) if feature[j] is categorical, whereas the explanation weight should be multiplied by 1, indicating the presence of the categorical value.
2. coefs will give you at most `num_feature` coefs (this is a parameter to explain_instance, the default is 10). If you have more than 10 features in your dataset, the multiplication won't work.

I think if you do
```
ids = [x[0] for x in coefs]
scaled_instance[categorical_features] = 1
manual_calculation = sum(coefs * scaled_instance[ids]) + exp.intercept[1]
```
you will get the same as exp.local_pred

**Comment by EoinKenny** [comment]
@marcotcr you were exactly right, it works perfect now.

Thanks a lot for taking the time to explain.
