### ISSUE TITLE
How to output the specific domain of the LimeTabularExplainer?

### ISSUE THREAD

**Issue by Larryliu912** [marcotcr/lime#212]
I want to use the LIME to put some interpretation of my medical prediction model. I see the domain function is really powerful, it can generate some domain for the HDL like if HDL < 90, it is positive if it is in 90<HDL < 106, it is negative with weight 1.9 if it is > 106 the weight is 2.9. 

But I get this domain by trying lots of explain_instance, is there a func to output the all the domain with weights by ID?

**Comment by marcotcr** [comment]
Sorry, we don't have a function like that. #206 is something that should help you when it lands
