### ISSUE TITLE
How to export the lime explanation output to a dataframe

### ISSUE THREAD

**Issue by ba4ekiko1** [marcotcr/lime#213]
Hello, awesome package!
Is there a function that outputs the explanation for each predicted row into a dataframe/list format? I am trying to use a for loop to append the explanations to a list and then transform them to a dataframe and concat with the predictions but it is taking a long time for about 4000 predictions

**Comment by ba4ekiko1** [comment]
Hello, awesome package!
Is there a function that outputs the explanation for each predicted row into a dataframe/list format? I am trying to use a for loop to append the explanations to a list and then transform them to a dataframe and concat with the predictions but it is taking a long time for about 4000 predictions

```
import lime
import lime.lime_tabular
explainer = lime.lime_tabular.LimeTabularExplainer(X_train.values, feature_names=X_train.columns, discretize_continuous=True)

l=[]
for n in range(0,X_test.shape[0]+1):
exp = explainer.explain_instance(X_test.values[n], clf.predict_proba, num_features=10)
a=exp.as_list()
l.append(a)

```
Thanks in advance!

**Comment by marcotcr** [comment]
We don't have that function, sorry. #206 will have that when it lands, but it won't be any faster then what you are doing, unless you choose to subsample. If you want faster (but less precise) explanations you can try decreasing the number of samples in explain_instance.

**Comment by ba4ekiko1** [comment]
Thanks Marco, yes the workaround for me to is to decrease the num features and in my case to explain only the predicted samples which are classified as 1 in my model.

**Comment by marcotcr** [comment]
Decreasing the number of features shouldn't make it much faster (unless you're using lasso_path or forward_selection), `num_samples` is what really matters. The default is 5000, which is probably way more than you need.

**Comment by ba4ekiko1** [comment]
So if i say have 500 predicted samples as 1 and if i change the num_samples to 500 this would make a difference?

**Comment by marcotcr** [comment]
Yes

**Comment by MohGhaziAlZeyadi** [comment]
Hi all, 
Please, I am just wondering if it is possible to save an explainer in Lime as .json ?
My explainer as fallowing 
explainer = lime.lime_tabular.LimeTabularExplainer(X_train, mode='classification', class_names = ListOftargets, feature_names= listOfFeature, )

**Comment by ajeevanshgtm7** [comment]
Is there a way to further optimize the time that the library consumers to create the following list:

```
l=[]
for n in range(0,X_test.shape[0]+1):
     exp = explainer.explain_instance(X_test.values[n], clf.predict_proba, num_features=10)
     a=exp.as_list()
     l.append(a)
```
I've tried reducing the num_samples but there hasn't been a significant improvement.

**Comment by tlyddiard** [comment]
Why is it difficult to convert the output from the for loop into a DataFrame? The output for the following code produces a DataFrame with only two columns.
l=[ ]
for n in range(0,X_test.shape[0]+1):
     exp = explainer.explain_instance(X_test.values[n], clf.predict_proba, num_features=10)
     a=exp.as_list()
     l.append(a)
df = pd.DataFrame(l)
df

Whereas, I have no problem with generating a DataFrame when it is not in a for loop. It easily generates a table.
exp = explainer.explain_instance(np.array(X_test)[i], clf.predict_proba, num_features=7)
df= pd.DataFrame(exp.as_list(label=1), columns=['Feature', 'Value'])
df

How do you recommend converting the output from the for loop into a dataframe?

**Comment by dharathakkar5** [comment]
@MartinPetrov8 Is there a way to vectorize it and not loop through every data point in the test set?
