### ISSUE TITLE
How to customer the super-pixel window size?

### ISSUE THREAD

**Issue by lesley9309** [marcotcr/lime#214]
Hello!

I recently use lime in the image classification project. I have test the tutorial examples in the ImageNet images, it works perfectly! Thank you so much.
I would like to implement into my own project. However, unlike the images of ImageNet, the images in my database is small: 20x20 pixels. When I use Lime, it shows the whole region of the image to represent the support region for the prediction. I though this is caused by the size of super-pixel. How can I change the size of searching the super-pixel? Otherwise, it there any other problem cause this results?
Thank you so much! And expect for your response.

**Comment by marcotcr** [comment]
Yes, that sounds like segmentation is the issue.
Take a look at [this](https://github.com/marcotcr/lime/blob/master/lime/lime_image.py#L149) and [this](https://github.com/marcotcr/lime/blob/master/lime/wrappers/scikit_image.py#L90).
