### ISSUE TITLE
Siamese Network Instance Explanation?

### ISSUE THREAD

**Issue by christianayala10** [marcotcr/lime#216]
Is it possible to explain an instance from a Siamese Neural Network?

**Comment by marcotcr** [comment]
I'm not familiar with Siamese NNs, but if you can wrap the output function so that it returns a prediction probability, LIME does not care what the underlying function is.

**Comment by christianayala10** [comment]
I mean, Siameses NNs needs two inputs, for example two images. Can LIME handle multiple inputs?

**Comment by marcotcr** [comment]
Ah, sorry. No, currently we do not allow multiple inputs by default. One way to hack it is to concatenate both inputs into one for LIME, while separating them in the predict_fn, while maybe use a custom segmentation_fn that does not allow segments to span both images.

**Comment by Rabia3** [comment]
Does now LIME offer any explanation method for Siamese Neural Network? Does Concatenation of both inputs work for anyone?
