### ISSUE TITLE
Training set too large to fit into RAM

### ISSUE THREAD

**Issue by dmesquita** [marcotcr/lime#219]
Hey everyone, so this is our scenario: I have a large training set that cannot be fit in RAM. I'm using scikit-learn and an estimator that implements the `partial_fit ` call to train our model.

We want to show LIME explanations along with the prediction results of our product. 

What do you think would be the best way to work around the large training set issue? 
Should we find a strategical way to reduce the training set before passing it to `LimeTabularExplainer` or it's better to implement a `partial_fit` method in the library?

Thanks!

**Comment by marcotcr** [comment]
The only reason we need the training set is to estimate frequencies for categorical features or mean / variance for continuous features. You should be fine if you just subsample the training set, but make sure every possible value for categorical features shows up in your subsample.
