### ISSUE TITLE
LightGBM Support?

### ISSUE THREAD

**Issue by BrianMiner** [marcotcr/lime#220]
I am using LIME with a lightgbm model. Is there an issue with using this since it only returns P(y=1) for a binary problem?

```
X_test=X_test.fillna(0)
explainer = lime.lime_tabular.LimeTabularExplainer(X_test[limit_vars].values, discretize_continuous=True, random_state=1231)

exp_idx = 0
exp = explainer.explain_instance(X_test[limit_vars].iloc[exp_idx,:].values, 
                                 lgbm_mod.predict, num_features=10)

```
Gives:
NotImplementedError: LIME does not currently support classifier models without probability scores. If this conflicts with your use case, please let us know: https://github.com/datascienceinc/lime/issues/16

**Comment by marcotcr** [comment]
I'm assuming it returns a 1d array. If so, you just have to wrap it like this:
``` 
def wrapped_fn(X):
  p = lgbm_model.predict(x).reshape(-1, 1)
  return np.hstack((1-p, p))
```
and use  `wrapped_fn` in `explain_instance`

**Comment by wyue92** [comment]
I am using LIME with a lightgbm model. Is there an issue with using this since it is multi-class ？

**Comment by sdubi2019** [comment]
@marcotcr , thank you for your code. It helps to fix an issue.
