### ISSUE TITLE
Guidance on Kernel Width

### ISSUE THREAD

**Issue by BrianMiner** [marcotcr/lime#222]
I am running explanations on a subset of a test set from a model (light gbm). I am trying to determine how to consider the best choice of kernel width. From here there are a couple questions:

1) In the R package they report R-squared for each explanation. I assume this means in terms of predictions and "actuals" from the perturbed data.....Is there a way to get that from python?
2) What is the meaningful measure - the r-squared on a given explanation or over the entire set (test set in my example) where you compare local predictions versus original model predictions?
3) I am finding the default kernel width gives horrible r-squared. If I reduce to kernel_width =5, r-squared is 0.18. If I reduce to 2, it goes to 0.99. What is the trade-off here to consider (is highest r-squared always preferred)?

I am seeing very different explanations depending on if kernel_width is 5, 2.5, 1 and if continuous features are binned or not. Even in cases where overall r-squared is high (say kernel_width = 2.5 or 1). The different explanations are that the list of top variables change and the directions (pos or neg) of the same variables.

Example of how I am calculating the overall r-squared:
```
better_explainer = lime.lime_tabular.LimeTabularExplainer(X_test[limit_vars].iloc[0:1500,:].values,feature_names=X_test[limit_vars].columns, 
                                                          kernel_width=5,  class_names=['Not Gold', 'Gold'],discretize_continuous=False, random_state=1231)
lime_expl = X_test[limit_vars].iloc[0:1500,:].apply(better_explainer.explain_instance, 
                                predict_fn=wrapped_fn, 
                                num_features=10,                                
                                axis=1)
lime_pred = lime_expl.apply(lambda x: x.local_pred[0])
y_pred=lgbm_mod.predict(X_test[limit_vars].iloc[0:1500,:])
r2_score(y_pred, lime_pred)
```

**Comment by marcotcr** [comment]
1. Yes, `explanation.score` gives you the r-squared score for the explanation on the perturbed data. Please note that this is weighted r-squared, so it depends on your kernel width

2. Depends on what you want to know. If you want to check how good an explanation is as a global approximation of the model, you can look at its r-squared on the whole test set. However, we don't expect that to be good for complex models. In general, I think r-squared on the region of the prediction makes more sense. That is **not** what you are doing though: you are taking the r-squared of the local prediction of each explanation, which does not really mean much (see point below).

3. Highest r-squared should not be preferred always. Consider that an explanation that just says 'intercept = prediction' has perfect r-squared, even though it does not explain anything. That is actually close to what you get if you set kernel_width to a very small value, as that means 'I only care about predicting this data point correctly'. This explains why you would get direction changes for the same variables, they probably have low enough weight that it is all noise (all of the weight is probably in the intercept with low kernel).

What you want is to find a kernel width for which the distances make sense, i.e. the weighting of 'close instances' is close to your perception of what a nearby instance is. This way you can reason about what the explanation is saying: if you have a good explanation.score, the linear model represented by the explanation is a good approximation of the black box model in this region.
