### ISSUE TITLE
LimeTabularExplainer - input features

### ISSUE THREAD

**Issue by ybwlrs** [marcotcr/lime#230]
Marco, i believe a related question to this thread.
In TensorFlow some of the features are constructed and only generated in runtime (Bucketing certain variable, crossing, one hot encoding etc). That means that in the "train" numpy array that is passed to the tabular explainer they do not exist. Do I need to recreate them and add them to that array?
Also does the "train" numpy array has to contain only the features used?

Unrelated, i get "TypeError: can't multiply sequence by non-int of type 'float'" from the discretize.py .. any quick idea why?

Thanks

**Comment by marcotcr** [comment]
Argh, I guess I never considered this case. Yes, I guess you would need to create the training data, we need the statistics to perturb new data. Note that we only use the mean and variance for numerical features, and the count frequencies for categorical features, so you could create a very small version of the dataset with the right statistics.

And sorry, no quick idea of why you're getting this error. I would make sure if you're passing as parameter a numpy array.

**Comment by rhamnett** [comment]
If you found a solution to this can you please post it? Thanks in advance

**Comment by marcotcr** [comment]
We now have an option for this in `LimeTabularExplainer` called `training_data_stats`, see [this](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L158).

**Comment by ybwlrs** [comment]
Thx. I'll give it a try.
