### ISSUE TITLE
Non-deterministic output even setting random_state

### ISSUE THREAD

**Issue by irenerodriguez** [marcotcr/lime#231]
Hello,

First of all, thanks for your amazing work on Lime!

I was surprised that after getting the constructor for LimeTabularExplainer (Lime 0.1.1.32) and setting the random_state parameter, I still got different results when explaining the same instance (explain_instance) using the same LimeTabularExplainer object.

I dived into the code, and I realized that the "problem" was that the random seed is not restarted when generating neighborhood samples (__data_inverse in lime_tabular.py) and the discretizer (get_inverse in discretize.py). Resetting the seed in these parts of the code worked for me, but I fear that this issue may affect to other classes different from LimeTabularExplainer.

Best.

**Comment by marcotcr** [comment]
This is expected, see #67, #119, #199.
Thanks : )
