### ISSUE TITLE
submodular_pick : recover chosen indices

### ISSUE THREAD

**Issue by paulaceccon** [marcotcr/lime#232]
Is it possible to recover the data chosen to be explained using submodular_pick? I would like to be able to compare the ground truth with the predict target.

Thank you.

**Comment by dyanni3** [comment]
You can get the indices that submodular_pick chose. For example, in the snippet below

```
from lime import submodular_pick
sp_obj = submodular_pick.SubmodularPick(explainer, train, rf.predict, sample_size=20, num_features=14,num_exps_desired=5)
sp_obj.V
```

the "V" will be a list of indices into the training set used to make the explainer object.

**Comment by paulaceccon** [comment]
Perfec, @dyanni3. Could you close this issue, please?

**Comment by paulaceccon** [comment]
Weird:

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-52-bae6524bfb3e> in <module>()
> ----> 1 sp_obj.V
> 
> AttributeError: 'SubmodularPick' object has no attribute 'V'

**Comment by dyanni3** [comment]
Hmm, I'm not getting that error. Did you try updating LIME?

If the problem persists, would you post a code snippet so I can try to replicate the error. Thanks!
