### ISSUE TITLE
Multiple text explanations

### ISSUE THREAD

**Issue by johnnykost** [marcotcr/lime#233]
Is there a way to return explanations if we have two or more seperate text features? For example, if we have one for title and one for main body as seperate features and we want to use their embeddings for text classification.
I would like also to ask you if we can use text feature together with tabular data for explanations.

**Comment by shafaypro** [comment]
There is a way of developing your own dictionary I believe, but that would be done in the Vectorization or Frequency inversion and then use that grammar(self-dictionary) like this 👍 
Sentence Feature 1 ---> Output
Sentence Feature 2 ---> Output
Sentence Feature 1 + Sentence Feature 2 ---> Output

This can generally be used to get the idea of different features counted as one, The textual Feature is always counted as one, but the Grammer(dictionary created for its vectorization can be very common to use)

**Comment by marcotcr** [comment]
Sorry for the delay in responding.
> Is there a way to return explanations if we have two or more seperate text features? For example, if we have one for title and one for main body as seperate features and we want to use their embeddings for text classification.

We don't have this feature, but you can achieve it by prefixing or postfixing each word by its source and appending it all into a single string. For example, you would have the document:
TITLEthis TITLEis TITLEa TITLEtitle BODYthis BODYis BODYa BODYbody.
Then you can write a wrapper for your predict function that strips these prefixes, something like
```
def wrap_predict_proba_fn(prefixed_strings):
  titles = [re.findall(r'TITLE(.*?)\b', t) for t in prefixed_strings] 
  bodies =  [re.findall(r'BODY(.*?)\b', t) for t in prefixed_strings]
  return predict_proba_fn(titles, bodies) 
```

> I would like also to ask you if we can use text feature together with tabular data for explanations.

Unfortunately not. It is tricky to know how to perturb text and tabular simultaneously.
