### ISSUE TITLE
Invalid html produced for 2 labels in classification

### ISSUE THREAD

**Issue by Lesterpig** [marcotcr/lime#239]
There is a label inversion in the HTML produced by LIME when the following conditions are met:

* classification mode
* only 2 labels
* winning label is the first one

See https://github.com/marcotcr/lime/blob/master/lime/js/explanation.js#L23. If we modify it slightly to introduce some debug information:

```javascript
let names = [`NOT ${this.names[label]}`, this.names[label]];
console.log("Names are in the general case:", names);
if (this.names.length == 2) {
  colors=[this.colors_i(0), this.colors_i(1)];
  names = this.names;
  console.log("Names are in this specific case:", names);
}
```

We get this output (with labels `label1` and `label2` for instance):

```
Names are in the general case: (2) ["NOT label1", "label1"]
Names are in this specific case: (2) ["label1", "label2"]
```

There is a clear mismatch in the transformation, leading to inverted results.
I'm working on a patch proposal.

**Comment by marcotcr** [comment]
Sorry for the long delay in responding. Let me just make sure this is wrong before I merge the pull request, because I think the behavior is as expected.
When we have two labels, we don't want each explanation to change what the right side is based on the predicted class (because that is confusing), so even if the prediction is the first one we want it to be on the left. 
I think the results are still correct, see for example line 13 [here](https://marcotcr.github.io/lime/tutorials/Lime%20-%20basic%20usage%2C%20two%20class%20case.html), where we have the 3 conditions you listed.

**Comment by Lesterpig** [comment]
Thanks for your comment :smiley: 
Indeed, your example seems to work well. It seems that the issue comes from the "Tabular" case.
Here is a little toy test with a basic classifier.

```python3
import numpy as np
import lime
from lime.lime_tabular import LimeTabularExplainer

data = np.array([
    [12],
    [16],
])

features = ["temp"]
classes = ["cold", "hot"]


def toy_predictor(vectors):
    """
    This trivial predictor returns "cold" when temperature is less than 15 degrees.
    Otherwise, it returns "hot".
    """
    output = np.zeros((len(vectors), len(classes)))
    for i, v in enumerate(vectors):
        [temp] = v
        if temp > 15:
            output[i][1] = 1
        else:
            output[i][0] = 1
    return output


explainer = LimeTabularExplainer(data, feature_names=features, class_names=classes)
for d in data:
    exp = explainer.explain_instance(d, toy_predictor, num_features=1)
    exp.show_in_notebook()
```

![capture d ecran de 2018-11-21 11-08-58](https://user-images.githubusercontent.com/5081760/48834350-e3012c80-ed7d-11e8-9e7c-14c67d60d64b.png)

The first "cold" case seems very wrong to me (as displayed), but maybe I'm not using lime properly?

---
The issue might comes from deeper levels in the labels orders, but here is the updated version that my PR proposes (it does not modify the output produced for the TextExplainer from what I can tell)

![capture d ecran de 2018-11-21 11-14-25](https://user-images.githubusercontent.com/5081760/48834669-a255e300-ed7e-11e8-808a-f5386d836c17.png)

**Comment by Lesterpig** [comment]
Ok, it seems that the version I first downloaded had an issue...
It was 0.1.1.32, downloaded on october 4th with `pip3`.
I just cleared my workspace and retried from latest pip version (again, 0.1.1.32 but with a different hash?!)
This time (as you said) it works! :thinking:

So, this issue might be solved! Sorry for the trouble.
Please close this issue and the PR as you wish  :smiley:

**Comment by marcotcr** [comment]
Sorry you had the trouble to do this, but thanks for trying to help! I appreciate it!
