### ISSUE TITLE
Fesability of using LimeTabularExplainer with training data statistics instead of data 

### ISSUE THREAD

**Issue by sokollip** [marcotcr/lime#241]
Hi , 

Is it possible to make  LimeTabularExplainer - to accept training statistics (Like mean  , median , std , labels etc ... ) instead of training data as it is expecting today . In case we are not supplied with training data but the above statistics alone - is it a feasible to make LimeTabularExplainer work with the same. Requesting comments . 

Thanks ,
Sowmya

**Comment by marcotcr** [comment]
Sure, that's an easy pull request : )
In the meantime, a hacky way to do it is to just create a dummy dataset with the right statistics and use it as parameter.

**Comment by sokollip** [comment]
Hi Marc , thanks for the quick response :) glad to hear that it is a easy pull request.  It would be great if we can have this provision .  As far as the statistics are concerned -  the following details will be available:

a) For numeric columns - mean , standard deviation , median , max , min values of the column 
b)  For categorical columns - categorical_data counts for each column

Couple of queries:
1.  Are the above set of stats sufficient ?
2. While generating the statistics do we need to consider "discretize_continuos" significance ?
3.  If I want to create a dummy dataset using stats(to try the tacky way)- do we need to consider anything specially for "discretization"

Requesting comments.

**Comment by venkataramanam** [comment]
@marcotcr If you can manage to push a change to accept stats, we will be more than glad :-)

**Comment by marcotcr** [comment]
> a) For numeric columns - mean , standard deviation , median , max , min values of the column
b) For categorical columns - categorical_data counts for each column
Are the above set of stats sufficient ?

We only use the mean and variance for numerical features, and the count frequencies for categorical features.

> While generating the statistics do we need to consider "discretize_continuos" significance ?
If I want to create a dummy dataset using stats(to try the tacky way)- do we need to consider anything specially for "discretization"


Yes, if you are discretizing continuous variables it becomes a little trickier, as you need to make sure you get the same discretization and the same frequency within each bin. This depends on which discretizer you use (quartile, decile, etc).

> Could you please throw some light on what parts of the code need to be touched and what changes are expected to be done? That would really help us go forward attempting a PR to accept stats for LIME tabular explainer

Around [here](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L213). If I need to detail exactly what needs to be done, it's easier if I do it myself. I won't do it myself anytime soon though.
