### ISSUE TITLE
Changing default distance metric in LimeTabularExplainer

### ISSUE THREAD

**Issue by omerza** [marcotcr/lime#245]
Hi,
First, LIME is awesome and I find it very useful for model debugging.
I would like to suggest using a different distance metric as default, instead of euclidean.
Euclidean distance works well with the iris dataset and other very low dimensional datasets.
I believe that in most of the actual use cases of LIME there will be usage of high dimensional data, as it is harder to interpret.
Also, the perturbations used for the distance metric are binary vectors, where jaccard or hamming distance work better.
I am constantly getting much better results after switching the distance metric, and for new users the default metric might get confusing results, and prevent them from experiencing the true power of LIME.

Thanks :)

**Comment by marcotcr** [comment]
Thanks for the advice. Do you have a few examples where euclidean is producing bad results, and jaccard / hamming is better? The reason we used euclidean was that at first I envisioned people would mostly use a mix of continuous and categorical features, but the default behavior is now to discretize and thus hamming / jaccard may be preferred as you are indicating.

**Comment by wabc1994** [comment]
Hi, marcotcr ! what discretize alogrithms you have use  for tabular dataset contain both discretize and continuous feature ?

**Comment by marcotcr** [comment]
see [this](https://github.com/marcotcr/lime/blob/0cd9a80373b551d503603d9e57cc2037db95d25c/lime/discretize.py#L175)

**Comment by expectopatronum** [comment]
Hi @omerza,
I know this is a very old issue - but I was wondering what you mean you get "much better results"? How do you determine that one explanation is better than the other?

Best regards
Verena
