### ISSUE TITLE
Model evaluation

### ISSUE THREAD

**Issue by matichorvat** [marcotcr/lime#25]
Hi, I love the LIME library so far, I have tried it out with some SVM models and planning to try it on neural networks next. In your paper you also talk about explaining models, not just individual predictions, by showing representative examples. Are you planning to add this feature to the library in the near feature?

**Comment by marcotcr** [comment]
Yeah, this is something I thought I was going to add a few weeks back. I already have code for it, it's just a matter of cleaning it up and plugging it with the library. I won't promise any specific date, but it is something I hope to have in the near future.

**Comment by TKlerx** [comment]
Hi,
thanks for the very nice library. 
I guess you are quite busy, but is there any update on the model explanation? Or can I help somehow, e.g. by testing or trying to clean up?

**Comment by marcotcr** [comment]
I have code for it for both text and tabular data, but no time to clean it up at the moment, unfortunately.

**Comment by ccmien** [comment]
Hi~ any progress? Need any helper?

**Comment by AlJohri** [comment]
I think this is related to #11. Also happy to lend a hand if needed.

**Comment by marcotcr** [comment]
closed by #206
