### ISSUE TITLE
Feature importance for the entire class or subgroup

### ISSUE THREAD

**Issue by Romits** [marcotcr/lime#254]
Using Lime, generate a model for the class or subgroup approximating the  DNN and get feature importance. It will help in validating the overall model before production deployment as well as focussing efforts during data collection specially for IOT use cases.

**Comment by marcotcr** [comment]
I'm sorry, I don't really understand what this issue is about. Please clarify and I will reopen it.

**Comment by Romits** [comment]
In case of multi-class classification using a DNN, some times the prediction for some classes have lower accuracy in comparison to others. Using this approach, the DNN can be represented by a simpler model for the specific class and hence feature importance can be generated at the class level which will help is resolving the issue.

**Comment by marcotcr** [comment]
That seems to be out of the scope of this repository (LIME). I know we had other things in the description, but I ended up just creating new projects for other interpretability ideas (e.g. [anchor](http://github.com/marcotcr/anchor))

**Comment by Romits** [comment]
Ok. Thanks for your response. I will reopen this issue in anchor.

**Comment by marcotcr** [comment]
This would be out of scope for anchor as well, I just used anchor as an example of another interpretability project that I didn't include in this repository.
