### ISSUE TITLE
Issue with running time

### ISSUE THREAD

**Issue by platinum736** [marcotcr/lime#255]
Hi, I am running LIME on my model having 1800 features with 1400+ BoW features and rest numeric features.

I see explainer working fine and running fine but the explain instance method is taking time in minutes to give result for single instance.

Let me know is it expected behaviour or am I doing something wrong.

**Comment by marcotcr** [comment]
By default, each explanation produces 5000 perturbed samples (you control this through the `num_samples` parameter). The explanation time is typically dominated by the time it takes your model to predict on those perturbed samples. If you want to speed things up, you can reduce the number of samples.

**Comment by platinum736** [comment]
Thanks @marcotcr num_samples helped in getting faster results
