### ISSUE TITLE
RecurrentTabularExplainer for Regression

### ISSUE THREAD

**Issue by DaniSalva** [marcotcr/lime#256]
Hello,

I'm trying to use LIME for explaining predictions of a **LSTM regression model** which has 2 features and 33 timestamps.

I saw in the documentation that there is a method "RecurrentTabularExplainer" designed to work with multidimensional input shapes (n_samples, n_timesteps, n_features) but there isn't a parameter to indicate "regression mode" as the one available in the normal "LimeTabularExplainer".

Is it not supported? Any other idea

Thank you in advance :)

**Comment by marcotcr** [comment]
Made a minor change to master, should work after 1e12bcdc4c021a1c87e1886379ab4e354c154a47.
Let me know if you have any issues.

**Comment by blaklodge** [comment]
Hello,
I am running into a similar issue, trying to Keras LSTMs with lime.lime_tabular.RecurrentTabularExplainer.
I get the following error:

_ValueError: Your model needs to output single-dimensional numpyarrays, not arrays of (5000, 12, 3) dimensions_

The Keras model is a sequence to sequence model, with output layer having a sequence of three values (Dense(3)).  
Here are the data shapes (batch, time_seq_step, features):

Train X = (4, 12, 228)
Train Y = (4, 12, 3)
Test X = (1, 12, 228)
Test Y = (1, 12, 3)

Does anyone know if the Lime Explainer support this type of Keras model.  I also tried using one output cell ((Dense(1)), Lime also gives a similar error.  

Thanks for your help.

**Comment by AdityaShaha** [comment]
@blaklodge I was facing the same problem. So apparently you model is returning a a one dimensional np array. So in place of a `classifier_fn` in the explainer, you can create a regressor function and return the predictions as flatten.

Example
```
def regressor_pred(input_data):
    pred = model.predict(input_data)
    return pred.flatten()

exp = explainer.explain_instance(x_test[0],regressor_pred,num_features=4
                                 ,labels=screend_dataset.drop('Predictor',axis=1).columns)
``` 
The above method worked for me.
