### ISSUE TITLE
'save_to_file' not working out-of-the-box for windows [tested on notebook example]

### ISSUE THREAD

**Issue by magnusax** [marcotcr/lime#26]
Hi,
first of all, very interesting package and project. I am planning on using it in the future.

My apologies if this is a spurious issue, but at least for myself working on a windows 7 machine using python (3.4.x) the notebook example on binary text classification throws an exception for when trying to save an explanation as a html document. If it helps, the version of lime I'm using is 0.1.1.16.

To be clear, the exceptions I'm getting are typically: "UnicodeEncodeError: 'charmap' codec can't encode character 'XXX' in position 0123456: character maps to <undefined>".

For myself, a workaround has been to edit the call from:

`file_path = "..." # assume set to something meaningful`
`explanation_to_save = exp.as_html()`
`file_ = open(file_path, 'w')`
`file_.write(explanation_to_save)`
`file_.close()`

to:

`file_path = "..."`
`explanation_to_save = exp.as_html().encode('utf-8')`
`file_ = open(file_path, 'wb')`
`file_.write(explanation_to_save)`
`file_.close()`

i.e. use a binary write instead. This works for myself, but I have no clue how this would generalize for others on other systems and versions etc.

I hope this post is somewhat useful, at least. To be explicit, the notebook I was working on:
https://github.com/marcotcr/lime/blob/master/doc/notebooks/Lime%20-%20basic%20usage%2C%20two%20class%20case.ipynb. I did download it and then ran the code on my own system.

Regards,
Magnus

**Comment by marcotcr** [comment]
Thanks! I know what the problem is, we've had it before on Windows - I just didn't fix the save_to_file. The fix is to have:
file_ = open(file_path, 'w', encoding='utf8')
I've added this to master, will be fixed in the next release (which should come out somewhat soon).

**Comment by magnusax** [comment]
I see, thanks for the clarification. 

Looking forward to see the next version!

/M
