### ISSUE TITLE
as_map() still has classes for regression?

### ISSUE THREAD

**Issue by mgb1028** [marcotcr/lime#262]
Hi,
I running the LimeTabularExplainer in regression mode and looking and trying to extract the coefficients using as_map but this returns a dictionary with keys as 0,1 and key values of feature ids and their coefficients. The weights for one key are the negatives of the weights in the other key. I suppose I could use as_list() to get these but I wanted to clarify this as well. My version is 0.1.1.32

**Comment by marcotcr** [comment]
`as_map[1]` are the coefficients you want. I don't remember why we also had `as_map[0]` as the negative of label '`1', it probably had something to do with visualization code.
