### ISSUE TITLE
Support for Sequence Models

### ISSUE THREAD

**Issue by rhlewd** [marcotcr/lime#263]
Hello,
I have been working on sequence models for classifying multivariate(for e.g. 5 variables) time series data into 2 classes. 
I want to use LIME to explain the contribution of a particular variable to a predicted score. Is this possible with LIME? 
I saw lot of examples on internet but none of them seem to address this particular model type, hence posting it here.

**Comment by marcotcr** [comment]
You can flatten the time series and use `LimeTabularExplainer`. Take a look at [this](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L446) wrapper for an example.
