### ISSUE TITLE
Structure of code regarding inverting and how it's done

### ISSUE THREAD

**Issue by Pavan-Sangha** [marcotcr/lime#264]
In the original paper

https://arxiv.org/pdf/1602.04938.pdf in section 3.3 sampling for local exploration it mentions perturbing a value in the interpretable space and then recovering the corresponding data point in the original space. However if as is typically expected the interpretable space is of lower dimension than the original space there is no direct map to this space to recover a unique entry. So my question is how is this taken care of in the codebase?  For my case i'm using tabular data

Taking a simple example to help 

if my original features are 

o1,o2,o3,o4,o5,o6,o7 and predictor p 

suppose i have completely separate interpretable features so we move from 7 dimensional space to 3 dimensional space.

i1,i2,i3 

Does the code allow for me to have completely separate interpretable features? 
Now suppose i perturb this interpretable space, how do i recover samples in the original space when the first model is build on 7 features and the second model on 3, would be have to randomly assign values in the original space? What methods in the code facilitate this? I know there is a __data_inverse method

 is this meant to take a row in the interpretable space and create perturbations? How do i recover values for o1,o2,...,o7? 

More specifically, I see the method in the class is explain_instance and it makes use of the __data_inverse method. In particular i was wanting to know is 

1. whether the interpretable feature space for the limetabular explainer is meant to be the same as the model feature space. The reason i ask is because we feed in a parameter predict_fn into the explainer which i presume is the model i learned in the original feature space. 
2. The __data_inverse method simply allows me undiscretise any features that i discretised. Does it do any more than that?

**Comment by marcotcr** [comment]
Good question. Unfortunately, we do not have any provisions for what you are describing in our code, we assume that for tabular data the model is either going to be using an interpretable representation or a representation that is a function of the interpretable representation (e.g. one-hot encoding).

To achieve what you want, you would have to write a new version of ``__data_inverse``. 
Sorry!
