### ISSUE TITLE
Multiclass classification: No explanations given

### ISSUE THREAD

**Issue by kommerzienrat** [marcotcr/lime#267]
Hello!

This issue is about multiclass classification with independent classes. Does Lime support such cases?

In my use case:
I have an annotated text dataset and a CNN Keras multiclass classifier.
The texts are customer reviews that received labels such as "kindness", "expertise" etc. 
The thing is, the predicted probabilities of the classes do not sum up to one because it was possible to assign zero, one or more classes to every review. That is, having "kindness" does not prevent the text from receiving the label for "expertise" etc. As the TextExplainer seems to be not suitable, I use `LimeTabularExplainer`. (Keras receives arrays with numerical representations for every letter, so I use the TabularExplainer.)

However, I get the following warnings:

```
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.6/dist-packages/lime/lime_tabular.py:296: UserWarning: 
                    Prediction probabilties do not sum to 1, and
                    thus does not constitute a probability space.
                    Check that you classifier outputs probabilities
                    (Not log probabilities, or actual class predictions).
```

Then, when using the following, there are no values for the labels (e.g. kindness), while on the "NOT-side", there is a bunch of zeros given. 
`exp.show_in_notebook(show_table=True, show_all=True)`

The "FeatureValue" list does show some numbers. But for what? Can I make use of them?
Does Lime support such a multi-class case?

**Comment by marcotcr** [comment]
> As the TextExplainer seems to be not suitable, I use LimeTabularExplainer. (Keras receives arrays with numerical representations for every letter, so I use the TabularExplainer.)

Unless you want the explanations to be in this numerical representation (which I doubt), you should use the TextExplainer. All you have to do is write a wrapper for the predict function, like:

```
def wrapped_predict(strings):
    cnn_rep = strings_to_numerical(strings)
    return cnn.predict_proba(cnn_rep)
```
And this function is what you should use with LIME.
To your second question, LIME assumes that increasing the prediction probability to one class decreases the probability for another class. However, you can still explain each class individually. To do this, you want to wrap the prediction function again, to something like:
```
def get_predict_proba_fn_of_class(label):
  """assuming wrapped_predict outputs an (n, d) array of prediction probabilities, where d is the number of labels"""
  def rewrapped_predict(strings):
      preds = wrapped_predict(strings)[:, label].reshape(-1, 1)
      return np.hstack((1 - preds), preds)
  return rewrapped_predict 
```
Let's say that you want to explain each label where you get a prediction probability great than 0.5. You would do something like:
```
preds = cnn.predict_proba(string_to_numerical(text))
labels_to_explain = (preds > .5).nonzero()[0]
explanation_for_label = {}
for label in labels_to_explain:
  wrapped = get_predict_proba_fn_of_class(label)
  explanation_for_label[label] = explainer.explain_instance(text, wrapped, ...)
```
