### ISSUE TITLE
Using LIME for unsupervised algorithms

### ISSUE THREAD

**Issue by rahuldatsme** [marcotcr/lime#269]
How can LIME be used for unsupervised algorithms , say K-Means clustering?

**Comment by marcotcr** [comment]
If you can define a predict_fn that gives you a probability of something (e.g. probability of instance being within a cluster), LIME doesn't care how you got that predict_fn.

**Comment by rahuldatsme** [comment]
Thanks for replying so soon.

Sorry to be asking maybe a trivial question, but I have defined a prediction function in my code which returns an array of showing predictions for any features array. But when i use this function in lime.explainer , then i get this error message "'Typeerror: 'list' object is not callable"

**Comment by marcotcr** [comment]
Assuming you are using LimeTabularExplainer, you need to make sure that your input is a 1d numpy array, and that your prediction function takes as input a 2d numpy array (n, d) where d is the number of features and returns a 2d numpy array of probabilities (n, p), where p is the number of classes.
If both of these are true, I need more information on this error to diagnose it.

**Comment by rahuldatsme** [comment]
Here is the my code for LIME:
explainer = lime.lime_tabular.LimeTabularExplainer(X_train, feature_names=iris.feature_names, class_names=iris.target_names, discretize_continuous=True)

# below line throws the error
exp = explainer.explain_instance(X_train[1], (predict_fn1(X_train)), num_features=2, top_labels=1)


and here is the function I have defined:

dstprob = []
# defining a function taking 2-d array as input
def predict_fn1(set):
	
	for i in range(len(set)):
		a = distance.euclidean(set[i],centroids[0])
		b = distance.euclidean(set[i],centroids[1])
		c = distance.euclidean(set[i],centroids[2])
		
	
		
# some mathematical formula to calculate the probabilities
				p1 = 1/(a/(a+b+c)); p2 = 1/(b/(a+b+c)) ; p3 = 1/(c/(a+b+c)) ; 
		prob1 = p1/(p1 + p2 + p3) ; prob2 = p2/(p1 + p2 + p3) ; prob3 = p3/(p1 + p2 + p3) ; 

#  ---appending these values to 2-d array
		dstprob.append((prob1 , prob2 , prob3 ))

# returning the array		
	return dstprob

**Comment by ibsherzod** [comment]
Hi @marcotcr ,
I am new to LIME and I have gone several forums to find why I am still getting error: **TypeError: 'numpy.ndarray' object is not callable** . Everythings goes well until I try to run **explain_instance**

Here is some portion of my code: 

dt_classifier= DecisionTreeClassifier()
dt_classifier= dt_classifier.fit(X_train,y_train)
y_pred = dt_classifier.predict(X_test)

y_pred_prob = dt_classifier.predict_proba(X_test)
Out: array([[0.94117647, 0.05882353],
       [0.        , 1.        ],
       [0.        , 1.        ],
       ...,
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.        , 1.        ]])

Then I converted dataframe to array: 
X_train_array = X_train.as_matrix() 
Out: 
array([[   2.  ,   25.  , 1184.  ],
       [   3.83,   52.  ,  342.  ],
       [   4.  ,   42.  ,  156.  ],
       ...,
       [   2.3 ,   39.  ,  282.  ],
       [   3.  ,   25.  ,  715.  ],
       [   3.  ,   26.  ,   70.  ]])

X_test_array = X_test.as_matrix()
Out:
array([[  3.4 ,  43.  , 636.  ],
       [  3.4 ,  35.  ,  11.  ],
       [  2.76,  30.  ,  67.  ],
       ...,
       [  3.06,  49.  ,  58.  ],
       [  2.29,  19.  , 151.  ],
       [  3.5 ,  32.  ,  51.  ]])

explainer = lime.lime_tabular.LimeTabularExplainer(X_train_array, class_names=['0', '1'], feature_names = feature_cols, mode='classification',discretize_continuous=True)

explainer_dt = explainer.explain_instance(X_test_array[0], y_pred_prob)

What I am doing wrong here? I really appreciate your feedback. Thank you so much.

**Comment by marcotcr** [comment]
It should be
`explainer_dt = explainer.explain_instance(X_test_array[2], dt.classifier.predict_proba))`

**Comment by RockLeeStudio** [comment]
cool.

**Comment by jahnavi2k** [comment]
> How can LIME be used for unsupervised algorithms , say K-Means clustering?



> Error I am getting on executing this:
> 
> File "C:\Python27\lib\site-packages\lime\lime_tabular.py", line 274, in explain_instance yss = predict_fn(inverse) TypeError: 'numpy.ndarray' object is not callable

Hey @rahuldatsme!
Were you able to resolve this?
