### ISSUE TITLE
Add support ignore_expressions?

### ISSUE THREAD

**Issue by jaderabbit** [marcotcr/lime#27]
Hi Marko,

I have a few words (using the text explainer) which are obvious and the explanation of those features is cluttering the explanations. I want to go about contributing an `ignore_expression` I think.

I was thinking of just use the `split_expression` field to do this but then I realised it might sometimes result in empty strings being matched if the ignored word at the beginning of the string. Would it replace those empty strings?

Ideas:
- Instead of `re.split`, use something similar that will ignore the empty strings
- Filter the `vocab` dict by not adding empty strings 
- Add a `ignore_expression` to make sure those words are never added?

Any feedback would be appreciated :)

**Comment by marcotcr** [comment]
If you pass in a split expression like this:
``` split_expression = '|'.join(['\W+', 'word1', 'word2'])```
Lime will keep your ignored words ('word1', 'word2') fixed just like it does spacing and punctuation (it will only perturb whatever does not match the split expression). It doesn't really matter if it matches a few empty strings, as it will not use those for anything.

I guess a conceptual question to ask is: if there are obvious features that explain your model well, why don't you want them?

**Comment by jaderabbit** [comment]
That is essentially what I ended up doing. :)

Well, I don't want them because they are necessary but not sufficient phrases for a certain class to be chosen and they occur in some way or another in every pattern. Basically, they're confusing investors :P
