### ISSUE TITLE
Lime package installation  done, but not able to import module in jupyter notebook

### ISSUE THREAD

**Issue by tusharu14** [marcotcr/lime#270]
The following things appear when i try pip installing lime on command prompt, but jupyter throws an error stating " No module found" when i try importing the lime module. Below is the output of the lime installation

C:\Users\TUSHAR\Anaconda3\anaconda_new>pip install lime
Collecting lime
Requirement already satisfied: scikit-learn>=0.18 in c:\users\tushar\anaconda3\anaconda_new\lib\site-packages (from lime) (0.18.1)
Requirement already satisfied: scikit-image>=0.12 in c:\users\tushar\anaconda3\anaconda_new\lib\site-packages (from lime) (0.12.3)
Requirement already satisfied: scipy in c:\users\tushar\anaconda3\anaconda_new\lib\site-packages (from lime) (0.18.1)
Requirement already satisfied: numpy in c:\users\tushar\anaconda3\anaconda_new\lib\site-packages (from lime) (1.11.3)
Requirement already satisfied: six>=1.7.3 in c:\users\tushar\anaconda3\anaconda_new\lib\site-packages (from scikit-image>=0.12->lime) (1.11.0)
Requirement already satisfied: networkx>=1.8 in c:\users\tushar\anaconda3\anaconda_new\lib\site-packages (from scikit-image>=0.12->lime) (1.11)
Requirement already satisfied: pillow>=2.1.0 in c:\users\tushar\anaconda3\anaconda_new\lib\site-packages (from scikit-image>=0.12->lime) (4.0.0)
No metadata found in c:\users\tushar\anaconda3\anaconda_new\lib\site-packages
Requirement already satisfied: dask[array]>=0.5.0 in c:\users\tushar\anaconda3\anaconda_new\lib\site-packages (from scikit-image>=0.12->lime) (0.13.0)
Requirement already satisfied: decorator>=3.4.0 in c:\users\tushar\anaconda3\anaconda_new\lib\site-packages (from networkx>=1.8->scikit-image>=0.12->lime) (4.0.11)
Requirement already satisfied: toolz>=0.7.2 in c:\users\tushar\anaconda3\anaconda_new\lib\site-packages (from dask[array]>=0.5.0->scikit-image>=0.12->lime) (0.8.2)
Installing collected packages: lime
Successfully installed lime-0.1.1.32

The output of the installation also shows that there was no metadata found, what could be the reason behind it ?

**Comment by SparshaD** [comment]
What was the issue. Though it appears to be a bit silly I am facing the same issue..
