### ISSUE TITLE
Lime not displaying two categories of two class calssification problem

### ISSUE THREAD

**Issue by tusharu14** [marcotcr/lime#274]
I have made a neural network for the banking dataset from the UCI machine learning repository and have tried lime for displaying the results, however when i make the explainer only one class's information is being shown(probability score), and i wanted to display both the class's probability, please help.

(below is the screenshot of the visualization i am able to view on my notebook).

![lime](https://user-images.githubusercontent.com/21282045/50489854-121b5580-0a30-11e9-81dd-0d5a5526074a.jpg)

**Comment by marcotcr** [comment]
Please verify that your `classifier.predict_proba` outputs a (n, 2) numpy array.
