### ISSUE TITLE
Lime explanation only highlights the first word

### ISSUE THREAD

**Issue by kimbold** [marcotcr/lime#276]
Hello, I just started to use Lime and executed the multiclass jupyternotebook tutorial. 
I did not change the code and executed all cells, but in the explanation only the first word is being highlighted and included in the explanation:

![lime_issue_only_one_word](https://user-images.githubusercontent.com/16795915/50738158-4a115e00-11d1-11e9-922b-5d900ad5b213.png)

How can I fix this?

**Comment by marcotcr** [comment]
Cannot replicate, I reran the notebooks on python2 and 3.

**Comment by kimbold** [comment]
Thanks for rerunning them. 
It works now. I am not really sure what the issue was, but the text is highlighted correctly now. 
I previously used jupyter notebook via anaconda but used it now without anaconda (working on windows). So maybe the issue was caused by that or something.
