### ISSUE TITLE
RFE: ein compatibility

### ISSUE THREAD

**Issue by sam-s** [marcotcr/lime#278]
[EIN](https://github.com/millejoh/emacs-ipython-notebook/) [cannot show LIME explanations](https://github.com/millejoh/emacs-ipython-notebook/issues/448) because they, apparently, rely on JavaScript. 
It would be nice if LIME could (optionally) output explanations in a more conventional way.
Thanks.

**Comment by marcotcr** [comment]
It can, you can generate a pyplot figure with `exp.as_pyplot_figure`, or as a list or map of weights (`exp.as_list` and `exp.as_map`).
