### ISSUE TITLE
 TypeError: __init__() got multiple values for argument 'mode'

### ISSUE THREAD

**Issue by Claudia1806** [marcotcr/lime#279]
<img width="848" alt="mode_error" src="https://user-images.githubusercontent.com/28003009/50982277-20bc3f00-14fd-11e9-80cc-eecdecc6db20.PNG">

I'd be very happy if someone could help me with this error message

**Comment by marcotcr** [comment]
feature_names is a keyword argument, but you are passing it as a non keyword argument in the second position, which is the position for `mode`
change your call to have `feature_names=feature_names` and you will be fine.

**Comment by Iamifra16** [comment]
![image](https://user-images.githubusercontent.com/102189333/177124679-5234e164-76f1-4565-810a-99d5e8fc192f.png)
i got stuck in this error, can somebody help?
