### ISSUE TITLE
Feature names in exported html file are not visible

### ISSUE THREAD

**Issue by ritviksahajpal** [marcotcr/lime#28]
Thanks for an awesome package! Looking forward to using LIME more in my work.

I had a query re visualization. In the html file that is exported out, some of the feature names are not visible. Can that be fixed?

![picture1](https://cloud.githubusercontent.com/assets/2277375/19028877/2738a02a-890f-11e6-84cc-32a2f4593f25.png)

**Comment by marcotcr** [comment]
What browser are you using? It should at least have ... at the end of the feature names (we cut them if they're too long).
I guess I need to add an option to make the linear model a little wider, I'll try to do this soon.
Sorry for the delay!

**Comment by ritviksahajpal** [comment]
thanks @marcotcr , I am using Chrome (Windows and Mac). Thanks again for an excellent library!

**Comment by marcotcr** [comment]
Sorry, I wasn't able to replicate this. If the feature names are shortened, there should be a '...' at the end to indicate it.
Anyway, I made the barplot a little wider in the next release.

**Comment by ritviksahajpal** [comment]
thanks!
