### ISSUE TITLE
Is it possible to choose set of features in the .explain_instance instead of giving the quantity 

### ISSUE THREAD

**Issue by engmubarak48** [marcotcr/lime#280]
Hi Marco, 

In this snippet 
exp = explainer.explain_instance(class1.iloc[i], gridsearch.best_estimator_.predict_proba, num_features=6)

we provided "num_features" as number (in my case, 6). but is it possible to give a list of features( for example, ['-----','-------'])?. I want to know the effect of such features on the instance we are investigating. this would be helpful as such datasets might have 100+ features. 

Also, is there another possible way of doing it? 

Thanks for your time.

**Comment by marcotcr** [comment]
There is no way of doing that with the code as it is, you would have to either write another version of `__data_inverse` (see [this](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L389)) to take in a list of features an either only perturb those features, or write a `feature_selection` function that only keeps the features you choose, depending on whether you want to keep the rest of the instance fixed or not. Either way, what could happen is that your chosen features have no effect on the underlying model.
