### ISSUE TITLE
Incorrect values returned Explanation.feature_frequencies

### ISSUE THREAD

**Issue by thegalang** [marcotcr/lime#281]
code: https://ideone.com/fvp8BN
dataset used: https://pastebin.com/TXSrx6vc

If i understand the code correctly, Explainer.feature_frequencies[i] should return fraction of the i'th label in the data.

Here i made a simple dataset and tested the correctness of feature_frequencies on the first label. The correct output should be [0.22222 0.44444 0.333333]

I believe that the bug occurs in that collections.Counter() will not always return the tuples sorted by the key and instead by the first appeared value.

**Comment by thegalang** [comment]
[explaner.feature_frequencies bug.zip](https://github.com/marcotcr/lime/files/2781215/explaner.feature_frequencies.bug.zip)

A notebook doing the bug step-by-step.

**Comment by thegalang** [comment]
[feature_frequencies_bug.zip](https://github.com/marcotcr/lime/files/2781221/feature_frequencies_bug.zip)

here is a notebook of the bug

**Comment by marcotcr** [comment]
I think there is no bug. If you notice where `feature_frequencies` is used [here](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L430), we use `feature_values`, which correspond to the correct frequencies. You are right that collections.Counter will return tuples sorted arbitrarily, but that is not a problem if we use the values in the same order. 
In your example, if you check explainer.feature_values[0], you will notice that the frequencies are associated with the correct values. The following also helps you check that:
`explainer.feature_frequencies[0][np.array(explainer.feature_values[0]).astype(int)]`

If I'm mistaken, let me know and I'll reopen this and the pull request.

**Comment by thegalang** [comment]
hello, in https://marcotcr.github.io/lime/tutorials/Tutorial%20-%20continuous%20and%20categorical%20features.html on terminal 30 you directly access explainer.feature_frequencies[4] assuming its the correct one for odor='Foul'.

**Comment by marcotcr** [comment]
Ah, good point. A quick question though: is sorting by key what we want? I think what we want is to have this order match `self.categorical_names`

**Comment by thegalang** [comment]
From definition, categorical_names[i] is the name of the i'th label right. So the 0th name is the label 0, 1th name is the label 0, and so on.

So sorting by keys will put then labels in ascending order.

**Comment by thegalang** [comment]
hello, just reminding about this issue
@marcotcr

**Comment by marcotcr** [comment]
Thanks!
