### ISSUE TITLE
Documentation lime_base.explain_instance_with_data incorrect

### ISSUE THREAD

**Issue by fvermeij** [marcotcr/lime#292]
Here is the problem in question:  https://github.com/marcotcr/lime/blob/master/lime/lime_base.py#L142

It states it returns 3 values. But in actuality, it returns 4 values. I'm fairly sure it used to return 3 values, so this caused a script to break. But that is not that important to me since it's easy to fix. Still, would be nice the documentation would be updated, so others won't have to dig around in the source code to see why they get unexplained errors.

**Comment by marcotcr** [comment]
Thanks for noticing this, fixed in be535b0
