### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by krvoijac** [marcotcr/lime#294]
I'm not experienced in Python but I would like to use the LIME package. When I tried the "Basic usage, two class. We explain random forest classifiers" notebook I get the error in the figure attached.
![error](https://user-images.githubusercontent.com/47889933/53242223-6f382e00-36a4-11e9-9f8f-1ca90fa4a144.JPG)

I'm happy to provide more information if necessary. Thanks!

**Comment by lchamp87x** [comment]
I am also getting this same error when running explain_instance from a text explainer. 
<img width="1025" alt="screen shot 2019-02-27 at 2 20 16 pm" src="https://user-images.githubusercontent.com/46979587/53523760-e0a82000-3a9a-11e9-9510-97290e7806d4.png">

My code is directly based off that example but using different data.

**Comment by venkataramanam** [comment]
If you are running LIME with Python 3.7, you are likely to hit this issue.
Try with Python 3.6, it should get resolved. Nevertheless, the issue exists with Python 3.7.

**Comment by marcotcr** [comment]
I fixed this in 9c906b4a15ed98032b0b4ea6ab4ecada35f9ec30, but I guess I didn't create a new release on pypi since it was so minor. If you install from master, you shouldn't get this error.
