### ISSUE TITLE
Using LIME with point clouds and TensoFlow

### ISSUE THREAD

**Issue by valvador92** [marcotcr/lime#299]
I don't find any informations about the possibility of using LIME with a Neural Net classifier using Tensorflow. The data are point clouds. I am wondering if LIME could work with such a structure of data.

Thank you for your help

**Comment by marcotcr** [comment]
I am not familiar with point clouds. If you can map whatever data you have into a binary representation with a small dimensionality (e.g. for images we map the input to superpixels) that is interpretable to humans, LIME should work.

**Comment by remindchobits** [comment]
> I don't find any informations about the possibility of using LIME with a Neural Net classifier using Tensorflow. The data are point clouds. I am wondering if LIME could work with such a structure of data.
> 
> Thank you for your help

Hello, I am also working with point cloud and LIME. Have you found some way to do that?

Thanks,
