### ISSUE TITLE
Does the code work for regressors yet?

### ISSUE THREAD

**Issue by desilinguist** [marcotcr/lime#3]
Or is it only scikit-learn classifiers for now? I am interested in using LIME for some work that I am doing that uses SVRs. Would it be a lot of work to extend LIME to work with regression models? I am happy to help.

**Comment by marcotcr** [comment]
Hello!
If I'm not mistaken, the only thing that wouldn't work with regression right now is the "prediction probabilities" part of the visualization. I haven't tested LIME for regression very much, so I would be interested to know if it malfunctions.

It's a little harder to interpret the weights for regression (especially if the data is tabular), which I tried to solve by separating the local approximation model from the feature contributions in the visualization. This is not a great solution, and I'm working on something better, but it's not out yet.

Anyway, take a look at [this notebook](https://github.com/marcotcr/lime/blob/master/doc/notebooks/Using%20lime%20for%20regression.ipynb).

**Comment by desilinguist** [comment]
Thanks a lot! I will take a look. My use case employs an SVR with a very sparse binary feature set (lexical and syntactic n-grams), not a dense float feature set like the example in the notebook so it will be an interesting thing to try lime on.

**Comment by marcotcr** [comment]
That case is closer to cases where I've seen LIME work really well, so I would be interested to know how it works for you.

**Comment by desilinguist** [comment]
Sounds good. I will work on this over the next couple of weeks and keep you posted!

**Comment by ritviksahajpal** [comment]
@desilinguist , any luck with trying lime with regression problems?

**Comment by desilinguist** [comment]
Haven't had a chance to try it yet. Been swamped with some other stuff but it's on my list.

**Comment by ritviksahajpal** [comment]
thanks @desilinguist

**Comment by pramitchoudhary** [comment]
Hey guys, might be able to give it a try as well. @desilinguist @marcotcr @ritviksahajpal. Will update as I am able to lay my hands on the same.

**Comment by desilinguist** [comment]
I finally got around to trying this. I am trying to replicate the regression notebook but the explanation is producing some output that doesn't look like what I see on `nbviewer`:

<img width="620" alt="screen shot 2017-04-17 at 4 35 18 pm" src="https://cloud.githubusercontent.com/assets/161680/25103860/06f0585e-238c-11e7-83e0-6305b021e779.png">

**Comment by desilinguist** [comment]
Okay, I think I've spotted the bug. In `lime_tabular.py`, the  `discretize_continuous` parameter to the `LimeTabularExplainer` initializer is `True` by default and because of that, on [this line](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L152), `self.categorical_features` is always set to be the full set of features instead of the indices that are actually passed in.

**Comment by desilinguist** [comment]
Okay, so I tried something else - I took the all-categorical example from the more recent notebook and used a `RandomForestRegressor` instead of a classifier. This was pretty straightforward since the label is already a number. The explanation for an instance then looks as follows:

<img width="810" alt="screen shot 2017-04-18 at 10 46 49 am" src="https://cloud.githubusercontent.com/assets/161680/25136959/62c52aae-2424-11e7-8bce-4cdcc4dae684.png">

1. I am not sure why it's using a different set of colors instead of the orange and blue that is used for classification. 

2. It seems likely that the [regression notebook](https://github.com/marcotcr/lime/blob/master/doc/notebooks/Using%20lime%20for%20regression.ipynb) is at this point out of date since I don't see a way of getting those results.

3. I am not entirely sure how to interpret the explanation in terms of regression. I guess the obvious way to think about it is that all of the bars in green decrease the "poisonous" value of a mushroom  and all the bars in blue increase it? 

4. I see that there's an open PR for regression support. I'll look into that next.

**Comment by marcotcr** [comment]
1. Also not sure, I have to take a look into that. I'll wait for the regression PR to land though
2. The regression notebook is woefully out of date - it was never a real tutorial, just an example I put together for this issue : ).
3. Yes
4. Please do : )

**Comment by melkoujo** [comment]
Hi Marco,

I would ask if you have now a new version that can be possible to use LIME as regression model.

I thank you in advance for you consideration.

**Comment by Aylr** [comment]
FYI I've taken the stagnant PR #52 and made *minor changes* to update it and get it to pass the CI flake8 style check. The new PR us #74

**Comment by Aylr** [comment]
And now @desilinguist has addressed the main concerns expressed in #52 in the new PR #74.
