### ISSUE TITLE
[Question] Using LIME with sparse bag of words representation

### ISSUE THREAD

**Issue by kjanko** [marcotcr/lime#300]
Hi,

I'm trying to use LIME with (scipy)sparse bag-of-words vectors. The issue is, the TextExplainer does not support this type of representation (judging by the error messages, it only works with vectors made out of strings(words)), and TabularExplainer seems to be way too slow.

Is there something that I'm missing or doing wrong? How should I approach the issue if I want to use LIME with BoW representations?

**Comment by marcotcr** [comment]
You are correct, we don't support this. I'm guessing tabular explainer is too slow because it's turning your sparse vector into a dense one and trying to perturb everything. Assuming you have an encoder from text to BOW, you could just use a string as the first parameter to `explain_instance` and use a wrapper for the prediction function that includes the encoder, e.g.:
```
def new_predict_fn(texts):
    return predict_fn(encoder.encode(texts))
```

**Comment by marcotcr** [comment]
If you can represent your data as a sparse bow vector, you can represent it in a string, and use `bow=True` in LimeTextExplainer. Say your sparse vector has 1s in features 1, 2, and 5. Just convert that to the string 'token1 token2 token5', and write an encoder that takes strings like that and returns the bow vector.
Does this make sense?

**Comment by kjanko** [comment]
I tried doing what you suggested and I'm running into another issue:

['573 2573 4357 5981 10827', '573 2573 4357 5981 ', '    ', '    ', '    ', '573  4357 5981 10827', '573    ', '573    1082

This is what a sample of the input that goes into the encoder. What's with the empty strings?

**Comment by kjanko** [comment]
Just to confirm: {'8687', '6080', '5198', '4579'}
Tokens are returned correctly.

**Comment by marcotcr** [comment]
the empty string is just setting all of the features to 0

**Comment by kjanko** [comment]
So how should I handle it? Would it be a 0:0 entry in the sparse matrix?

**Comment by marcotcr** [comment]
yep

**Comment by kjanko** [comment]
Works 👍

I also think I've found a bug with show_in_notebook() method: under site-packages the module is installed under "lime-0.1.1.33-py3.7.egg" but the method is searching for only "lime" (when resolving bundle.js dependency)
