### ISSUE TITLE
Latest release forces a downgrade of matplotlib

### ISSUE THREAD

**Issue by jgbustos** [marcotcr/lime#302]
The setup.py file states that one of the dependencies is "matplotlib==2.1.0", which forces a downgrade of matplotlib. While this might be useful for Python 2 users, it breaks lime for those using Python 3.

Ideally, this could be changed to use platform specific dependencies (see https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies and https://www.python.org/dev/peps/pep-0508/) so the downgrade is only forced for Python 2.

Maybe state 'matplotlib==2.1.0;python_version<"3.0"' as the dependency line?

Many thanks

**Comment by marcotcr** [comment]
Thanks, I was looking for something like this yesterday. Added in f7f63fb8bd479a13323a63a5fee2c22b75fe4b27
