### ISSUE TITLE
Weights for text classifier explanation do not add up

### ISSUE THREAD

**Issue by duphan2014** [marcotcr/lime#304]
Hi Marco and the team,

I ran Lime on a RandomForest classifier for text classification and got an issue that I did not quite understand. Please refer to photo in this link https://ibb.co/7bfKFSm. All the weights don't seem to add up to the their corresponding class probability, and the sum of all the weights for sales are higher than the sum of all the weights for Engineering, even though both the blackbox and the local model agree that this instance is of class "Engineering". This happens for many instances in my data not just this one.

Could you please explain this for me?

Thank you very much.

**Comment by marcotcr** [comment]
There is an intercept term (exp.intercept) in the explanation, we don't display it because it sometimes is confusing. I am guessing that the explanation listed has a high intercept towards class engineering. This is usually the case when there is class imbalance, is it the case that most labels are 'engineering'?

**Comment by duphan2014** [comment]
Hi Marco,

Thank you for your response. There is a slight class imbalance but not that severe.

Engineering Jobs                     8210
Sales Jobs                           5349

Do you still think class imbalance have something to do with this?

Besides that, I think I've just figured out that those with 0.0 are actually rounded up by using exp.as_pyplot_figure() instead of exp.show_in_notebook(text=True). Please have a look at the image https://ibb.co/8K0JnkF

Can you please confirm if that's the case?

Kind regards

**Comment by marcotcr** [comment]
Yes, it does seem like class imbalance explains it (you have to check the intercept to make sure). There is a bias towards predicting 'Engineering' in the figure you posted, and while there is some evidence towards 'sales', it is not enough to overcome the bias.

`show_in_notebook` does round numbers, but that is a good practice. A weight of 0.0025 is the same thing as a 0 weight, and should not be interpreted as contributing towards a prediction.
