### ISSUE TITLE
Binary classification: Problem with displaying the results because of probability prediction function used in explain instance. 

### ISSUE THREAD

**Issue by MariaSahakyan** [marcotcr/lime#305]
Hello. I have problems with displaying the LIME explain instance results. I used LightGBM classifier for training, and as advised (https://github.com/marcotcr/lime/issues/51), I used the wrapped function in explain instance.
![image](https://user-images.githubusercontent.com/38503390/54590068-afd75d00-4a40-11e9-925f-b1883fa8019e.png)

![image](https://user-images.githubusercontent.com/38503390/54590137-caa9d180-4a40-11e9-9598-8ec22c44d7e1.png)

 However, when I want to display the results by using exp=show_in_notebook(labels=None, predict_proba=True, show_predicted_value=True) 
I receive the following error 

![image](https://user-images.githubusercontent.com/38503390/54590165-dd240b00-4a40-11e9-9691-3dd21e43b675.png)

On the other hand, I tried to change the predict probability function a bit, the following way (flatten_predict(i), see image) 

![image](https://user-images.githubusercontent.com/38503390/54589597-80742080-4a3f-11e9-9cde-768baaee4d81.png)

Using this one I managed to display the results in notebook, however, the results seem incorrect (as the classification is binary classification with 0 and 1), but the displayed one is something strange. Please see the picture. 
![photo_2019-03-17_16-28-04](https://user-images.githubusercontent.com/38503390/54589153-4bb39980-4a3e-11e9-8f26-5caf1643cf12.jpg)

Could you please advice, what is wrong in my function, or, how can I display the explainer, using the advised function. 

Thanks in advance
Maria

**Comment by marcotcr** [comment]
Please verify if:
- `wrapped_fn(X_train.as_matrix()[:3]).shape` is `(3, 2)`
- `type(X_train.columns) == list` and `type(X_train.columns)[0] == str`

**Comment by MariaSahakyan** [comment]
Hi Marco.
Thanks for responding.
All is true, except that X_train.columns type is Index. Should I convert it somehow?
Here is the screenshot. 

![image](https://user-images.githubusercontent.com/38503390/55055499-92c40f00-507c-11e9-89e7-cf2c59791fc3.png)

**Comment by MariaSahakyan** [comment]
I have saved this as HTML and tried to open in Chrome. Here is the point in the code that it throws the exception.

![image](https://user-images.githubusercontent.com/38503390/55060196-57304180-508a-11e9-9abf-c604fef264b0.png)

The number 4 in there is a mystery for me. Could you please explain this part? It seems to me it tried to get the 4th label name but I have only 2 here.
```
(0, _lodash.range)(4, sorted.length).map(function(d) {
        return other.add(sorted[d].name);
 });
```

**Comment by MariaSahakyan** [comment]
Thank you very much. This helped a lot, now it works perfectly.
