### ISSUE TITLE
save_to_file fails if directory does not exist on Windows

### ISSUE THREAD

**Issue by DariaSh** [marcotcr/lime#306]
Not really a significant issue, but can add a check if a file_path directory exists and mkdir otherwise...

    def save_to_file(self,
                     file_path,
                     labels=None,
                     predict_proba=True,
                     show_predicted_value=True,
                     **kwargs):
        """Saves html explanation to file. .

        Params:
            file_path: file to save explanations to

        See as_html() for additional parameters.

        """
        
        if not os.path.exists(os.path.dirname(file_path)):
            try:
                os.makedirs(os.path.dirname(file_path))
            except OSError as exc:
                if exc.errno != errno.EEXIST:
                    raise
        
        file_ = open(file_path, 'w', encoding='utf8')
        file_.write(self.as_html(labels=labels,
                                 predict_proba=predict_proba,
                                 show_predicted_value=show_predicted_value,
                                 **kwargs))
        file_.close()

**Comment by marcotcr** [comment]
I am not sure I want to create a directory for the user if the one provided doesn't exist. I guess I could go either way.
In the interest of simplicity, I think I'll leave it as is : )
Thanks,
