### ISSUE TITLE
Not getting consistent result for MLPRegression 

### ISSUE THREAD

**Issue by elahe91** [marcotcr/lime#307]
I wanted to use LimeTabularExplainer with MLPRegressor for getting to know the feature behavior. But the problem is with the same training and testing set I am getting inconsistent result. Am I doing anything wrong??

**Comment by marcotcr** [comment]
If by 'inconsistent result' you mean minor variations in weights, this is expected, see #67, #119, #199.
Otherwise, you need to provide more information : )
