### ISSUE TITLE
Tabular data example

### ISSUE THREAD

**Issue by palatos** [marcotcr/lime#313]
I was running the tabular data example in the repository, more specifically the Iris dataset one.

In particular, I was generating an explanation for "test[11]", which is the test dataset entry [5.4, 3.9, 1.7, 0.4]. The Random forest correctly classifies this as class 0 (setosa) with 99.8% probability.

However the generated explanation seems to have larger weights for features that go against this classification, and the only feature explaining the classification has a weight close to 0.

Is this counter-intuitive behavior or did I misunderstand the tabular explanations?

![image](https://user-images.githubusercontent.com/49554605/56028995-d317c400-5cef-11e9-88b2-c4a1f596d653.png)

Other entries of the dataset I've tested seem to work in the intuitive way.

**Comment by marcotcr** [comment]
Interesting find. This is a case where LIME was not able to produce a good local approximation, and thus the explanation is just bad. I would have to investigate more as to why that is, my guess is that the model is not locally linear close to this point, or the kernel width is not low enough to make the explanation accurate close to the instance. If you look at `exp.local_pred` and `exp.score`, you would see that `local_pred` is pretty far from the prediction and that `score` is really low, both of which are indications of the badness of the explanation (compare that with values in other explanations). It's rare for it to be so bad though!

**Comment by palatos** [comment]
Thank you for the quick and helpful answer!
I didn't think about checking the local_pred and score. That definitely shows why the explanation seemed counter intuitive.
Checking local_pred and score for all entries in the test set shows there's 3 samples that have this behavior (score below 0.1 and local_pred contradicting the model pred).
The other samples all agree with the model predictions, with scores varying from ~0.25 to ~0.9
![image](https://user-images.githubusercontent.com/49554605/56071621-0eed7080-5d66-11e9-8722-d1f5da089311.png)
If I could add two more questions, since this is one of the illustrative examples of tabular explanations in the repo:
1 - Would it be a good idea for the visualizations in the example to contain the explanation score? I think I wouldn't have come across this idea until I had a problem with a non intuitive explanation.
2 - I understand this is a very case-by-case scenario, but is there an intuitive way to decide on an acceptable score threshold for this particular Iris example? If so would it make sense to also add this to the example notebook?

**Comment by marcotcr** [comment]
Sorry for the delay in responding.

1. Yes, I think this would be a great idea. I unfortunately don't have bandwidth to do it at the moment, but I've considered adding a score _and_ a few examples in the neighborhood with the predictions (which would make it more intuitive for users, it's hard to interpret what a raw score means as I mention below)
2. I think it is very hard to do in general because the score depends on the kernel function, which in turn depends on the distance function.
