### ISSUE TITLE
XGBoost (sklearn Multioutputregressor) Multioutput regression vs LIME

### ISSUE THREAD

**Issue by DaveDarrel** [marcotcr/lime#314]
Hi, i'm trying to do a XGBRegressor (sklearn Multioutputregressor) multi-output regression (y1,y2,y3,y4...y30) , with 531 features and locally explain each Y forecast with LIME. I tried

multioutputregressor = MultiOutputRegressor(XGBRegressor(n_estimators=950, learning_rate=0.01, 
                                                         max_depth=9,
                                                         min_sample_size = 0.8, 
                                                         random_state=0
                                                         )).fit(X_train, y_train)

explainer = lime.lime_tabular.LimeTabularExplainer(X_train,
training_labels = y_features_list,
feature_names=feature_list,
verbose=True,
mode='regression')

exp = explainer.explain_instance(data_row = X_test0,:], 
                                 predict_fn = multioutputregressor.predict, 
                                 num_features=50)

But i get

ValueError: Your model needs to output single-dimensional numpyarrays, not arrays of (5000, 30) dimensions

Is there a way to do that with LIME ?

Thanks!

**Comment by marcotcr** [comment]
Right now regression assumes it's single regression. A simple thing you could do is to explain each regressor individually, i.e. write a wrapper like
```
def get_predict_fn(idx):
  def predict_fn(x):
    return multioutputregressor.predict(x)[:, idx]
  return predict_fn
```
And hten you can call explain_instance repeatedly. For example, if you want to explain the first output you would use `fn = get_predict_fn(0)` as input to `explain_instance` instaed of `multioutputregressor.predict`

**Comment by DaveDarrel** [comment]
Thanks you ! Very useful !
