### ISSUE TITLE
Where is submodular_pick documentation? 

### ISSUE THREAD

**Issue by robotenique** [marcotcr/lime#316]
Hello, I saw the paper and the notebook with the example of submodular pick, but I can't find it in the API docs. Could someone point me to the correct page?

Thanks!

**Comment by lrnzcig** [comment]
Hi. Had the same problem. The code itself is quite well documented and you can read about the API.

https://github.com/marcotcr/lime/blob/813fbd0f4f1b0499065fca1ca2159e20263bf8a8/lime/submodular_pick.py

Hope it helps.

**Comment by marcotcr** [comment]
It's been forever since I updated the API docs, I guess I have to go relearn how to do that : )
