### ISSUE TITLE
LIME and Multi-input CNN model

### ISSUE THREAD

**Issue by johnnypetr** [marcotcr/lime#317]
Hello,
I am trying to use LIME to interpret the output of a three-branch (three-input) Deep Learning CNN architecture which looks like as follows:
```
# Members
members_input = Input(shape=(61,4,3), name='members_input')
x1 = Dropout(0.2)(members_input)
x1 = Conv2D(32, kernel_size = (61,4), padding='valid', activation='relu', strides=1)(x1)
x1 = Flatten()(x1)

# Transactions
transactions_input = Input(shape=(61,39,3), name='transactions_input')
x2 = Dropout(0.2)(transactions_input)
x2 = Conv2D(32, kernel_size = (61,1,), padding='valid', activation='relu', strides=1)(x2)
x2 = Conv2D(32, kernel_size = (1,39,), padding='valid', activation='relu', strides=1)(x2)
x2 = Flatten()(x2)

# User logs
userlogs_input = Input(shape=(61,7,3), name='userlogs_input')
x3 = Dropout(0.2)(userlogs_input)
x3 = Conv2D(32, kernel_size = (61,1,), padding='valid', activation='relu', strides=1)(x3)
x3 = Conv2D(32, kernel_size = (1,7,), padding='valid', activation='relu', strides=1)(x3)
x3 = Flatten()(x3)

# User_logs + Transactions + Members
merged = keras.layers.concatenate([x1,x2,x3]) # Merged layer
out = Dense(2)(merged)
out_2 = Activation('softmax')(out)
```

However, I haven't found any cases similar to mine from which I can draw inspiration when trying to resolve this issue as I believe LIME wouldn't natively take in a list as an input. 
I receive this issue when trying to do so:

`AttributeError: 'list' object has no attribute 'shape'`

Am I doing something wrong? Or is there a workaround?

**Comment by marcotcr** [comment]
There is no way to have a 3d tabular input, as I don't know how to perturb that (unless it's an image or unless one of the dimensions represents time, in which case you can use `RecurrentTabularExplainer`).

I don't know what is being represented by your input, but one workaround would be to reshape it into a 1d array (i.e. flatten the input if it makes sense)
