### ISSUE TITLE
No explanations given

### ISSUE THREAD

**Issue by SamPersoon** [marcotcr/lime#318]
Hello!

I would like to interpret a Doc2Vec model followed by a classification algorithm. I tried multiple sample sizes [100, 5000, 10000, 100000] and a different number of features, but all weights are <0.01. My texts are around 2000 tokens.

``` python
explainer = LimeTextExplainer(class_names=['Not ' + label, label])
exp = explainer.explain_instance(case_to_explain, pipeline.predict_proba,
                                                     num_features=10, num_samples=sample_num)

```
The probabilities given are [0.95, 0.05] so pretty certain. I don't know why this is happening and how to solve it? Could this be correct output or is something wrong?

**Comment by marcotcr** [comment]
It could be a few things, but my first guess is that there is a high class imbalance and thus the intercept is driving most of the prediction for class 0 (interpret that as 'prediction of 0 does not need an explanation, it is the default').
Could you verify if this is the case?
