### ISSUE TITLE
regression deep model explanation for text dataset

### ISSUE THREAD

**Issue by zeevikal** [marcotcr/lime#320]
Hi, I've trained a DNN model for regression problem on text dataset.
my model including embedding, dense and LSTM layers.
can I use lime for this kind of model explanation? 
thanks!

**Comment by marcotcr** [comment]
Ugh, not without a hack. `LimeTabularExplainer` has a regression mode, but not `LimeTextExplainer`.
I'm pretty sure that if you wrap your prediction function in the following way it will work, except for the predict_proba part of the visualization (assuming predict_fn returns a 1d array with the regression outputs)
```
def wrapped_predict_fn(inputs):
    preds = predict_fn(inputs)
    return np.vstack((preds, preds)).T
```
