### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by seansaito** [marcotcr/lime#322]
Reading the LIME paper, I have a question for which I can't really find an answer. In Section 3.3 "Sampling for Local Exploration", the sampling algorithm is described to perturb the interpretable representation of `x` (denoted as `x'`) by drawing nonzero elements at random to generate `z'`. You then "recover the sample in the original representation `z \in R^d` and obtain `f(z)`, which is used as a label for the explanation model."

For text classification tasks, I understand that `x` is the raw text and `x'` can be a binary Bag of Words vectorization. My question is, how do we recover `x` from `x'` when `x'` does not encode any positional information? Or, more generally speaking, how does LIME recover `z` from `z'` when the interpretable representation loses information from the original representation?

I would greatly appreciate any clarification to this question. Looking forward to your reply!

**Comment by marcotcr** [comment]
In the paper, we assume that you can recover z from z'. In practice, that means you have to maintain some state when you convert z -> z' that allows you to transform z' back to z.
For the example you use (text and binary bag of words), we keep the positional information (exactly what you mentioned) in a separate structure.
