### ISSUE TITLE
Dependency on matplotlib 2.1 does not work in Linux docker

### ISSUE THREAD

**Issue by puneethmishra** [marcotcr/lime#325]
Hi ,

Due to the dependency on Matplotlib 2.1, im not able to install LIME package in Linux docker.

Matplotlib latest version works perfectly fine, but not able to downgrade.

Request you to please remove that dependency, so that it installs fine.

**Comment by marcotcr** [comment]
Which version of python are you using? Which version of LIME are you trying to install?

**Comment by puneethmishra** [comment]
I'm using python 3.7 and trying to install 0.1.1.34 version of LIME

**Comment by marcotcr** [comment]
There is no dependency on matplotlib==2.1 if python version is > 3:
` 'matplotlib;python_version>="3.0"',`
Unless this specification doesn't work.

**Comment by puneethmishra** [comment]
Thanks i got the git cloned and it installed fine. But while trying from pip the matplotlib 2.1 dependency still persists.
