### ISSUE TITLE
Preprocessing vs Segmentation

### ISSUE THREAD

**Issue by palatos** [marcotcr/lime#326]
I've seen this briefly discussed on another issue but I'm working on an example where I'm having the same problem and I'm not sure how to proceed.

I'm wondering if I can compare how two different models (lets say Resnet and Inception) explain a given instance. Lets also say that these two models have different pre-processing for the images. For example:
Resnet maps pixels like [0 to 255] -> [0 to 1] (image = image/255)
Inception maps pixels like [0 to 255] -> [-1 to 1] (image = 2*(image/255-0.5))

If I run both preprocessed images through a segmentation algorithm, I shouldn't expect the resulting superpixels to be the same on both cases, right? The segmentation is sensitive to the preprocessing?

At the same time, if I tried to force the Resnet-preprocessing superpixels on the Inception model (or vice versa), would that make sense?

Or, alternatively, should I segment the images before any preprocessing is applied, and then only apply preprocessing within the prediction function? I'm just not sure this makes sense for -1 to 1 preprocessing because maybe this should indeed affect the superpixels. What if I had a weird preprocessing that maps to [-2 to 854] or some other weird colormap?

I imagine the question is a bit confusing but hopefully it's clear enough. Thanks in advance for any advice.

**Comment by marcotcr** [comment]
The superpixel segmentation should depend on the natural representation of the image, and not at all on whatever preprocessing different networks do.

> Or, alternatively, should I segment the images before any preprocessing is applied, and then only apply preprocessing within the prediction function?

If I understood your question correctly, this is what you should do. Even if the model is doing something weird, you still want the explanation to be in terms of an image a user would understand (i.e. the superpixels are more likely to have semantic meaning in the original space).

**Comment by palatos** [comment]
Thank you for the prompt and helpful answer! If I could add one extra question, although it doesn't have to do with the previous one. I'm just not sure if this warrants an issue on its own.

If a model has a single output from a sigmoid activation( say like [0.64]), rather than a softmax-like multiclass output like most predict_proba() functions ([0.26 0.64] in this case), for a binary classification problem, do I have to write a custom prediction function to give these two probabilities or can I just pass the single valued predictions to explain_instance() ?

**Comment by marcotcr** [comment]
You can use a single output, but you will need to do two things. 
1. set `labels=(0,)` rather than the default (which is 1). 
2. You need the output to be a (n, 1) shaped numpy array, rather than (n, ). This means you may still have to write a wrapper, unfortunately.

**Comment by palatos** [comment]
Undestood. Thanks once again!
