### ISSUE TITLE
Tutorial - Image Classification Keras, getting the actual labels.

### ISSUE THREAD

**Issue by BjornPijpops** [marcotcr/lime#328]
I followed the tutorial for Image Classification Keras and got everything to work fine. However when trying it with new images I am faced with an issue.

When getting the predictions from the decode_predictions function, the output looks like this:
('n02123159', 'tiger_cat', 0.5438387)
('n02124075', 'Egyptian_cat', 0.2519924)
('n02123045', 'tabby', 0.07184614)
('n04589890', 'window_screen', 0.013598396)
('n02808440', 'bathtub', 0.0028444957)

This is the same type of output you had in the example. However,when making an instance of the lime_image explainer and using the .get_image_and_mask function the first parameter we should be giving is the label.

`temp, mask = explanation.get_image_and_mask(282, positive_only=True, num_features=5, hide_rest=True)`

The label, in my case a 'tiger_cat' is not 'n02123159' but 282. I found the number in the imagenet_class_index.json. Is there a better way to get this label without checking for it manually that I am missing or is this just the downside of the return format of decode_predictions?

**Comment by marcotcr** [comment]
I think you can still do `preds.argsort()[0][-5:]:` to get the top 5 labels, or argmax if you just care about the top 1. Alternatively, you can run `explanation.local_exp.keys()`, which will give you the labels for which you computed explanations. Unfortunately, this will be out of order.

**Comment by BjornPijpops** [comment]
Aha, thanks for the response. I am unsure what `preds.argsort()[0][5]` is suppose to do because I get 359 as an output which is pretty weird but `explanation.local_exp.keys()` is indeed what I was looking for.

You mentioned that they would be out of order but in my example they are in order (smallest percentage first).

**Comment by marcotcr** [comment]
`explanation.top_labels` will be in order if `top_labels` was used in computing explanations. Otherwise, there is no guarantee that local_exp.keys() will be in order.
