### ISSUE TITLE
Tutorial: Image Classification Keras - improvement

### ISSUE THREAD

**Issue by BjornPijpops** [marcotcr/lime#332]
I feel like a small improvement can be made to this tutorial. Making it so that people will not be getting the 'KeyError: Label not in explanation' error again. This error tends to occur when people use different images and don't know what the label variable does.

This can however be optimized so the label is always chosen correctly.

Adding this:
```
# Labels going from lowest percentage to highest
labels = list(explanation.local_exp.keys())

# Labels from highest to lowest -- preference
labels.reverse()
```

Change the get_image_and_mask call from:
`temp, mask = explanation.get_image_and_mask(295, positive_only=True, num_features=5, hide_rest=True)`

to:
`temp, mask = explanation.get_image_and_mask(labels[0], positive_only=True, num_features=5, hide_rest=True)`

I personally feel that this would be an improvement to the tutorial and would also allow people to instantly see how to get the actual labels.

**Comment by marcotcr** [comment]
It would be an improvement, but unfortunately local_exp.keys() will not necessarily be in order. I changed the tutorial according to your suggestion in e38258a5eecc7023b32219d59628a8e73b34345a
