### ISSUE TITLE
how to use lime with xgboost?

### ISSUE THREAD

**Issue by francescolosterzo** [marcotcr/lime#334]
Hello!

I **love** lime and I used it so far to explain predictions of sklearn-based models. I am now switching to xgboost to use the `xgboost.Booster()`, but I see that lime is not working out of the box on this.

Here is where I get the error:
```
data = xgb.DMatrix(X_row, y_row)
exp = explainer.explain_instance(data, model.predict)
```
where `X_row` and `y_row` are the features and labels of the single instance I want to explain, and here is the error I get:
```
~/anaconda3/envs/testenv/lib/python3.7/site-packages/lime/lime_tabular.py in explain_instance(self, data_row, predict_fn, labels, top_labels, num_features, num_samples, distance_metric, model_regressor)
    309             explanations.
    310         """
--> 311         data, inverse = self.__data_inverse(data_row, num_samples)
    312         scaled_data = (data - self.scaler.mean_) / self.scaler.scale_
    313 

~/anaconda3/envs/testenv/lib/python3.7/site-packages/lime/lime_tabular.py in __data_inverse(self, data_row, num_samples)
    449                 binary, but categorical (as the original data)
    450         """
--> 451         data = np.zeros((num_samples, data_row.shape[0]))
    452         categorical_features = range(data_row.shape[0])
    453         if self.discretizer is None:

AttributeError: 'DMatrix' object has no attribute 'shape'
```

The main point here is that the xgboost model only takes as input an `xgboost.DMatrix()` object, while the lime explainer assumes the input to be a numpy array.

Is there any workaround for this? Am I missing anything?

**Comment by marcotcr** [comment]
LimeTabularExplainer expects as input a numpy array, rather than a xgb.DMatrix. 
I'm assuming X_row is a numpy array. If so, you can wrap the prediction function so as to have the conversion to DMatrix in it, something like:
```
def wrapped_predict(data):
  dummy_y = [1 for _ in data.shape[0]]
  data = convert_numpy_to_dmatrix(data, dummy_y)
  return model.predict(data)
```

The other thing you can do is to use the sklearn API included in xgboost, i.e. use `xgboost.XGBRegressor` or `xgboost.XGBClassifier`.

**Comment by francescolosterzo** [comment]
I thought there was something built-in already, but in the end I wrote a wrapper as you suggested.
Here it is:
```
def wrapped_predict(data_x):
    '''
    wrap xgboost predict function in order to make it lime-friendly
    '''
    
    dummy_y = np.array([ 1 for _ in range(data_x.shape[0]) ])
    tmp_data = xgb.DMatrix(data_x, dummy_y, feature_names=feat_names)
    
    tmp_out = model.predict(tmp_data)
    
    # add the first column to make it like predict_proba
    out = np.zeros((data_x.shape[0], 2))
    out[:, 0] = 1-tmp_out
    out[:, 1] = tmp_out
    
    return out
```

Also, let me point out that `xgboost.XGBRegressor` and `xgboost.XGBClassifier` work out of the box with `lime` as you were suggesting, but they are not the `xgboost.Booster()` (i.e. what you get as output of `xgboost.train()`) which is, in my understanding, the whole point of using `xgboost`.

**Comment by elseml** [comment]
Hello,

since I am bound to use `xgboost.train()` with LIME, I'd love to utilize the wrapper @francescolosterzo provided. Unfortunately, I can't get it to work in my case. I understood your thoughts in the way that you provide your data row as usual and then use the `wrapped_predict` function which you input the whole corresponding data: 

```
feature_names = X
model = xgb_model
LIME_explainer.explain_instance(valid.iloc[0,:12],  wrapped_predict(valid.iloc[:,:12]))
```
What did I get wrong about this? Does one have to use the DMatrix instead of the DataFrame or did I provide the data in the wrong format?

The code throws the following error:

```
C:\Programs\Anaconda3\lib\site-packages\lime\lime_tabular.py in explain_instance(self,
data_row, predict_fn, labels, top_labels, num_features, num_samples, distance_metric, model_regressor)
    353         ).ravel()
    354 
--> 355         yss = predict_fn(inverse)
    356 
    357         # for classification, the model needs to provide a list of tuples - classes

TypeError: 'numpy.ndarray' object is not callable
```


Any help on this topic would be deeply appreciated!

**Comment by francescolosterzo** [comment]
Hi!

sorry for the late reply!

I guess the problem is in how you call it?
Here is what I do:
```
explainer.explain_instance(data, xgb_wrapped_predict)
```
as you can see the second argument is the wrapped predictor itself, i.e. the function, not the function computer over a given (set of) value(s), which is what you get if you pass it over with a specific input.

Maybe this helps?

**Comment by SrikanthPusarla** [comment]
Hi francescolosterzo

I tried your wrapper function, I passed only one sample/row of 'numpy.ndarray' of (304,) for explanation but where as data_x shape is becoming (5000, 304) inside wrapper function, not sure why?

** please find code snippet &  details below:**
x_train is <class 'numpy.matrix'> (29424, 304) -- 304 features
y_train is <class 'numpy.ndarray'> (29424,)
x_val is <class 'numpy.matrix'> (2785, 304)

x_t =  np.squeeze(np.asarray(x_train))   ## LimeTabularExplainer needs ndarray

explainer = lime.lime_tabular.LimeTabularExplainer(x_t, feature_names = features, class_names = ['0', '1']) 

              def wrapped_predict(data_x):
                  '''
                  wrap xgboost predict function in order to make it lime-friendly
                  - model and feature_names are defined outside
                  '''
                  print(data_x.shape)
                  dummy_y = np.array([ 1 for _ in range(data_x.shape[0]) ])
                  print(dummy_y)
                  tmp_data = xgb.DMatrix(data_x, dummy_y, feature_names=features)
                  print(tmp_data)
                  
                  tmp_out = _model.predict(tmp_data)
                  print(tmp_out)
                  
                  # add the first column to make it like predict_proba
                  out = np.zeros((data_x.shape[0], 2))
                  print(out)
                  out[:, 0] = 1-tmp_out
                  out[:, 1] = tmp_out
                  print(out)
                  return out


x_v = np.squeeze(np.asarray(x_val))    # explainer needs ndarray

exp = explainer.explain_instance(x_v[0], wrapped_predict, num_features = 304)

it is giving output as 

**(5000, 304)
[1 1 1 ... 1 1 1]
<xgboost.core.DMatrix object at 0x7f831ba15d60>
[0.04686321 0.01429689 0.013503   ... 0.01028677 0.01482881 0.01389816]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.9531368  0.04686321]
 [0.98570311 0.01429689]
 [0.98649698 0.013503  ]
 ...
 [0.98971325 0.01028677]
 [0.9851712  0.01482881]
 [0.98610187 0.01389816]]**

please help me how to fix this.

Thanks,
Srikanth
