### ISSUE TITLE
adding scipy sparse support for lime

### ISSUE THREAD

**Issue by imatiach-msft** [marcotcr/lime#335]
Hi, I recently added scipy.sparse support for KernelExplainer in shap and would like to do something similar for LimeTabularExplainer.  First, is this actually feasible?  LIME randomly samples points around a given point, in the sparse case with a naive implementation this would make the samples dense which we would want to avoid.  Sampling around non-zero features only for a given sparse point would work but may miss some important perturbations, but maybe that is fine in the sparse case.  I can also imagine a more complex method that does sampling for zero values for a given point only some ratio of the time proportional to the number of non-zeros for the feature.

**Comment by marcotcr** [comment]
Hi,
Everything you said is correct. If it is important to sample the non-zero items, the options are to do dense sampling, or to have some perturbation distribution that takes sparsity into account as you described.

Sampling only around non-zero features is what we do in `LimeTextExplainer`, and I think it makes sense in that domain. I think having this option would already be way better than the current status quo (where we just don't support scipy sparse for tabular data), we just have to be careful in the documentation (or more importantly, in the tutorial example) to make sure people understand that is what is happening.

Thanks for being willing to (potentially) help! Feel free to reopen the issue if there are more questions, or even to email me directly.
