### ISSUE TITLE
Minimum predictive performance (accuracy) of classifier for LIME to work properly.

### ISSUE THREAD

**Issue by arteagac** [marcotcr/lime#336]
Thank you for publishing this great library.
I have a quick question. Can I still use LIME even if my classifier yields "low" accuracy (i.e. classifier with prediction accuracy of 65%)?  Is there a minimum predictive accuracy that should be considered in order for LIME to work properly?
Given that LIME relies on the `classifier.predict_proba` function, I assume that the predictive performance of the classifier is very important; however, I am not sure at what level of accuracy I can start using LIME. 
Thank you in advance!

**Comment by marcotcr** [comment]
I think the accuracy of a model is not relevant for LIME to work. The goal of LIME is to help the user understand the predictions of the model, and which parts of the input lead to those predictions. The model may have 0% accuracy, and LIME can still surface _why_ it is making the (wrong) predictions it is making.
