### ISSUE TITLE
Prediction probabilities do not sum to 1

### ISSUE THREAD

**Issue by drjosephliu** [marcotcr/lime#339]
I'm using `LimeTabularExplanation` with a custom model. The model spits out scores, which I've converted to probabilities for compatibility with LIME. 

Problem is when I try to run `.explain_instance()`, I get the following error message:

```
py:342: UserWarning: 
                    Prediction probabilties do not sum to 1, and
                    thus does not constitute a probability space.
                    Check that you classifier outputs probabilities
                    (Not log probabilities, or actual class predictions).
```

I've gone back to double check what my prediction probabilities sum up to and I get `0.9999999999999967`. So not exactly 1 but close enough. I've tried rounding the probabilities and the best I got was `1.0000000026000089` when rounded to 10 decimal places.

Is there a way to get the explainer to work with sum of probabilities that does not exactly sum to 1, but is close enough?

**Comment by marcotcr** [comment]
That is just a warning, not an error message. If you are not getting explanations, something else is the problem.

**Comment by drjosephliu** [comment]
You're right. This is the actual error message:

```
IndexError                                Traceback (most recent call last)
<ipython-input-137-f61ecd743145> in <module>
----> 1 exp = explainer.explain_instance(np.asarray(positive_findings_map), interpret_positive_findings, num_features=2)

~/.pyenv/versions/3.6.5/envs/kb/lib/python3.6/site-packages/lime/lime_tabular.py in explain_instance(self, data_row, predict_fn, labels, top_labels, num_features, num_samples, distance_metric, model_regressor)
    416                     num_features,
    417                     model_regressor=model_regressor,
--> 418                     feature_selection=self.feature_selection)
    419 
    420         if self.mode == "regression":

~/.pyenv/versions/3.6.5/envs/kb/lib/python3.6/site-packages/lime/lime_base.py in explain_instance_with_data(self, neighborhood_data, neighborhood_labels, distances, label, num_features, feature_selection, model_regressor)
    151 
    152         weights = self.kernel_fn(distances)
--> 153         labels_column = neighborhood_labels[:, label]
    154         used_features = self.feature_selection(neighborhood_data,
    155                                                labels_column,

IndexError: index 1 is out of bounds for axis 1 with size 1
```

Any idea why I'm getting this?

For the `data_row` argument, I'm inputting a 1D NumPy array.

And for the `predict_fn` argument, I'm inputting a function that takes in a 1D NumPy array and outputs 2D NumPy array which I've reshaped.

**Comment by drjosephliu** [comment]
Closing this as it looks like I was using the explainer wrong for my given model

**Comment by Hoozits728** [comment]
@marcotcr , I'm wondering if we can re-open this issue as I am having the exact same problem.

**Comment by Hoozits728** [comment]
@marcotcr , never mind. I see you addressed the issue in a closed issue. Thanks, your response there did the trick for me.
