### ISSUE TITLE
How to map categories_names for LimeTabularExplainer for my model?

### ISSUE THREAD

**Issue by drjosephliu** [marcotcr/lime#340]
I have a diagnosis model that takes in some symptoms and spits out several possible diagnoses.

For example, if I have `nausea`, `vomiting`, `flu`, then the model may output these are diagnoses: `influenza`, `intestinal obstruction`.

I've been following the tutorial for `LimeTabularExplainer` with categorical features that involves the mushroom dataset. In that dataset, there are 22 different categories of features and a mushroom will have a feature in each category.

For my dataset, I have ~8000 different symptoms. I assume that each symptom would be mapped to an index in `categories_names`. But obviously a patient will not have a feature in each category. 

So what's the best way to map symptoms here for `categories_names`?

**Comment by marcotcr** [comment]
Sounds like you could make each symptom a categorical feature with possible values 0 (absent) or 1 (present), or a numerical feature if the values are continuous.
If all of your symptoms are binary, you could also use LimeTextExplainer and just input the symptom names as text.

**Comment by drjosephliu** [comment]
Yes you're spot on. To clarify what you mean by inputting the symptom names as text, if I have a test case who has the symptoms nausea, vomiting, flu then I would just input a raw string `"nausea vomiting flu"` as an argument into `explain_instance()`?

**Comment by drjosephliu** [comment]
So I added all the symptoms as a single string separated by commas and these are the results I got:

<img width="902" alt="Screenshot 2019-06-14 at 3 01 03 PM" src="https://user-images.githubusercontent.com/22230085/59541276-69659300-8eb5-11e9-8e95-c42f53b1a6ac.png">

For prediction probabilities it seems to be displaying some data, but for all the other graphs there is no data showing. Is there any reason for this?

**Comment by drjosephliu** [comment]
Turns out I was not adding all unexplained results into my classifier. Closing this now.
