### ISSUE TITLE
How to set number of "Prediction Probabilities" bars to display?

### ISSUE THREAD

**Issue by drjosephliu** [marcotcr/lime#341]
At the moment LIME seems to only display the top 4 prediction probabilities and concatenates all the others under "Other":

<img width="253" alt="Screenshot 2019-06-18 at 9 51 27 AM" src="https://user-images.githubusercontent.com/22230085/59703485-d37c8180-91ae-11e9-9dbf-8fe47de300ca.png">

Is there a way to customise these settings to view more than 4?

**Comment by marcotcr** [comment]
No, that is hardcoded to make the component fit.
Sorry  : )

**Comment by marcotcr** [comment]
You can use something else to visualize the prediction probabilities
