### ISSUE TITLE
Increasing num_features results in 0 values contributions

### ISSUE THREAD

**Issue by psxnl3** [marcotcr/lime#342]
I just started to use LIME. I'm trying to explain a LightGBM model, generated from a binary dataset with shape `(13091751, 58)` . The dataset has quite a lot of missing values
I create the explainer as:

```
import lightgbm as lgb
bst = lgb.Booster(model_file=path_model)
train = pandas.read_csv(path_to_csv)
explainer = lime.lime_tabular.LimeTabularExplainer(train.values,feature_names=bst.feature_name(), class_names=[0,1], discretize_continuous=True)
```
Then, I explain a prediction as:
```
exp = explainer.explain_instance(test.values[0], predict_fn, num_features=6)
```
where
```
def predict_fn(x):
  # Function necessary to get probabilities to be used by LIME
  # As described in here: https://github.com/marcotcr/lime/issues/51
  preds = bst.predict(x).reshape(-1, 1)
  p0 = 1 - preds
  return np.hstack((p0, preds))
```
The result seems correct as I get:
```
[('A_count <= 0.00', -0.06178344115449494),
 ('B_count <= 0.00', -0.052635802248307204),
 ('C_count <= 0.00', -0.05228960785493585),
 ('D_count <= 0.00', -0.04322376606191438),
 ('E_count <= 0.00', -0.03703730551001753),
 ('F_count <= 0.00', -0.026563804832789854)]
```
However, if I increase `num_features=7` or more, I get `NaN` and `0` as values:
```
[('G <= nan', 0.0),
 ('F <= nan', 0.0),
 ('H <= nan', 0.0),
 ('I <= nan', 0.0),
 ('L <= nan', 0.0),
 ('M <= nan', 0.0),
 ('N <= nan', 0.0)]
```
Please not that `G-N` are features with a lot of missing values. Can that be the issue? Why are all the contributions `0`?

**Comment by marcotcr** [comment]
Unfortunately you can't have missing values in the train dataset, as we use it to generate perturbations. I don't know why you get all 0 weights though, seems related to another issue I have to investigate.
