### ISSUE TITLE
Probabilities and classes are contradicting each other

### ISSUE THREAD

**Issue by rathee** [marcotcr/lime#343]
Prediction probabilities and the classes are different. Please see the attached file.
<img width="1440" alt="Screen Shot 2019-06-24 at 2 28 48 PM" src="https://user-images.githubusercontent.com/1786208/60005579-6d9b6880-968c-11e9-8c83-568e1dc6e6cb.png">

**Comment by marcotcr** [comment]
Would you please print `lime_clf.predict_proba([text])`, and confirm that `lime_clf.predict_proba([text])[0].argmax()` is 65? It sounds like your class names maybe are not aligned with the columns of predict_proba.
