### ISSUE TITLE
Help needed: Does the explainer work with MXnet models?

### ISSUE THREAD

**Issue by CarlosE97** [marcotcr/lime#344]
As I've noticed the use of the "Predict" function from keras in the "explain_instance" function, I want to use the explainer for MXNet models or GluonCV models, but I'm new to this field, I need some guidance. Thank you.

**Comment by marcotcr** [comment]
All you need is for the predict function to output an array with prediction probabilities. Take a look at [this](https://discuss.mxnet.io/t/wrapping-gluon-into-scikit-learn-like-api/2112) for people wrapping mxnet models like Sklearn, or just take a look at sklearn's predict_proba and make sure your model's output is in the same format.

**Comment by CarlosE97** [comment]
Thank you @marcotcr for you work ! ^_^
