### ISSUE TITLE
Can lime_tabular accept original categorical values?

### ISSUE THREAD

**Issue by junjiecai** [marcotcr/lime#346]
Hi

I am trying belowing code
``` python
import numpy as np
from lime import lime_tabular

data = array([
    ['1',  'a'],
    ['2',  'b'],
    ['1',  'c'],
    ['2',  'd']
])

labels = array(
    [
        0, 0, 1, 1
    ]
)

explainer = lime_tabular.LimeTabularExplainer(
    data,
    categorical_features=[0, 1],
    feature_names=['A', 'B']
)
```
And it raise an exception
```python
ValueError: could not convert string to float: 'a'
```

According to my understanding, what matters for categorical values are their frequency, not their values. 

I am not sure whether I misused the  lime_tabular.LimeTabularExplainer class or it need some modify to support original categorical values?

**Comment by marcotcr** [comment]
`LimeTabularExplainer` is assuming that the input is an array of floats, and that categorical features have been encoded (see line 16 of [this](https://marcotcr.github.io/lime/tutorials/Tutorial%20-%20continuous%20and%20categorical%20features.html)). We really should document that better. In any case, in your example we should have data being `[[0 , 0], [1, 1], [0, 2], [1, 3]]` and 
`categorical_names = {0: ['1', '2'], 1: ['a', 'b', 'c', 'd']}`

**Comment by maxhardt** [comment]
would be great to support original (string) values as well imo
