### ISSUE TITLE
Removing characters causing model malfunctioning

### ISSUE THREAD

**Issue by zd-project** [marcotcr/lime#351]
First, thank for the hard work for maintaining this project. 

I ran into a problem when experimenting with Lime Text model. The implementation blatantly removes character value (if char_level is set to true) by replacing it with 0, but this character is not used in my pre-trained text embedding and is causing a look up problem. I'm wondering if it's possible to supply a character placeholder parameter or equivalent to resolve the issue (say replace with whitespace instead)

**Comment by marcotcr** [comment]
Fixed in 7bd4f16ab46090ce9a46d5bcdeb5871f9942892c. Pull and install from master, and use the `mask_string=' '` to replace with whitespace.
