### ISSUE TITLE
"Domain error in arguments" exception after lime update

### ISSUE THREAD

**Issue by ptynecki** [marcotcr/lime#352]
Hey,

I updated lime package from lime==0.1.1.34 to lime==0.1.1.35 version. After that LimeTabularExplainer raised ValueError: Domain error in arguments.

```python
explainer = LimeTabularExplainer(
    training_data=X_train.toarray(),
    mode='classification',
    feature_names=feature_names,
    class_names=[0, 1],
    feature_selection='highest_weights',
    random_state=42
)
```

X_train object is a sparse matrix and feature_names is a list of strings.

* Python 3.6.8 x64
* numpy 1.16.4
* scipy 1.3.0

Exception details:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-22-68c347456caa> in <module>
      8     ],
      9     feature_selection='highest_weights',
---> 10     random_state=42
     11 )

/project/env/lib/python3.6/site-packages/lime/lime_tabular.py in __init__(self, training_data, mode, training_labels, feature_names, categorical_features, categorical_names, kernel_width, kernel, verbose, class_names, feature_selection, discretize_continuous, discretizer, sample_around_instance, random_state, training_data_stats)
    214                 self.discretizer = QuartileDiscretizer(
    215                         training_data, self.categorical_features,
--> 216                         self.feature_names, labels=training_labels)
    217             elif discretizer == 'decile':
    218                 self.discretizer = DecileDiscretizer(

/project/env/lib/python3.6/site-packages/lime/discretize.py in __init__(self, data, categorical_features, feature_names, labels, random_state)
    185         BaseDiscretizer.__init__(self, data, categorical_features,
    186                                  feature_names, labels=labels,
--> 187                                  random_state=random_state)
    188 
    189     def bins(self, data, labels):

/project/env/lib/python3.6/site-packages/lime/discretize.py in __init__(self, data, categorical_features, feature_names, labels, random_state, data_stats)
     97             self.maxs[feature] = qts.tolist() + [boundaries[1]]
     98             [self.get_undiscretize_value(feature, i)
---> 99              for i in range(n_bins + 1)]
    100 
    101     @abstractmethod

/project/env/lib/python3.6/site-packages/lime/discretize.py in <listcomp>(.0)
     97             self.maxs[feature] = qts.tolist() + [boundaries[1]]
     98             [self.get_undiscretize_value(feature, i)
---> 99              for i in range(n_bins + 1)]
    100 
    101     @abstractmethod

/project/env/lib/python3.6/site-packages/lime/discretize.py in get_undiscretize_value(self, feature, val)
    136                 scipy.stats.truncnorm.rvs(
    137                     minz, maxz, loc=means[val], scale=stds[val],
--> 138                     random_state=self.random_state, size=self.precompute_size))
    139         idx = self.undiscretize_idxs[feature][val]
    140         ret = self.undiscretize_precomputed[feature][val][idx]

/project/env/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py in rvs(self, *args, **kwds)
    960         cond = logical_and(self._argcheck(*args), (scale >= 0))
    961         if not np.all(cond):
--> 962             raise ValueError("Domain error in arguments.")
    963 
    964         if np.all(scale == 0):

ValueError: Domain error in arguments.
```

**Comment by marcotcr** [comment]
Fixed in 601b7118286eb1d5c444d80f224cc8191e6f7be9, bumped version to 0.1.1.36
Please reopen if this doesn't solve the issue.

**Comment by sunny1072** [comment]
same error I am facing the same issue above with  @marcotcr 's mentioned version as well.

`ValueError                                Traceback (most recent call last)
<ipython-input-95-21f3e0bb7dda> in <module>
      2                      categorical_features=categorical_features,
      3                                                    categorical_names=categorical_names,
----> 4                                                    kernel_width=3, verbose=True,)

~/anaconda3/lib/python3.7/site-packages/lime/lime_tabular.py in __init__(self, training_data, mode, training_labels, feature_names, categorical_features, categorical_names, kernel_width, kernel, verbose, class_names, feature_selection, discretize_continuous, discretizer, sample_around_instance, random_state, training_data_stats)
    214                 self.discretizer = QuartileDiscretizer(
    215                         training_data, self.categorical_features,
--> 216                         self.feature_names, labels=training_labels)
    217             elif discretizer == 'decile':
    218                 self.discretizer = DecileDiscretizer(

~/anaconda3/lib/python3.7/site-packages/lime/discretize.py in __init__(self, data, categorical_features, feature_names, labels, random_state)
    190         BaseDiscretizer.__init__(self, data, categorical_features,
    191                                  feature_names, labels=labels,
--> 192                                  random_state=random_state)
    193 
    194     def bins(self, data, labels):

~/anaconda3/lib/python3.7/site-packages/lime/discretize.py in __init__(self, data, categorical_features, feature_names, labels, random_state, data_stats)
     97             self.maxs[feature] = qts.tolist() + [boundaries[1]]
     98             [self.get_undiscretize_value(feature, i)
---> 99              for i in range(n_bins + 1)]
    100 
    101     @abstractmethod

~/anaconda3/lib/python3.7/site-packages/lime/discretize.py in <listcomp>(.0)
     97             self.maxs[feature] = qts.tolist() + [boundaries[1]]
     98             [self.get_undiscretize_value(feature, i)
---> 99              for i in range(n_bins + 1)]
    100 
    101     @abstractmethod

~/anaconda3/lib/python3.7/site-packages/lime/discretize.py in get_undiscretize_value(self, feature, val)
    141                         minz, maxz, loc=means[val], scale=stds[val],
    142                         random_state=self.random_state,
--> 143                         size=self.precompute_size))
    144         idx = self.undiscretize_idxs[feature][val]
    145         ret = self.undiscretize_precomputed[feature][val][idx]

~/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py in rvs(self, *args, **kwds)
    936         cond = logical_and(self._argcheck(*args), (scale >= 0))
    937         if not np.all(cond):
--> 938             raise ValueError("Domain error in arguments.")
    939 
    940         if np.all(scale == 0):

ValueError: Domain error in arguments.`

**Comment by peggyzhu520** [comment]
I'm experiencing the same error ValueError: Domain error in arguments.
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-45-323289105c16> in <module>()
      1 lime_explainer = lime.lime_tabular.LimeTabularExplainer(x_a_trainp.values, feature_names=x_a_trainp.columns.tolist(),
----> 2                                                     verbose=True,  mode='classification'
      3                                                        ) 

~/anaconda3/envs/python3/lib/python3.6/site-packages/lime/lime_tabular.py in __init__(self, training_data, mode, training_labels, feature_names, categorical_features, categorical_names, kernel_width, kernel, verbose, class_names, feature_selection, discretize_continuous, discretizer, sample_around_instance, random_state, training_data_stats)
    214                 self.discretizer = QuartileDiscretizer(
    215                         training_data, self.categorical_features,
--> 216                         self.feature_names, labels=training_labels)
    217             elif discretizer == 'decile':
    218                 self.discretizer = DecileDiscretizer(

~/anaconda3/envs/python3/lib/python3.6/site-packages/lime/discretize.py in __init__(self, data, categorical_features, feature_names, labels, random_state)
    190         BaseDiscretizer.__init__(self, data, categorical_features,
    191                                  feature_names, labels=labels,
--> 192                                  random_state=random_state)
    193 
    194     def bins(self, data, labels):

~/anaconda3/envs/python3/lib/python3.6/site-packages/lime/discretize.py in __init__(self, data, categorical_features, feature_names, labels, random_state, data_stats)
     97             self.maxs[feature] = qts.tolist() + [boundaries[1]]
     98             [self.get_undiscretize_value(feature, i)
---> 99              for i in range(n_bins + 1)]
    100 
    101     @abstractmethod

~/anaconda3/envs/python3/lib/python3.6/site-packages/lime/discretize.py in <listcomp>(.0)
     97             self.maxs[feature] = qts.tolist() + [boundaries[1]]
     98             [self.get_undiscretize_value(feature, i)
---> 99              for i in range(n_bins + 1)]
    100 
    101     @abstractmethod

~/anaconda3/envs/python3/lib/python3.6/site-packages/lime/discretize.py in get_undiscretize_value(self, feature, val)
    141                         minz, maxz, loc=means[val], scale=stds[val],
    142                         random_state=self.random_state,
--> 143                         size=self.precompute_size))
    144         idx = self.undiscretize_idxs[feature][val]
    145         ret = self.undiscretize_precomputed[feature][val][idx]

~/anaconda3/envs/python3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py in rvs(self, *args, **kwds)
    938         cond = logical_and(self._argcheck(*args), (scale >= 0))
    939         if not np.all(cond):
--> 940             raise ValueError("Domain error in arguments.")
    941 
    942         if np.all(scale == 0):

ValueError: Domain error in arguments.
`
Version:
 lime ==0.1.1.36

**Comment by ronykroy** [comment]
hi there..
Could you try with setting the  discretize_continuous=True parameter to False...
my use case:
newsGroups20 dataset
h20 w2v vectorizer 200 cols
values in the 200 cols after vectorization is almost continuous, going by the name of the parameter
discretize_continuous .. it doesnt make sense to set it to true here..

thats my guess.. a better explanation is welcome though

**Comment by knchanu** [comment]
@ronykroy yes, setting the parameter, discretize_continuous=False solved this issue for me.

**Comment by ArpitSisodia** [comment]
yes, setting the parameter, discretize_continuous=False solved this issue for me.

**Comment by kennysong** [comment]
discretize_continuous=False doesn't work well, since it's hard to interpret the weights without discretizing.

This may be caused if you have missing values in your continuous features. If so, you can try solution two here: #572
