### ISSUE TITLE
Why is StandardScaler called with `with_mean=False`?

### ISSUE THREAD

**Issue by sometimescasey** [marcotcr/lime#358]
Hello! Thanks for providing this package. This isn't a bug, just a question, and apologies if I am missing something obvious - but on line 231 of **lime_tabular.py**, why is StandardScaler() called using `with_mean=False`?

What is the reason that we don't want to subtract the mean when scaling features? Thanks!

**Comment by marcotcr** [comment]
Good question, it is not obvious at all (we should have a comment there).
We never actually use `scaler.transform`, we do the mean centering ourselves [here](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L345) or [here](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L513). Part of the reason for this is that we don't want the scaler to change categorical features, so we set their mean to 0 and scale to 1 [here](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L275).
Setting `with_mean=False` allows the scaler to work on sparse data. It still computes the mean for dense data (which we use in the lines mentioned above).
