### ISSUE TITLE
Neighbourhood Data Creation for LIME text sometimes removes all words from sentence

### ISSUE THREAD

**Issue by Alex-Mathai-98** [marcotcr/lime#360]
Hi, I think I have found an issue with how the neighbourhood data is being generated for given raw text. In **lime_text.py**, from my understanding of the code the way the sentences are created are as follows :

(1) the **number of words** to be replaced for every neighbour is decided by
 `sample = self.random_state.randint(1, doc_size + 1, num_samples - 1)`

(2) then **which words** need to be replaced are decided by 
`inactive = self.random_state.choice(features_range, size,replace=False)`

Now if during (1) the number of words generated is equal to the total number of words in the sentence then by logic of (2) all words will be removed from the sentence as **replace=False**.

This causes a problem, because for classifiers that do not use `<sos>` and `<eos>` before and after sentences, an error is thrown because of an empty input.

Can you please verify if what I am saying is correct ? If not can you suggest why some of the sentences created by LIME are completely empty ?

Thanks a lot for this code. Currently I am on a very tight deadline, a prompt response would greatly help me. 
@marcotcr

**Comment by marcotcr** [comment]
You are correct, but I consider this correct behavior, i.e. I think a classifier should be able to make a prediction when the input is an empty string. Let's say the example we are explaining contains a single word. The only way to check if that word is important for the prediction or if the prediction is driven mainly by the intercept is to remove that word (or replace it with something).

If your model cannot handle empty strings, a workaround would be to wrap the prediction function with something that replaces empty strings with an unknown token, something like:
```
def new_predict_fn(inputs):
  inputs = [x if x else 'UNK' for x in inputs]
  return predict_fn(inputs)
```

**Comment by Alex-Mathai-98** [comment]
Okay, thanks a lot for you response.
