### ISSUE TITLE
[Question]  How to make LIME run faster?

### ISSUE THREAD

**Issue by drjosephliu** [marcotcr/lime#361]
I have a custom diagnosis classifier that takes in a bunch of symptoms as a single string like so: `nausea, vomiting, flu`.  

However running LimeTextExplainer takes almost a minute, which is too long to use in production.

Do you have any advice on how to get the explainer to run faster?

**Comment by dmichelin** [comment]
I'd use [cProfile](https://docs.python.org/2/library/profile.html#module-cProfile) to figure out what specifically is slow in the explanation call. I'd be interested in seeing what the result is.

**Comment by dyanni3** [comment]
One option is to decrease the num_samples parameter when calling explain_instance. Default is 5000, which may or may not be larger than you need.

**Comment by apremgeorge** [comment]
I had the same problem with time, only reducing num_features in model reduced the explainer time, tuning more feature engineering works a bit.
