### ISSUE TITLE
[Question] On toy example

### ISSUE THREAD

**Issue by zhangtj1996** [marcotcr/lime#362]
Hi Marco,
Nice work, on toy example, z' can only take (0,0)(0,1)(1,0)(1,1) since we only have 2 features(x,y axis), I just can't see how the straight line in the plot generated, if you choose z' binary. 
I thought z' is used to express which feature is more important, and I'm comfused by this example.
z and z' are on different domain and I think you shouldn't plot them together.

Best,
Tianjian

**Comment by marcotcr** [comment]
Sorry, I don't understand your question. z' is the representation, the barplot is showing the weights (local linear model) that approximate the black box model on that representation.

**Comment by zhangtj1996** [comment]
![image](https://user-images.githubusercontent.com/13365957/61688561-efe47e80-ad57-11e9-893c-ebd325ccc0c2.png)

I'm actually talking on this picture. Is the dash line here the local linear explainer? I think the domain of local linear explainer should be  ${0,1}^d'$ .

**Comment by marcotcr** [comment]
Ah yes, that is just a toy picture to give intuition. In the paper the interpretable representation is always binary, but LimeTabularExplainer can also be used with non-binary representations (which would give you something like this picture)

**Comment by zhangtj1996** [comment]
Thanks for your response :)
