### ISSUE TITLE
Using LIME with YOLOv2

### ISSUE THREAD

**Issue by Shameendra** [marcotcr/lime#363]
HI i am trying to use LIME on a YOLOv2 trained model. The process i followed is Training my model, then installing LIME then loading my model in Jupyter Notebook, getting results from the model and then trying to use LIME but i get an error wjile trying to run explainer. 

    TypeError: 'list' object is not callable

Can i get some suggestions on where i am going wrong please.

My Code is:

    import cv2
    from darkflow.net.build import TFNet
    import matplotlib.pyplot as plt

    %config InlineBackend.figure_format = 'svg'

    # define the model options and run

    options = {
        'model': 'cfg/yolov2-tiny-9c.cfg',
        'load': 26000,
        'threshold': 0.15,
    
    }

    tfnet = TFNet(options)

      # read the color image and covert to RGB

    img = cv2.imread('C:/darkflow/Augmented Images/Rodenstock_gelb/New Dataset/Rodenstock_Gelb_Lensbags_36.jpg', cv2.IMREAD_COLOR)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # use YOLO to predict the image
    result = tfnet.return_predict(img)

    img.shape

    tl = (result[0]['topleft']['x'], result[0]['topleft']['y'])
    br = (result[0]['bottomright']['x'], result[0]['bottomright']['y'])
    label = result[0]['label']
    confidence = result[0]['confidence']
    
    # add the box and label and display it
    img = cv2.rectangle(img, tl, br, (0, 255, 0), 7)
    img = cv2.putText(img, label, tl, cv2.FONT_HERSHEY_COMPLEX, 1, (0, 0, 0), 2)
    print(result)

The output for print(result) is:

    [{'label': 'Rodenstock_Gelb_Lensbags', 'confidence': 0.19607885, 'topleft': {'x': 190, 'y': 138}, 'bottomright': {'x': 666, 'y': 594}}]

Then i try to use LIME 
    
    from lime import lime_image
    import time

    explainer = lime_image.LimeImageExplainer()

    tmp = time.time()
    # Hide color is the color for a superpixel turned OFF. Alternatively, if it is NONE, the superpixel will be replaced by the average of its pixels
    explanation = explainer.explain_instance(image, result, top_labels=5, hide_color=0, num_samples=1000)
    print(time.time() - tmp)

The error i get is:

    TypeError                                 Traceback (most recent call last)
    <ipython-input-179-cd907a7e352d> in <module>
          1 tmp = time.time()
          2 # Hide color is the color for a superpixel turned OFF. Alternatively, if it is NONE, the superpixel will be replaced by the average of its pixels
    ----> 3 explanation = explainer.explain_instance(image, result, top_labels=5, hide_color=0, num_samples=1000)
          4 print(time.time() - tmp)

    c:\programdata\anaconda3\envs\tensorflow\lib\site-packages\lime\lime_image.py in explain_instance(self, image, classifier_fn, labels, hide_color, top_labels, num_features, num_samples, batch_size, segmentation_fn, distance_metric, model_regressor, random_seed)
        192         data, labels = self.data_labels(image, fudged_image, segments,
        193                                         classifier_fn, num_samples,
    --> 194                                         batch_size=batch_size)
        195 
        196         distances = sklearn.metrics.pairwise_distances(

    c:\programdata\anaconda3\envs\tensorflow\lib\site-packages\lime\lime_image.py in data_labels(self, image, fudged_image, segments, classifier_fn, num_samples, batch_size)
        253             imgs.append(temp)
        254             if len(imgs) == batch_size:
    --> 255                 preds = classifier_fn(np.array(imgs))
        256                 labels.extend(preds)
        257                 imgs = []

    TypeError: 'list' object is not callable       

Can i please get some suggestions on how to proceed furtherr

**Comment by dyanni3** [comment]
You need to pass your model's prediction function in to explainer.explain_instance. Currently you are passing a prediction in, which is a list, and then when LIME tries to treat it as a function you get this "list object is not callable" error.

In other words you should run

`explanation = explainer.explain_instance(image, tfnet.return_predict, top_labels=5, hide_color=0, num_samples=1000)`

**Comment by Shameendra** [comment]
Hi thanks for the  reply. i tried 

    explanation = explainer.explain_instance(image, tfnet.return_predict, top_labels=5, hide_color=0, num_samples=1000)

now i get error 

    ValueError: too many values to unpack (expected 3)

I will try to write a function to unpack 3 values and then try

**Comment by Shameendra** [comment]
@dyanni3 Thanks for the wrapper idea i made a wrapper and it works but i encountered a new problem. I am Opening a new thread for it but this issue was resolved

**Comment by saraswat40** [comment]
@Shameendra could you please share your wrapper function. As far as I can tell Yolo takes in a custom image object in the prediction function ( height, width, channels with image.data of type *float ). lime expects an array. I don't know how to reconcile both.

**Comment by AntMorais** [comment]
I might be missing the point here, but maybe something like this is suitable
```
import cv2
from lime import lime_image

image_to_explain = cv2.imread(img_path)
explainer = lime_image.LimeImageExplainer()
height = 28
width = 28
# input a list of images as ndarray
def lime_classification_function(image_numpy):
    probabilities = []
    for i in range(len(image_numpy)):
        img = image_numpy[i]
        # the yolo prediction function you mentioned
        class_probs = yolo_predict_function(height, width, img)
        probabilities.append(class_probs)
    return probabilities
# here you pass an array with only one image
explanation = explainer.explain_instance(np.array(image_to_explain), lime_classification_function, top_labels=5, hide_color=0, num_samples=1000)
```
I have a [repo](https://github.com/AntMorais/yolime) that does this with Darknet YOLOv4 but it is not documented as of yet.
