### ISSUE TITLE
ValueError: too many values to unpack (expected 3) while trying to run explanation with YOLOv2(Images Basic) 

### ISSUE THREAD

**Issue by Shameendra** [marcotcr/lime#368]
Hi Guys, I am using YOLOv2 to make predictions on images and i used a python wrapper to get desired parameters i.e just the confidence from the YOLOv2 prediction function(tfnet.return_predict) and passing it to the explanation( explanation = explainer.explain_instance(image,tfnet.return_predict, top_labels=5, hide_color=0, num_samples=1000)).

However i get this error:

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-8-544b9939cd9b> in <module>
          1 tmp = time.time()
          2 # Hide color is the color for a superpixel turned OFF. Alternatively, if it is NONE, the superpixel will be replaced by the average of its pixels
    ----> 3 explanation = explainer.explain_instance(image,tfnet.return_predict, top_labels=5, hide_color=0, num_samples=1000)
          4 print(time.time() - tmp)

    c:\programdata\anaconda3\envs\tensorflow\lib\site-packages\lime\lime_image.py in explain_instance(self, image, classifier_fn, labels, hide_color, top_labels, num_features, num_samples, batch_size, segmentation_fn, distance_metric, model_regressor, random_seed)
        192         data, labels = self.data_labels(image, fudged_image, segments,
        193                                         classifier_fn, num_samples,
    --> 194                                         batch_size=batch_size)
        195 
        196         distances = sklearn.metrics.pairwise_distances(

    c:\programdata\anaconda3\envs\tensorflow\lib\site-packages\lime\lime_image.py in data_labels(self, image, fudged_image, segments, classifier_fn, num_samples, batch_size)
        253             imgs.append(temp)
        254             if len(imgs) == batch_size:
    --> 255                 preds = classifier_fn(np.array(imgs))
        256                 labels.extend(preds)
        257                 imgs = []

    C:\darkflow\darkflow\net\flow.py in return_predict(self, im)
         77     assert isinstance(im, np.ndarray), \
         78                                 'Image is not a np.ndarray'
    ---> 79     h, w, _ = im.shape
         80     im = self.framework.resize_input(im)
         81     this_inp = np.expand_dims(im, 0)

    ValueError: too many values to unpack (expected 3)

Can anyone please suggest if i have to Change something in the wrapper or in the Imagess ?

A little background: the prediction function of YOLOv2 is  

    tfnet.return_predict(image)

which returns a Dictionary 

[{'label': 'Rodenstock_gelb', 'confidence': 0.32647023, 'topleft': {'x': 98, 'y': 249}, 'bottomright': {'x': 311, 'y': 455}}]

According to a previous issue i had, and suggestion from @dyanni3 i created a wrapper to Output just the conficence from YOLOv2 predictions. My wrapper is as follows

    def conf_deco(func):
    def wrapper(*args, **kwargs):
        return func(*args, **kwargs)[0]["confidence"]
    return wrapper

    tfnet.return_predict = conf_deco(tfnet.return_predict)

    tfnet.return_predict(image)

Running this on Jupyter Notebook i have the desired Output

    0.32647023

**Comment by marcotcr** [comment]
your prediction function should output a 2d array, where each row has the prediction probabilities for the correspondent input image.

**Comment by jim060** [comment]
Hello @Shameendra ,

Have you found a solution for this issue ? 
I encounter the same difficulty. 

Thank's

Jim

**Comment by Shameendra** [comment]
@jim060 I have nnot had time to implement marcotcr's idea yet but i will try it in coming days. Maybe you can try and hopefully our error can be solved

**Comment by mileseverett** [comment]
@Shameendra 
did you mange to find a solution yet?
