### ISSUE TITLE
TextExplainer with PyTorch

### ISSUE THREAD

**Issue by sathish331977** [marcotcr/lime#370]
I am working on a Multi-class classification on Text ( long length documents  to be identified as a document type, where the document types are at-least 50 types) . The models are build with pytorch, can i use TextExplainer to explain predictions. I did refer to the note book Tutorial - images - Pytorch.ipynb. Is there something similar notebook for text ?

**Comment by marcotcr** [comment]
See [this](https://marcotcr.github.io/lime/tutorials/Lime%20-%20basic%20usage%2C%20two%20class%20case.html) and [this](https://marcotcr.github.io/lime/tutorials/Lime%20-%20multiclass.html)
