### ISSUE TITLE
Is there an explanation for XGBoost regression tasks available?

### ISSUE THREAD

**Issue by akifcinar** [marcotcr/lime#371]
![image](https://user-images.githubusercontent.com/49044721/62452782-2b784300-b771-11e9-8d18-a926e09cd6c3.png)

**Comment by olgakravchenko** [comment]
hey. you need to reshape the output XGBoost classifier gives for Lime to work, it expects an 1d array. The issue is discussed in detail here https://github.com/marcotcr/lime/issues/35
