### ISSUE TITLE
Your model needs to output single-dimensional numpyarrays, not arrays of (5000, 1) dimensions

### ISSUE THREAD

**Issue by SeungJinWang** [marcotcr/lime#377]
I have an error as below. Please help me....

explainer_Lime_one = lime.lime_tabular.LimeTabularExplainer(full_train_npary, mode="regression", feature_names = None, feature_selection = "lasso_path")
Lime_one_model = explainer_Lime_one.explain_instance(full_test_npary[0], model.predict, num_features=5)

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\lime\lime_tabular.py in explain_instance(self, data_row, predict_fn, labels, top_labels, num_features, num_samples, distance_metric, model_regressor)
    288             try:
--> 289                 assert isinstance(yss, np.ndarray) and len(yss.shape) == 1
    290             except AssertionError:

AssertionError: 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-286-cb5b728c4b93> in <module>
----> 1 Lime_one_model = explainer_Lime_one.explain_instance(full_test_npary[0], model.predict, num_features=5)

C:\ProgramData\Anaconda3\lib\site-packages\lime\lime_tabular.py in explain_instance(self, data_row, predict_fn, labels, top_labels, num_features, num_samples, distance_metric, model_regressor)
    290             except AssertionError:
    291                 raise ValueError("Your model needs to output single-dimensional \
--> 292                     numpyarrays, not arrays of {} dimensions".format(yss.shape))
    293 
    294             predicted_value = yss[0]

ValueError: Your model needs to output single-dimensional                     numpyarrays, not arrays of (5000, 1) dimensions

FYI, 
full_test_npary[0].shape
(192,)

type(full_test_npary)
numpy.ndarray

model.summary()
Layer (type)                 Output Shape              Param #   
=================================================================
dense_45 (Dense)             (None, 128)               24704     
_________________________________________________________________
dense_46 (Dense)             (None, 64)                8256      
_________________________________________________________________
dense_47 (Dense)             (None, 32)                2080      
_________________________________________________________________
dense_48 (Dense)             (None, 16)                528       
_________________________________________________________________
dense_49 (Dense)             (None, 1)                 17

**Comment by RekhaChandrasekaran** [comment]
See if this hack works... Write a custom wrapper function around your model predictions, like this.
```   
def custom_regressor(x_test):
    predictions = model.predict(x_test)
    return predictions.reshape(1, -1)
```

And pass this new function to the explainer call.
explainer_Lime_one.explain_instance(full_test_npary[0], **custom_regressor**, num_features=5)

**Comment by shyamrallapalli** [comment]
I had same error and i don't think it is the issue with his model predictions shape ( i could be wrong).
I think lime is passing 5000 (that being the num_samples param in explain_instance) samples but only 1 label.
Just to test this, If pass num_samples=1, then it works. ( i know explanation based on 1 sample is of no value).
I only started reading/using about lime, so will dig more and see if I understand the problem and report further

**Comment by RekhaChandrasekaran** [comment]
I don't think the number of labels matters here, it's a regression model.
As you mentioned, if you pass `num_samples=1`, then the output shape would be (1,1) or (1,) and it fits the shape LIME is expecting.

I believe the workaround I suggested will solve the problem...

**Comment by shyamrallapalli** [comment]
sorry my issue was #35 
my prediction funcation outputs prediction for one sample instead of the list.
please ignore my previoous comment
