### ISSUE TITLE
 LIME for multidimensional images ?

### ISSUE THREAD

**Issue by sgalopinIGN** [marcotcr/lime#378]
I work with 5d images (RVB + IR (infrared) + Height) for aerial images segmentation...
![peupleraies_431659_6514780](https://user-images.githubusercontent.com/36155393/63869956-4f6a2580-c9b9-11e9-8c93-94a8f2adc7e1.jpg)

**Comment by marcotcr** [comment]
Ugh, sorry, I don't know what a good interpretable representation or perturbations would be for those.
