### ISSUE TITLE
Duplicating Jupyter Notebook with LIME explanation freezes Jupyter Lab

### ISSUE THREAD

**Issue by dillonm** [marcotcr/lime#379]
Whenever I try and copy/paste or duplicate a jupyter notebook that has the output from `show_in_notebook()`, jupyter labs will freeze upon trying to open the new file.  It will remain frozen even after restarting jupyter lab via the terminal, due to the file attempting to be brought up immediately.  Deleting the file and then starting jupyter lab from a different directory fixes the freezing issue.  Clearing the output from the cell containing the `show_in_notebook()` call allows the file to be copied again like normal.

**Comment by frankwxu** [comment]
I have the exact problem. You can reload the page. It will show the graph. But it bugs me. I am using colab.

**Comment by marcotcr** [comment]
Yeah, when I wrote the javascript code I didn't even know that JupyterLab existed. I would have done it differently, but now I unfortunately don't have the bandwidth to fix it.
Sorry!
