### ISSUE TITLE
binary classification? (and grayscale images)

### ISSUE THREAD

**Issue by bradshawuw** [marcotcr/lime#385]
What should be the input to explain_instance() for the labels parameter for a binary classification problem? I tried labels=(0,) and it worked, but the results were nonsense.

Also, for those working with grayscale images, I found that if your model expects input dimensions of (Nbatch, Nx, Ny, 1), you need to pass explain_instance() images of shape (Nx, Ny, 3) which can be done using gray2rgb. You also need to pass it a custom function (instead of model.predict):

def predict(images):
    images = images[:,:,:,1]
    images = images[...,np.newaxis]
    return model.predict(images)

**Comment by marcotcr** [comment]
`labels=(0,)` will give you an explanation for label 0, which is confusing because it gives you the opposite of what you would expect. In binary classification the default `labels=(1,)` is a good choice

**Comment by marcotcr** [comment]
Check out the answer to #161. Please reopen if it doesn't fix your problem.
