### ISSUE TITLE
What does it mean if explaining image instance is entirely green?

### ISSUE THREAD

**Issue by Zhunaidm** [marcotcr/lime#386]
Hi, I've used Lime on a pytorch CNN model trained on the MNIST dataset.
The problem I'm having is that it works fine for most instances where it properly displays the boundaries but on certain predictions the following code:

temp, mask = explanation.get_image_and_mask(explanation.top_labels[0], positive_only=True, num_features=5, hide_rest=False)
img_boundry1 = mark_boundaries(temp/255.0, mask)
plt.imshow(img_boundry1)

would just show the base image and setting positive_only to False makes the entire image green with no boundaries.

Am I doing something wrong? It works for some images and others have this issue

**Comment by marcotcr** [comment]
Check `explanation.local_exp`, I'm guessing the segmentation function is probably not segmenting the image into more than 5 superpixels.
