### ISSUE TITLE
UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.

### ISSUE THREAD

**Issue by whyisyoung** [marcotcr/lime#388]
Hi,

I'm using LIME to explain a dataset with about 645 categorical features. I used ~2600 samples for training and ~1300 samples for testing. I used LimeTabularExplainer to explain a single instance.

**I guess the default `num_samples=5000` is too big for my case, is it right?**
So I changed it to 32 or 500, then I got either one of the following warning:

```
1. /python3.6/site-packages/sklearn/linear_model/ridge.py:189: UserWarning: 
Singular matrix in solving dual problem. Using least-squares solution instead.
2. /python3.6/site-packages/sklearn/linear_model/ridge.py:187: 
LinAlgWarning: Ill-conditioned matrix (rcond=2.15906e-18): result may not be accurate.
  overwrite_a=False)
```

I'm using OS X 10.14.6, Python 3.6.5, sklearn 0.21.3, LIME 0.1.1.36.

Any suggestions would be appreciated : )

**Comment by marcotcr** [comment]
It doesn't sound like 5000 is too big for your case, since you have so many categorical features. The warning is saying that you have less instances than features, not a good thing for ridge regression (which is what we are using).
