### ISSUE TITLE
LimeTabularExplainer is not consistent. Does not set random_state in discretizer. 

### ISSUE THREAD

**Issue by prempiyush** [marcotcr/lime#389]
I know there are issues like #67 et al that focus on LIME being consistent and repeatable. 

However, this is different.

This snippet when called multiple times, setting random_state in class, does not guarantee same results.

```
explainer = lime.lime_tabular.LimeTabularExplainer(X_train, feature_names=feature_names, random_state=10, mode='regression')
exp = explainer.explain_instance(X_test[10], final_model.predict)
``` 

This is because LimeTabularExplainer is not setting this `random_state` in any of the discretizers. Resulting in the perturbed samples to be different every time. 

@marcotcr If you agree with the solution of passing `random_state` to the discretizers, I can quickly raise a PR. 

Thanks.

**Comment by marcotcr** [comment]
You're right, thanks for noticing this. The PR should be quite simple, as the discretizers already have the random_state parameter (we're just not using it). If you're willing, go ahead and submit it : )
