### ISSUE TITLE
LIME Tabular is not able to generate explanations

### ISSUE THREAD

**Issue by prempiyush** [marcotcr/lime#391]
LIME tabular is failing to generate explanation for a regression problem on our dataset.  For any data point, it just generates an explanation where all feature weights are zero.. the local prediction is equal to local intercept in the range of ~5.45

Dataset Used: 
[ProblemDataset.csv.zip](https://github.com/marcotcr/lime/files/3743384/ProblemDataset.csv.zip)

Notebook Used: 
[Lime Explanation Issue.ipynb.zip](https://github.com/marcotcr/lime/files/3744007/Lime.Explanation.Issue.ipynb.zip)

Observations:

1. The problem is likely in feature_selection `highest_weights` method which is the auto method when num_features > 6. I tried using this feature_selection for num_features < 6, and still got the same result

2. The feature_selection `forward_selection` method which is the auto method when num_features <=6 works well. It also works well for num_features > 6. 

3. The attached notebook shows a simple RandomRegressor model. However, the model is most likely of no consequence. I saw the same issue in an XGBoost Regressor too.

4. This issue looks similar to the one mentioned here 
https://github.com/marcotcr/lime/issues/243#issuecomment-509499641
> Thanks for the reply,
> Actually i cant share the dataset, sorry for that,
> Also if i go for 10 features i get zeros.., it works upto 6 features.

@marcotcr Do let me know if you need anything else to recreate the issue. Thanks.

**Comment by marcotcr** [comment]
Thanks for providing the full example. I'm quite busy these days, but I'll try to look into this as soon as possible!

**Comment by marcotcr** [comment]
Thanks, the example was really helpful. Fixed in 305b55b. It was indeed a bug in feature selection, but a tricky one that would only manifest if the number of features was large enough w.r.t. the number of samples.
