### ISSUE TITLE
Same Input, Different Explanation

### ISSUE THREAD

**Issue by rahimentezari** [marcotcr/lime#392]
Thanks for your code.
I used LIME in Tensorflow for MNIST. Why the same input for explanation e.g. "7" has different explained outputs? I run this code several times, and each time the image from explanation has minor differences with others. Is this because each time we have different num_samples=1000 ? If yes how can we fix these samples? I also tried this solution https://github.com/marcotcr/lime/issues/67 , but still get different outputs for the same input.

    explainer = LimeImageExplainer()
    explanation = explainer.explain_instance(test_d['features'][0].astype('float32'), predict_proba,
                                             top_labels=10, num_samples=1000,
                                             random_seed=42)
    temp, mask = explanation.get_image_and_mask(explanation.top_labels[0], positive_only=True, num_features=5, hide_rest=True)
    plt.imsave('MNIST_LIME.png', mark_boundaries(temp / 255, mask))

    explainer = LimeImageExplainer()
    def explain(instance, predict_fn, top_labels, num_samples):
        np.random.seed(16)
        return explainer.explain_instance(instance, predict_fn, top_labels, num_samples)

    explanation = explain(test['features'][0].astype('float32'), predict_proba, top_labels=1, num_samples=1000)
    temp, mask = explanation.get_image_and_mask(explanation.top_labels[0], positive_only=True, num_features=5, hide_rest=True)
    plt.imsave('MNIST_LIME.png', mark_boundaries(temp / 255, mask))

**Comment by marcotcr** [comment]
Sorry. Try calling `explainer.random_state.seed(1)` instead of `np.random.seed(16)`, reopen if it doesn't fix it (it should)
