### ISSUE TITLE
submodular pick with ImageExplainer

### ISSUE THREAD

**Issue by DeeperDeeper** [marcotcr/lime#395]
Submodular_pick cannot run on LimeImageExplainer() because it does not have a mode attribute

 `AttributeError: 'ImageExplanation' object has no attribute 'mode'` by running the  `submodular_pick.SubmodularPick` on `explainer = lime_image.LimeImageExplainer()`

**Comment by marcotcr** [comment]
It can't run for a deeper (=]) reason: the features used on image explanations are not comparable across instances. A superpixel on an image is not the same as a superpixel on another, and thus we can't get a measure of how important a feature is across the dataset.
