### ISSUE TITLE
SVM explain_instance predict_proba sklearn alternative

### ISSUE THREAD

**Issue by naf3a** [marcotcr/lime#396]
Hi guys,

First, thank you for your amazing job.

I would like to know if you can recommand a way to explain prediction on text data without using `predict_proba`.

Indeed, [SVC](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html) and [OneClassSVM](https://scikit-learn.org/stable/modules/generated/sklearn.svm.OneClassSVM.html) are `scikit-learn` models than can be used to perform classification.  

But both doesn't implement `predict_proba` method.

> Not a native speaker, please forgive me If I did english mistakes.

**Comment by marcotcr** [comment]
Yes, you can just use the predict fn as long as you wrap it so that it is a 2d np array (even if the second dimension has length 1). You can do it like the following, and use `new_predict` when getting explanations:
`new_predict = lambda x: model.predict(x).reshape(-1, 1)`
