### ISSUE TITLE
Implementation with KerasClassifier

### ISSUE THREAD

**Issue by fredylg** [marcotcr/lime#397]
Hi
 I am trying to run a explainer on a Classifier and I am getting the error 

 File "/usr/local/lib/python3.7/site-packages/keras/wrappers/scikit_learn.py", line 228, in predict
    proba = self.model.predict(x, **kwargs)
AttributeError: 'KerasClassifier' object has no attribute 'model'

Is it even possible??  my code below

PS thanks for any help

`
import numpy
import pandas
import tensorflow
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing

import lime
import lime.lime_tabular

min_max_scaler = preprocessing.MinMaxScaler()

seed = 7
numpy.random.seed(seed)

#Read data
df = pandas.read_csv("./canada.csv", sep=",", header='infer')
df.head()

dataset = df.values
X = dataset[:, 0:-1] ##ALL DATA
Y = dataset[:, -1]	#choice
X = min_max_scaler.fit_transform(X)

explainer = lime.lime_tabular.LimeTabularExplainer(dataset, feature_names=df.columns, class_names='choice', discretize_continuous=True)

#Convert categories to one hot encoded
categ_Y = np_utils.to_categorical(Y)

def baseline_model():
	#Create model
	model = Sequential()
	model.add(Dense(10, input_dim=X.shape[1], activation='relu'))
	model.add(Dense(8, activation='relu'))
	model.add(Dense(6, activation='relu'))

	model.add(Dense(8, activation='relu'))
	model.add(Dense(categ_Y.shape[1], activation='softmax'))
	#Compile model
	model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

estimator = KerasClassifier(build_fn=baseline_model, epochs=13, batch_size=10, verbose=1)
kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
results = cross_val_score(estimator, X, categ_Y, cv=kfold)
print("Accuracy: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

i = 25
exp = explainer.explain_instance(dataset[i], estimator.predict, num_features=5)

`

**Comment by DeeperDeeper** [comment]
This error has no relation with Lime. It is about your KerasClassifier implementation. Check ig KerasClassifier class has an attribute model ?!

**Comment by fredylg** [comment]
@DeeperDeeper Thanks for your help, I think whats going on is Lime assumes the object Model is set on the  KerasClassifer, below error details

`Traceback (most recent call last):
  File "/\canada_3layer.py", line 55, in <module>
    exp = explainer.explain_instance(dataset[i], estimator.predict, num_features=5)
  File "/usr/local/lib/python3.7/site-packages/lime/lime_tabular.py", line 352, in explain_instance
    yss = predict_fn(inverse)
  File "/usr/local/lib/python3.7/site-packages/keras/wrappers/scikit_learn.py", line 228, in predict
    proba = self.model.predict(x, **kwargs)
AttributeError: 'KerasClassifier' object has no attribute 'model'`
