### ISSUE TITLE
lime_image not consistent with lime_tabular classification

### ISSUE THREAD

**Issue by rafikg** [marcotcr/lime#399]
@marcotcr I see that in lime_tabular classification mode the explanation return a `exp.predict_prob`. However, in the case of lime_image, the explanation does not have predict_prob! I think to be consistent, we should add this to lime_image. Thanks

**Comment by marcotcr** [comment]
That is in lime_tabular for visualization purposes. If you think this is particularly important, please comment here explaining why and submit a one liner pull request
Thanks : )
