### ISSUE TITLE
Cannot open HTML file created by Explain Instance in Python

### ISSUE THREAD

**Issue by LuckyRathod** [marcotcr/lime#401]
I have a created a model and used Lime Explanation and Created HTML File
`res = exp.save_to_file('Output.html')`
Now in Django i want to render these HTML File
But Below error is shown
`Could not parse the remainder: '([\s\S]+?)' from '([\s\S]+?)'
Error on Line No 24811 in Html

**Comment by marcotcr** [comment]
Can you open the HTML file on your computer? I'm guessing it's because that HTML file has a ton of embedded javascript, and Django may not like that? Please reopen if that is not the case.
