### ISSUE TITLE
Features not displayed correctly when using explain_in_notebook

### ISSUE THREAD

**Issue by mortenoosvik** [marcotcr/lime#404]
Hi, Marco Tulio Ribeiro!

I've implemented your LIME framework but the output does not look right. 

![Screenshot 2019-11-20 at 16 08 32](https://user-images.githubusercontent.com/33130876/69250518-16a0ad80-0bb0-11ea-84ff-e3d78e20e356.png)

I've tried running it in both Chrome and Safari with the same result. LIME was installed using `pip install lime`.

There was a similar issue: [Issue 88](https://github.com/marcotcr/lime/issues/88). I tried the proposed solution without any luck. I've also tried `save_to_fig` but it produces the same plot.

**Comment by marcotcr** [comment]
I think #88 was actually a bug, but I don't see the problem in this case. We do have to truncate feature names when they are too long.
Please reopen if I'm missing something.
