### ISSUE TITLE
pretrained pickled models

### ISSUE THREAD

**Issue by alexlaurence** [marcotcr/lime#405]
Sorry for the incredibly stupid question, but does LIME / Anchors work on pretrained (i.e. pickled) models?

**Comment by manujosephv** [comment]
It ideally should as long as you have access to the train dataset, or atleast the stats of the trained dataset.

**Comment by marcotcr** [comment]
You only need access to a function that takes instances and outputs prediction probabilities. If you are using lime tabular, you do need to provide some statistics so we know how to perturb data.
