### ISSUE TITLE
Is not compatible with the output of Keras models for regression

### ISSUE THREAD

**Issue by vd1371** [marcotcr/lime#408]
Hi,

Line 351, if the predict_fn is a keras model for regression, the output shape would be (5000, 1). Then this will raise an error in line 381.

My suggestion:

           try:
                 if len(yss.shape) != 1 and len(yss[0].shape) == 1:
                        yss = np.array([val[0] for val in yss])
                 assert isinstance(yss, np.ndarray) and len(yss.shape) == 1
            except AssertionError:
                raise ValueError("Your model needs to output single-dimensional \
                    numpyarrays, not arrays of {} dimensions".format(yss.shape))

**Comment by marcotcr** [comment]
Thanks, added to 8b72193
