### ISSUE TITLE
Choose fix for missing `__init__()` documentation

### ISSUE THREAD

**Issue by proinsias** [marcotcr/lime#41]
When reading the [documentation](https://lime-ml.readthedocs.io/en/latest/lime.html#lime.lime_tabular.LimeTabularExplainer) for LimeTabularExplainer, I noticed that there was no explanation of the function's arguments. 

After a bit of digging, I realized that these arguments are documented in the `__init__()` function in the source code, but that this function's documentation is not included by `Sphinx` by default.

StackOverflow gives a couple of [fixes](https://stackoverflow.com/questions/5599254/how-to-use-sphinxs-autodoc-to-document-a-classs-init-self-method) for this.

**Comment by marcotcr** [comment]
It's fixed.
Thanks!
