### ISSUE TITLE
Slicing through pandas dataframe not working even after using iloc

### ISSUE THREAD

**Issue by Shameendra** [marcotcr/lime#412]
Hello everyone,
I have trained my dataset with XGBoost classifier and used Pandas dataframe directly as Input data. 
the Code is as follows:

    #Read csv file and prepare Input and Target columns
    df = pd.read_csv('Broken.csv', encoding='ISO-8859-1', sep=',') 
    X = df5.drop(['C'], axis=1)  #Input column, dropping the target column
    y = df5['C']  #Target column

    #split test and Train dataset
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
    
    #Train using XGBoost classifier
    from xgboost import XGBClassifier
    xg = XGBClassifier()
    xg.fit(X_train, y_train)

after Training i am trying to use LIME to slice through the dataframe. I am using the iloc command but still i get an error : 

    TypeError: '(slice(None, None, None), 0)' is an invalid key

My Code is as follows:

    prepare feature names for LIME Tabular explainer
    columnsNamesArr = (X).columns.values   #get column names from df
    listOfColumnNames = list(columnsNamesArr) #convert it to a list

    #Column used as target
    breakage = df5['C'].values   # get target values to be used in LIME tabular explainer

    #LIME explainer  
    explainer =lime.lime_tabular.LimeTabularExplainer(X_train.iloc[:,:], feature_names=listOfColumnNames, class_names=breakage,verbose=True, mode='classification')

which gives the error : 
 
    TypeError: '(slice(None, None, None), 0)' is an invalid key

Can anyone suggest where i am going wrong ?

**Comment by marcotcr** [comment]
Can you please check that:
-  `X_train.iloc[:,:]` is a 2d numpy array
- `listOfColumnNames` is a list of strings
- `class_names` is a list of strings
