### ISSUE TITLE
Lime Not Capturing Categorical Features Well

### ISSUE THREAD

**Issue by hiyam97** [marcotcr/lime#415]
Hello, in my dataset, I have a mix of categorical and nuremerical features, and I'm tackling a regression problem.

I specified through the explainer the indices corresponding to the ```categorical_features```, as well as the ```categorical_names``` as follows:

```
explainer = lime.lime_tabular.LimeTabularExplainer(X_train, feature_names=columns_names, 
                                                   categorical_features=[14,15,16,17,18,19,20],
                                                   categorical_names=['mohafaza_B', 'mohafaza_N', 'mohafaza_NE',
                                                                        'service_General Medicine', 'service_Pediatrics',
                                                                        'service_Gynaecology', 'service_Pharmacy'],
                                                   verbose=True, mode='regression')
i = 20
model = Ridge()
model.fit(X_train, y_train)
np.random.seed(21)
exp = explainer.explain_instance(X_test[i], model.predict, num_features=21)
exp.show_in_notebook(show_table=True)
```

However, in the tabular representation, the categorical column of the particular instance that is labeled 0 as well as the one labeled 1 are both being considered ```True```. Please find the image below:
![Screenshot (389)](https://user-images.githubusercontent.com/35295550/71812705-901d2e00-3080-11ea-9072-a31311434f94.png)

Am I doing anything wrong ?

Thanks in advance.

**Comment by marcotcr** [comment]
`categorical_names` should be a dictionary from int to list of names, where `categorical_names[x][y]` represents the name of the yth value of column x.  Take a look at [this](https://marcotcr.github.io/lime/tutorials/Tutorial%20-%20continuous%20and%20categorical%20features.html) tutorial.
