### ISSUE TITLE
Size of lime installation

### ISSUE THREAD

**Issue by PawelFaron** [marcotcr/lime#417]
Hello,
The only class I'm using from lime is LimeTextExplainer. I'm trying to fit it into AWS lambda limitation which is 250 mb. Lime alone with all dependencies has this size. Do you know maybe a way how to shrink it?

**Comment by marcotcr** [comment]
lime itself is quite small (the egg is less than 400kb). I don't know which of the dependencies are large (I'm guessing skimage, maybe scipy?). One thing you could do is install it with only the dependencies you need (e.g. remove skimage if you're not using LimeImageExplainer).
