### ISSUE TITLE
ValueError: Found unknown categories [...] in column 0 during transform

### ISSUE THREAD

**Issue by ispmarin** [marcotcr/lime#418]
Hi there,

I´m trying to use the table explainer on categorical data and I have a highly dimensional dataset, so I have to take a sample out of the dataset. I fit the Label encoder and the One Hot encoder on the entire dataset, and try to fit it, but I´m getting the error

```
cat_feat = ['feat_1', 'feat_2', 'feat_3']
df_sample = df_m.sample(1000)
labels = df_sample.discreas
df_cat = df_sample[cat_feat].copy()
df_cat.fillna('NA', inplace=True)

categorical_names = {}
for feature in cat_feat:
    le = LabelEncoder().fit(df_m[feature].fillna('NA'))
    df_cat[feature] = le.transform(df_cat[feature])
    categorical_names[feature] = le.classes_

df_cat = df_cat.astype(float)

one_hot_encoder = OneHotEncoder(categories='auto').fit(df_m[cat_feat].fillna('NA'))
X_train, X_test, y_train, y_test = train_test_split(df_cat, labels)


encoded_train = one_hot_encoder.transform(X_train)

mdl_c = RandomForestClassifier(n_jobs=-1, n_estimators=200)
mdl_c.fit(encoded_train, y_train)

predict_fn = lambda x: mdl_c.predict_proba(one_hot_encoder.transform(x))

explainer = lime.lime_tabular.LimeTabularExplainer(X_train.values ,
                                                   #class_names=labels, 
                                                   feature_names = cat_feat,
                                                   categorical_features = len(df_cat),
                                                   categorical_names=categorical_names
                                                  )
exp = explainer.explain_instance(X_test.values[0], predict_fn)
exp.show_in_notebook()

ValueError: Found unknown categories [0.0, 1.0, 9.0, 12.0, 15.0, 17.0, 26.0, 27.0, 28.0, 29.0, 37.0, 48.0, 49.0, 51.0, 52.0, 53.0, 55.0, 56.0, 57.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0] in column 0 during transform

```

Any idea on what´s going on? Thanks

**Comment by marcotcr** [comment]
`categorical_features` should be a list of integers (ids), not an integer

**Comment by ispmarin** [comment]
Fixed with `range(len(df))`, as all columns are categorical features, same error appears.

**Comment by marcotcr** [comment]
Your encoder is trained on `df_m[cat]` (which I'm guessing is continuous), while `X_train` is categorical. LimeTabularExplainer is perturbing the categorical features, resulting in values that your encoder has never seen (because it was trained on the wrong data).

**Comment by marcotcr** [comment]
Try training your encoder on `df_cat` instead

**Comment by adamrain01** [comment]
> 

Hay can you explain how you fix this problem, because i have same problem like this. . Thx

**Comment by MRB-2020** [comment]
This problem is due to infrequent categorical cases. Thus, there are cases in test which weren't present in the train when the test_train_split happened.

OneHotEncoder(categories='auto', handle_unknown = 'ignore') might to the trick.
