### ISSUE TITLE
How does LIME choose it local ?

### ISSUE THREAD

**Issue by thuybt** [marcotcr/lime#419]
Dear Marco, 
I have read your paper and use LIME to explain my model in Kaggle Default Risk competion data, and encounter some struggle as following: 
1. How can LIME choose or calculate  πx(z)? Please refer your source code that is related to this part?
2. How can LIME divide group of each variables in its explanation?
Please help me address these issue, thank you in advance

**Comment by thuybt** [comment]
![explain mar](https://user-images.githubusercontent.com/59462501/72045797-8fd39b80-32e9-11ea-82f9-37ed5c6e8682.PNG)

**Comment by marcotcr** [comment]
Pi: [here](https://github.com/marcotcr/lime/blob/master/lime/lime_base.py#L182)
Definition: [here](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L246)

By group, I assume you mean the fact [that we are discretizing continuous variables](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L214).
