### ISSUE TITLE
Clarification: What does the number mean in explanations?

### ISSUE THREAD

**Issue by joschjava** [marcotcr/lime#421]
![grafik](https://user-images.githubusercontent.com/35228356/72205882-32c21c00-3488-11ea-8aea-be784f0dc9c7.png)
In this graphic what does the 0.26 actually mean in odor=foul? I assume it's a probability. How do the individual values contribute to the final explanation? If edible is 0.00, how can there be gill-size=broad of 0.13 which should increase the probability of edible?

Thank you!

**Comment by marcotcr** [comment]
[This ](https://marcotcr.github.io/lime/tutorials/Tutorial%20-%20continuous%20and%20categorical%20features.html#Explaining-predictions)section of the tutorial explains it.
