### ISSUE TITLE
'Numpy.ndarray' object is not callable

### ISSUE THREAD

**Issue by arindam44** [marcotcr/lime#423]
I am trying to initiate an explainer like
explanation = explainer.explain_instance(df_test.iloc[i], mlp.predict_proba(df_test))
Here df_test is a dataframe of shape (49, 687)
Please help!!

**Comment by SMILElikeJONNY** [comment]
I have the same issue.

**Comment by marcotcr** [comment]
the second parameter of `explain_instance` shoudl be `mlp.predict_proba`, not `mlp_predict_proba(df_test))`
