### ISSUE TITLE
Right input for explain_instance

### ISSUE THREAD

**Issue by intelliGait** [marcotcr/lime#424]
Dear Marco,

I experimented with your [Keras tutorial](https://github.com/marcotcr/lime/blob/master/doc/notebooks/Tutorial%20-%20Image%20Classification%20Keras.ipynb) but instead of using the InceptionV3 I used a VGG16 model. 

In order to read the image, which should be used for explanations i ran follwing lines:

```
IMAGE_PATH = '../cat.jpg'
img_org = image.load_img(IMAGE_PATH, target_size=(224, 224))
img = image.img_to_array(img_org.copy())
img = np.expand_dims(img, axis=0)
img = preprocess_input(img)

```
Furthermore I wanted to test different Segmentation algorithms and started with your default approach and settings for quickshift:

```
from lime.wrappers.scikit_image import SegmentationAlgorithm
segmentation_quick = SegmentationAlgorithm('quickshift', kernel_size=4, max_dist=200, ratio=0.2, random_seed=42)
```

The segmentation results for the original image and the VGG preprocessed image are significantly different:
![LIME](https://user-images.githubusercontent.com/47107686/73160591-b49d8080-40e9-11ea-8897-1ed654e26792.png)
 
There is of course also a difference in the explanations when i call the explanaition function _explain_instance_ with the original and the preprocessed image.

`explanation = explainer.explain_instance(img[0], model.predict, top_labels=3, hide_color=0, num_samples=10000, segmentation_fn=segmentation_quick)`

vs

`explanation = explainer.explain_instance(img_org, model.predict, top_labels=3, hide_color=0, num_samples=10000, segmentation_fn=segmentation_quick)`

In your tutorial you provided the preprocessed image as parameter for _explain_instance_ which is reasonable because you need the predictions from model.predict on that one. I think there is a problem regarding the VGG preprocessed image and the segmentation algorithms. Could you describe the correct workflow?

Kind regards

**Comment by marcotcr** [comment]
I think the easiest thing to do here would be to fold the preprocessing into the predict_fn, something like:
```
def new_predict(xs):
  return model.predict(preprocess_input(xs))
```
And just using the original image, for which the segmentation is reasonable.
Sorry for the delay in responding!
