### ISSUE TITLE
Explain a linear regression model

### ISSUE THREAD

**Issue by titecher** [marcotcr/lime#427]
To understand how LIME explains the model, I tried to apply this to a simple linear regression model.
The artificial data is as follows,
 x_i =np.random.random(1000);
 y_i = -3*x_1-1.5*x_2+0*x_3+1.5*x_4+4*x_5+6*x_6+ 1*(np.random.random(1000)-0.5)

then I fitted this by LightGBM and used LIME to explain the model. LightGBM is well-fitted on this data, R^2=0.97. Then, LIME says the following output.
Intercept 3.3205477174765647
Prediction_local [2.11415409]
Right: 1.9567157008087541
![image](https://user-images.githubusercontent.com/40323207/73613900-764e1700-463d-11ea-93f8-86556cfa5c0d.png)

Why are not the values of feature contribution the same values of the coefficient of the artificial data? The ratio seems same as them.

**Comment by marcotcr** [comment]
Sorry, this is poorly documented, but the weights are actually relative to scaled data. See #189
