### ISSUE TITLE
explain_instance_with_data

### ISSUE THREAD

**Issue by elsharifali** [marcotcr/lime#431]
Do you have a working example that demonstrates the use of **explain_instance_with_data** to generate the R^2 score?

Thanks.

**Comment by Leponka** [comment]
@elsharifali Did you find any example? I also trying to find one.

**Comment by spook95** [comment]
What I'm i trying to find ?

**Comment by Leponka** [comment]
@spook95 
I am trying to find a working example that demonstrates the use of explain_instance_with_data

**Comment by whtitefall** [comment]
> @spook95
> I am trying to find a working example that demonstrates the use of explain_instance_with_data

Hi, did you figure this out? I can't find any examples either
