### ISSUE TITLE
Hide color

### ISSUE THREAD

**Issue by palatos** [marcotcr/lime#433]
I was wondering if there is a methodical way of choosing the hide_color option for Image explanations.
I noticed changing it can influence the results of the explanation a bit, so I was wondering if there is a specific way of knowing the best color.

Also when an image is pre-processed to some weird color scale (as is the case with some models that use the average or standard deviation of the data as references), I'm not sure how to choose the color.

Let's say I have an image mapped to values between [-120,113] instead of the usual [0,255], [0,1], [-1,1] scales. Could I reasonably pass hide_color = -120 for instance, expecting that to be the equivalent of "black" in this color space, for the purposes of generating explanations?

Thanks for any clarifications, and once again for this great resource you're maintaining.

**Comment by marcotcr** [comment]
I guess one option is to leave it as `None`, in which case the `hide_color` becomes the average color of the superpixel (I think this is the most general-purpose option).

It does change the explanation, as you would expect: if you use white, you get perturbed images that are much lighter than if you use black. For some models, you get weird correlations, e.g. if you use gray the model things there are candles in the image for some reason.

You are right that preprocessing alters this - in that case, maybe the best thing to is to fold the preprocessing function into the predict_fn, and using the original image as input to LIME (then you don't have to figure out color mappings)
