### ISSUE TITLE
Dealing with numerical integer feature

### ISSUE THREAD

**Issue by xuyangela** [marcotcr/lime#434]
In my data set, I have integer features, such as week of year. I want to use it numerical and at the same time, it is integer. In LIME sampling, it generates float numbers for all numerical features (if I understand it correctly). Can I limit it to sample from existing integers?

**Comment by marcotcr** [comment]
Sorry, you'd have to write a custom explainer (you can copy TabularExplainer and change [this](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L469))
