### ISSUE TITLE
The most important features used in LIME explanations

### ISSUE THREAD

**Issue by Dola47** [marcotcr/lime#436]
Hello All,

I am working on Tabular data, I gather my data in a single batch, after doing some preprocessing on my data. I get the explanation of each single instance. I have more than 40k instance. I am asking if there is way to know which features are the most important ones, and used frequently in the explanation of each single instance? I want to find out which features are the most important ones in the explanations over the whole instances?

Is there is a way to generate a graph or a plot the represent the most important features used in the explanations of the whole explained instances?

Is that possible?

**Comment by marcotcr** [comment]
Check out lines[ 99-108 of submodular pick](https://github.com/marcotcr/lime/blob/master/lime/submodular_pick.py#L99), where we are creating an instance-feature matrix. W there is the squareroot of the sum of feature importances (a measure of importance), but you could also do the number of rows that are non-zero in a column, etc.

**Comment by Dola47** [comment]
@marcotcr  That is was not my main aim, but thanks a lot to mention that.

However, I am asking if there is a way that allow me to find some very important features that will be common between specific different instance out of my batch that need to be explained. 

To be more precise,  I have several instances in my batch.  I need only to explain some specific instance out of my batch. Moreover, I need to find if there are some common features that contribute the most in all of these instances. 

Is there is a way that allow me to find out the most important common features between different instance? Because, I am always getting different features used in the explanation for each different instance.

**Comment by Dola47** [comment]
@marcotcr That is a completely different question to the title of the question, but because you mentioned Submodular LIME, I have some weirdness with understanding the results out of submodular LIME. I have found out that submodular LIME is not following our model probabilities as the normal LIME do. So, I have an instance that is expected by the model to be classified as class zero, However, submodular LIME present the explanation that it is classified to class 1.

**Comment by marcotcr** [comment]
The code that I linked to aggregates the explanation weights of multiple instances, per feature. The columns of the W matrix in that code are features, while the rows are samples in your batch. If you want to know which features contribute the most, you would do the sum of feature importances.

**Comment by Dola47** [comment]
@marcotcr  The sum of the feature importances is actually done in line 108? Am I right?

Then I can just modify this code a little a bit, such that the rows of the W matrix is the samples I am only interested in, and do the sum of the features importance as well, and by that I have achieved my goal. Is that correct?

**Comment by marcotcr** [comment]
Yes, line 108. Instead of using specific rows of W, you can just pass the instances of interest as input (`data`) and set `method='full'`

**Comment by Dola47** [comment]
@marcotcr  Thanks a lot it is clear for me now. However, can I also access the importance varaible?
Or, I can just have a look from the explanations that will be displayed for each of the instances passed?

**Comment by marcotcr** [comment]
You can't access that variable, you'll have to copy the code and modify it.

My guess is you're running submodular lime with the default `method='random'`, such that you are generating explanations for 1000 random examples (and thus the indices do not match your original dataset)

**Comment by Dola47** [comment]
@marcotcr  I think you mean that I was running the `method='random'`
