### ISSUE TITLE
total probability is greater than  1. and weights are not adding to the class probability values.

### ISSUE THREAD

**Issue by raammishra** [marcotcr/lime#438]
Hi everyone,

I am getting an issue with Lime Text Explainer.
I am testing lime on Multilabel classification model . I know that the probabilities  will not converge to 1. But how to interpret the results. 
 below is the o/p i am getting.

![image](https://user-images.githubusercontent.com/56956579/77041601-35894200-69e0-11ea-8c3a-677a96222523.png)

**Comment by marcotcr** [comment]
Sorry, I think I don't understand the question. If your model is multilabel and you are explaining one particular label, interpret the results as positive / negative towards that label.
