### ISSUE TITLE
show_in_notebook not displaying the left "Prediction Probabilities" portion figure

### ISSUE THREAD

**Issue by rabitwhte** [marcotcr/lime#441]
Issues with show_in_notebook for regression
![image](https://user-images.githubusercontent.com/43826606/77895576-46a34000-7277-11ea-86a1-5f50f1769212.png)

**Comment by rabitwhte** [comment]
It seems that it does not work properly for wide range variables. I just checked it in the same notebook and it worked for smaller y. Predicted variable from the screenshot above is in the range 0-100_000. @marcotcr that could be solved with scientific notation maybe?

**Comment by marcotcr** [comment]
should be fixed by 5c7107e09e85c07a3417686673f2c81756c29280.

**Comment by rabitwhte** [comment]
Thank you, now I can see the predicted variable. Yet it still overlaps with feature value:
![image](https://user-images.githubusercontent.com/43826606/78419467-5d1a1480-7646-11ea-9d9b-7b472a4d1e11.png). Can I move it around somehow?
