### ISSUE TITLE
No module named 'tqdm.auto'

### ISSUE THREAD

**Issue by Andreasksalk** [marcotcr/lime#445]
As i can see you have updated the latest release to use tqdm. However this bug occurs when using the image explainer.

tqdm==4.45.0
lime==2.0.0

**Comment by marcotcr** [comment]
hm, I can't reproduce it.
Can you give me a few more details, namely:
- Python version
- OS

Thanks,

**Comment by Andreasksalk** [comment]
Python 3.7.0
Windows 10 

Downgrading one version helps.

**Comment by marcotcr** [comment]
Also can't replicate on python3.7 on Windows. Weird....
I'll close and investigate further if we get more cases

**Comment by Andreasksalk** [comment]
Sorry for the late response!

Nice of you too look into it, and weird that im the only one facing this issue. However it works fine with downgrading one version, so ill just stick to that. As i allready said i think it is some tqdm dependency that fails, but i mostly work in a clean Anaconda environment, so i cant see where it should come from.

Regards,
Andreas

**Comment by SchiggyWasTaken** [comment]
> 
> 
> Sorry for the late response!
> 
> Nice of you too look into it, and weird that im the only one facing this issue. However it works fine with downgrading one version, so ill just stick to that. As i allready said i think it is some tqdm dependency that fails, but i mostly work in a clean Anaconda environment, so i cant see where it should come from.
> 
> Regards, Andreas

thats not true, I have the same issue on Windows 10 and Python 3.7.0
