### ISSUE TITLE
ignore 1st column in lime tabular explainer

### ISSUE THREAD

**Issue by Mrinal-Mahajan** [marcotcr/lime#446]
Is there a way i can ignore the 1st column without dropping it from data from lime tabular explainer and use just remaining columns in analysis.

**Comment by marcotcr** [comment]
If you don't want the first column to be perturbed, you can write a custom `__data_inverse` (see [here](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L468)), or write a hacked prediction function (probably easier). Assuming `x` is the instance you want to explain, `pp_fn` is the predict_proba function, and `explainer` is a `LimeTabularExplainer` which was initialized with data that **does not** contain the first column:

```
def explain_without_first(x, pp_fn, explainer, **kwargs):
  first = x[0]
  # remove first column from x
  x = x[1:]
  def new_pp(xs):
    n = xs.shape[0]
    firstcol = np.repeat(first, n).reshape(-1, 1)
    # adds the original value back before predicting
    xs = np.hstack((firstcol, xs))
    return pp_fn(xs)
  return explainer.explain_instance(x, new_pp, **kwargs)
