### ISSUE TITLE
CNN explainability on images with more than 3 images.

### ISSUE THREAD

**Issue by Spiruel** [marcotcr/lime#447]
I have inputs of dimensions (250,250,13), representing multispectral imagery. 

As Lime describes itself as able to explain the predictions of any machine learning classifier - is there a possible way to explain predictions using Lime on such images?

Thanks

**Comment by marcotcr** [comment]
In principle nothing stops us from explaining such predictions, but LIME depends on an interpretable representation and a perturbation function. For images with 3 channels, we use 'superpixel on or off' as interpretable representation, and 'hide superpixel' as a perturbation function. I don't know what a meaningful representation or perturbation function would be for multispectral imagery.
In sum, you could definitely do it, but you won't be able to take LIME as is (you'd have to write an explainer similar to the image one)
