### ISSUE TITLE
TypeError: 'numpy.ndarray' object is not callable

### ISSUE THREAD

**Issue by rsingh2083** [marcotcr/lime#449]
My partial code is runing but fails at LIME

```
import numpy as np
import tensorflow as tf
import os,sys
import cv2
import matplotlib.image as mpimg
import lime
from lime import lime_image

mapping = {'ABS': 0, 'ALL': 1, 'BZM': 2}
inv_mapping = {0: 'ABS', 1: 'ALL', 2: 'BZM'}
sess = tf.compat.v1.Session()
tf.compat.v1.get_default_graph()
#tf.compat.v1.reset_default_graph()
tf.compat.v1.disable_eager_execution()

saver = tf.compat.v1.train.import_meta_graph(os.path.join('models/BZMNetv2/', 'model.meta_eval'))
saver.restore(sess, os.path.join('models/BZMNetv2/', 'model-2069'))
graph = tf.compat.v1.get_default_graph()


image_tensor = graph.get_tensor_by_name("input_1:0")
pred_tensor = graph.get_tensor_by_name("dense_3/Softmax:0")

x = cv2.imread('assets/test.jpeg')
x = cv2.resize(x, (224, 224))
x = x.astype('float32') / 255.0


pred = sess.run(pred_tensor, feed_dict={image_tensor: np.expand_dims(x, axis=0)})
print('Prediction: {}'.format(inv_mapping[pred.argmax(axis=1)[0]]))
print('Confidence')
print('ABS: {:.3f}, ALL: {:.3f}, BZM: {:.3f}'.format(pred[0][0], pred[0][1], pred[0][2]))

#LIME
explainer = lime_image.LimeImageExplainer()
explanation = explainer.explain_instance(mpimg.imread('assets/test.jpeg'),pred.argmax(axis=1)[0], top_labels=1, hide_color=0)

```
**ERROR**
Prediction: BZM
Confidence
ABS: 0.036, ALL: 0.398, BZM: 0.566

  1%|█                                                                                                                      | 9/1000 [00:00<00:27, 35.86it/s]
Traceback (most recent call last):
  File "temp.py", line 57, in <module>
    explanation = explainer.explain_instance(mpimg.imread('assets/ex-covid.jpeg'),pred.argmax(axis=1)[0], top_labels=1, hide_color=0)
  File "/home/buddy/anaconda3/lib/python3.7/site-packages/lime/lime_image.py", line 200, in explain_instance
    batch_size=batch_size)
  File "/home/buddy/anaconda3/lib/python3.7/site-packages/lime/lime_image.py", line 261, in data_labels
    preds = classifier_fn(np.array(imgs))
TypeError: 'numpy.int64' object is not callable

**Comment by marcotcr** [comment]
the second parameter of explain_instance should be the softmax function, not a prediction itself
