### ISSUE TITLE
Add tutorial from gh-pages as Jupyter notebook

### ISSUE THREAD

**Issue by shagunsodhani** [marcotcr/lime#45]

**Comment by marcotcr** [comment]
So, the reason I kept them as html files was that the notebooks do not show the visualizations (because of the weird way in which I generate them with javascript).
Did you have a fix for that?
Thanks,

**Comment by shagunsodhani** [comment]
Ahh I see your point. So the notebooks, when uploaded to Github, do not show the visualizations. But on running the notebooks locally,  the visualizations render fine. I have attached a screenshot for the same.

![lime](https://cloud.githubusercontent.com/assets/1321193/22401108/caabb090-e5ed-11e6-93f6-ea70882d0998.png)

So maybe we can add the notebooks with the disclaimer that visualizations render properly only when they are run locally (as of now).  In current scenario, where the demo is not available as executable code, it is harder to experiment and play around with.

**Comment by shagunsodhani** [comment]
Hey @marcotcr I would love to know your feedback on the proposed issue and [PR](https://github.com/marcotcr/lime/pull/46).

**Comment by marcotcr** [comment]
Right now, we do have the tutorials in the repository, under doc/notebooks. I guess if you couldn't find it, it means we should create a link in the README.
I prefer to keep the gh-pages as html so that the visualizations work.

**Comment by shagunsodhani** [comment]
Ouch I never realized that. The PR does exactly this :)
