### ISSUE TITLE
How to remove unwanted columns for explanations?

### ISSUE THREAD

**Issue by jkrabbenbos** [marcotcr/lime#450]
For my research I have created my own explainer by copying and adapting the tabular implementation. However, I get explanations on data in columns in my data which are not relevant for the explanation but are necessary to create the perturbations. 

Should I remove these unwanted columns from the data set I feed into the explanation.Explanation function to get only explanations on the real features?

**Comment by marcotcr** [comment]
Sorry, I don't understand your situation, so I'll give a general answer (you can reopen the issue if this doesn't answer your question).

Whatever features you feed to the Explainer will be perturbed, and can potentially be part of the explanation. If your model uses features 1-10 and you give features 1-5 to the explainer, the explainer will create perturbed data with features 1-5 and ask the model to make predictions, which will not work unless you wrap the model's prediction function such that it works with features 1-5 by filling in features 6-10 with something (see the discussion in #414). This could be a good solution if your other features are a function of what you are calling _real_ features.
