### ISSUE TITLE
Explaining Grey-Images with Lime

### ISSUE THREAD

**Issue by LukeValley** [marcotcr/lime#453]
Hi,

I have an existing CNN model that needs to be explained. This looks like the following:

```
model = tf.keras.models.Sequential()

width, height = 1024,1024

model.add(tf.keras.layers.Conv2D(8, 3, activation='relu', input_shape=(width, height, 1)))  
model.add(tf.keras.layers.MaxPooling2D())
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Conv2D(6, 1, activation='relu', input_shape=(width, height, 1)))  
model.add(tf.keras.layers.MaxPooling2D())
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Conv2D(4, 3, activation='relu', input_shape=(width, height, 1)))
model.add(tf.keras.layers.MaxPooling2D())
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Conv2D(8, 1, activation='relu', input_shape=(width, height, 1)))
model.add(tf.keras.layers.MaxPooling2D())
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Conv2D(8, 1, activation='relu', input_shape=(width, height, 1)))
model.add(tf.keras.layers.MaxPooling2D())
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Conv2D(4, 1, activation='relu', input_shape=(width, height, 1)))
model.add(tf.keras.layers.MaxPooling2D())
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Dropout(0.3))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(4, activation='relu',kernel_regularizer=keras.regularizers.l2(l=0.1)))
model.add(tf.keras.layers.Dense(2))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))    

model.summary()
```

And a test data set with the shape (1,1024,1024,1). If I now want to have this record explained with the following code:
`explanation = explainer.explain_instance(testing[1].reshape(1,1024,1024,1),
                                         model.predict,
                                         top_labels=5,
                                         hide_color=0,
                                         num_samples=100)`
I get this error:
> ValueError                                Traceback (most recent call last)
> <ipython-input-77-9a0cb43df74a> in <module>
>       5                                          top_labels=5,
>       6                                          hide_color=0,
> ----> 7                                          num_samples=10)
> 
> ~/.local/lib/python3.6/site-packages/lime/lime_image.py in explain_instance(self, image, classifier_fn, labels, hide_color, top_labels, num_features, num_samples, batch_size, segmentation_fn, distance_metric, model_regressor, random_seed)
>     182             segments = segmentation_fn(image)
>     183         except ValueError as e:
> --> 184             raise e
>     185 
>     186         fudged_image = image.copy()
> 
> ~/.local/lib/python3.6/site-packages/lime/lime_image.py in explain_instance(self, image, classifier_fn, labels, hide_color, top_labels, num_features, num_samples, batch_size, segmentation_fn, distance_metric, model_regressor, random_seed)
>     180                                                     random_seed=random_seed)
>     181         try:
> --> 182             segments = segmentation_fn(image)
>     183         except ValueError as e:
>     184             raise e
> 
> ~/.local/lib/python3.6/site-packages/lime/wrappers/scikit_image.py in __call__(self, *args)
>     115 
>     116     def __call__(self, *args):
> --> 117         return self.target_fn(args[0], **self.target_params)
> 
> ~/.local/lib/python3.6/site-packages/skimage/segmentation/_quickshift.py in quickshift(image, ratio, kernel_size, max_dist, return_tree, sigma, convert2lab, random_seed)
>      61         if image.shape[2] != 3:
>      62             ValueError("Only RGB images can be converted to Lab space.")
> ---> 63         image = rgb2lab(image)
>      64 
>      65     if kernel_size < 1:
> 
> ~/.local/lib/python3.6/site-packages/skimage/color/colorconv.py in rgb2lab(rgb, illuminant, observer)
>    1030     a list of supported illuminants.
>    1031     """
> -> 1032     return xyz2lab(rgb2xyz(rgb), illuminant, observer)
>    1033 
>    1034 
> 
> ~/.local/lib/python3.6/site-packages/skimage/color/colorconv.py in rgb2xyz(rgb)
>     672     # Follow the algorithm from http://www.easyrgb.com/index.php
>     673     # except we don't multiply/divide by 100 in the conversion
> --> 674     arr = _prepare_colorarray(rgb).copy()
>     675     mask = arr > 0.04045
>     676     arr[mask] = np.power((arr[mask] + 0.055) / 1.055, 2.4)
> 
> ~/.local/lib/python3.6/site-packages/skimage/color/colorconv.py in _prepare_colorarray(arr)
>     143         msg = ("the input array must be have a shape == (.., ..,[ ..,] 3)), " +
>     144                "got (" + (", ".join(map(str, arr.shape))) + ")")
> --> 145         raise ValueError(msg)
>     146 
>     147     return dtype.img_as_float(arr)
> 
> ValueError: the input array must be have a shape == (.., ..,[ ..,] 3)), got (1, 1024, 1024, 1)

It seems that LIME is not able to explain images which are not in RGB format?
On the other hand a transformation to RGB (1,1024,1024,3) would not fit to my CNN.

Anyone familiar with this?

Thank you!

**Comment by marcotcr** [comment]
We assume that the image is either 3d or 2d grayscale (in which case we convert it to 3d). This implies that the predict function must take a 3d RGB image with 3 channels in the last dimension (x, y, 3), or dimension (x, y), while yours takes in (x, y, 1).  One quick fix is to use an image with dimensions (x, y) with the explainer, and fold the conversion to (x, y, 1) into the prediction function:

```
def new_predict_fn(images):
    images = convert_to_1channel(images)
    return model.predict(images)
```
Where `convert_to_1channel `will be something like a np.reshape(1, -1).

**Comment by garykuok** [comment]
Hello,
I am also using grayscale image for lime explain_instance function. 
Now I encounter a new problem. If I set any 'size' of num_samples>1, when passing it to classifier_fn, it will have shape of ('size', x, y, 3). In this case, I can't simply reshape it back to grayscale image of shape (x, y, 1) because of the 'size'. If I set num_samples=1, I can reshape it to (1, x, y, 1) and do prediction as usual (this is the dimension my classifier can read).
How is this num_samples work in the classifier? Or should I just omit the 'size' and always return the same result in the loop?

**Comment by rEstela** [comment]
Hello Marco!

I have the same issue.
So, if I understand correctly, what I gotta do is:

1 - Convert image (1 x img_width x img_height x 1) to (img_width x img_height)
`image = x_img[0, :, :, 0]`

2 - Define a function to convert image to (img_width x img_heigth) back to (1 x img_width x img_heigth x 1)
`def new_predict_fn(img)`
`      img = img[np.newaxis, ..., np.newaxis]`
`      return model.predict(img)`

3 - Run lime
`explainer = lime_image.LimeImageExplainer()`
`explanation = explainer.explain_instance(image, new_predict_fn(image), top_labels=5, hide_color=0, num_samples=250)`

However, when I do this it starts to run but it stops at 9/250 and I got:

TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_6332/722228459.py in <module>
      9 print('image shape: ', image.shape)
     10 
---> 11 explanation = explainer.explain_instance(image,\
     12                                          new_predict_fn(image), top_labels=5,\
     13                                          hide_color=0, num_samples=250)

~\anaconda3\lib\site-packages\lime\lime_image.py in explain_instance(self, image, classifier_fn, labels, hide_color, top_labels, num_features, num_samples, batch_size, segmentation_fn, distance_metric, model_regressor, random_seed)
    196         top = labels
    197 
--> 198         data, labels = self.data_labels(image, fudged_image, segments,
    199                                         classifier_fn, num_samples,
    200                                         batch_size=batch_size)

~\anaconda3\lib\site-packages\lime\lime_image.py in data_labels(self, image, fudged_image, segments, classifier_fn, num_samples, batch_size)
    259             imgs.append(temp)
    260             if len(imgs) == batch_size:
--> 261                 preds = classifier_fn(np.array(imgs))
    262                 labels.extend(preds)
    263                 imgs = []

TypeError: 'numpy.ndarray' object is not callable

**Comment by psyllost** [comment]
Do you see that the 2D to 3D conversion will affect the results of the explainer in some way?
