### ISSUE TITLE
LSTM based text classification model gives "Value error:  The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()"

### ISSUE THREAD

**Issue by amarpazad** [marcotcr/lime#454]
Hi, 
I am using an LSTM based model for text classification. Facing the following problem. 
Any pointers to fix this? 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-f1f38b46ebcd> in <module>
----> 1 exp = explainer.explain_instance(test_sen1, pred_eval.pred_probs, num_features=3, labels=(0,) )

/home/anaconda3/envs/py36torch/lib/python3.6/site-packages/lime/lime_text.py in explain_instance(self, text_instance, classifier_fn, labels, top_labels, num_features, num_samples, distance_metric, model_regressor)
    430                 data, yss, distances, label, num_features,
    431                 model_regressor=model_regressor,
--> 432                 feature_selection=self.feature_selection)
    433         return ret_exp
    434 

/home/anaconda3/envs/py36torch/lib/python3.6/site-packages/lime/lime_base.py in explain_instance_with_data(self, neighborhood_data, neighborhood_labels, distances, label, num_features, feature_selection, model_regressor)
    204         return (easy_model.intercept_,
    205                 sorted(zip(used_features, easy_model.coef_),
--> 206                        key=lambda x: np.abs(x[1]), reverse=True),
    207                 prediction_score, local_pred)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by marcotcr** [comment]
does `pred_eval.pred_probs` take a list of strings as inputs and outputs an `(n, d)` numpy array of prediction probabilities?

**Comment by amarpazad** [comment]
Thanks. On checking, I realized that pred_eval.pred_probs was not in proper format. Its working.

**Comment by renhao1998** [comment]
> Thanks. On checking, I realized that pred_eval.pred_probs was not in proper format. Its working.

hello, i meet the same error like your , can you show the detail , thanks!
