### ISSUE TITLE
Is LIME suitable for dataset with more than 100 features and multiclass with RandonForestClassifier Model?

### ISSUE THREAD

**Issue by lavendercmt** [marcotcr/lime#455]
Is LIME suitable for dataset with more than 100 features and multiclass with RandonForestClassifier Model?
I have used lime_tabular.LimeTabularExplainer 
although it has results but how to explain it?

![image](https://user-images.githubusercontent.com/52583754/80365520-0809a100-8888-11ea-9a21-29a71c07820c.png)

(just hid the real feature names..)

The predicition about probabilty is correct! But how about the features in right side...why all the value so strange...

**Comment by marcotcr** [comment]
I don't know if I understood what you are asking, but what you have on the middle and right side are explanations for two labels: label 1 and label 6. The one in the middle is telling you what is positive towards 1 and negative towards 1 (i.e. positive towards everything else), while the one on the right is doing the same for label 6.

If you're asking about why the weights are so low: it could be a variety of things, including:
- The intercept for class 1 is really high, i.e. the model generally predicts 1 in the neighborhood of the prediction (or in general if there is class imbalance), so the 'empty' explanation is sufficient
- The kernel width is too small
