### ISSUE TITLE
local_exp has only one feature index but many weights

### ISSUE THREAD

**Issue by aminamo** [marcotcr/lime#456]
Using the following code with the explainer,

`explanation = LimeH2OHI3G.explain_instance(dataRow, h2o_drf_wrapper.predict_proba, num_samples=100, num_features=6)
  explanationlist = explanation.as_list()`

I get this error _TypeError: only size-1 arrays can be converted to Python scalars_   originating from this line in as_list() : `ans = [(x[0], float(x[1])) for x in ans]`

digging a bit i found out that local_exp in explanation has 6 wights but only one value for the feature indexes. I tried many combinations of num_features and num_samples but no luck.

![image](https://user-images.githubusercontent.com/37072838/80764542-3534a880-8b41-11ea-8d0a-a5637edeba84.png)

**Comment by marcotcr** [comment]
Can you paste the line you used to initialize the explainer?

**Comment by aminamo** [comment]
I am loading the explainer from a file as it is used in a separate environment that the training one. 

```
with open('/LimePredict/XLimeH2OHI3GModel', 'rb') as f:
        LimeH2OHI3G=dill.load(f) 
        explanation = LimeH2OHI3G.explain_instance(dataRow, h2o_drf_wrapper.predict_proba,num_samples=10, num_features=6)
        explanationlist = explanation.as_list()
```

Ti initialize it i am using this line

```
explainerH2OHI3G = lime.lime_tabular.LimeTabularExplainer(XLimeH2OHI3G ,mode='classification', feature_names = feature_names05, class_names = ['0','1'],
                                                   categorical_features=categorical_features05, 
                                                   categorical_names=['FAC_CODE'], discretize_continuous=False)
```

**Comment by marcotcr** [comment]
I'm having a hard time reproducing it. Can you generate any explanations with this explainer?
`exp.local_exp` should be a dict of labels to list of `(feature, value)` tuples.

**Comment by aminamo** [comment]
Thank you for investigating it. To be more specific, the explainer work in my development environment, on JupiterLab and a running H2O cluster.

But as I said when using it on a separate environment by loading it and executing it against remote H2O server through API, it haven't generated any valid explanation.
