### ISSUE TITLE
Does surrogate model use binary features?

### ISSUE THREAD

**Issue by pmavrodiev** [marcotcr/lime#458]
This is more of a question about the implementation and not really a functional problem. I hope it's not out of place and I appologize in advance if it is.

My question is why isn't the surrogate model trained on the binary features of the interpretable space? This is at least what I read in every academic paper on Lime - surrogate model is trained on binary features. True, targets come from the black-box model, but the features are simply 0's and 1's. 

Instead it seems to be that the surrogate is trained on features in the original features space.

What am I missing? 

Thanks a lot.

**Comment by marcotcr** [comment]
The surrogate is trained on binary data, for all explainers (Tabular, Text and Image). Why do you get the impression that it is trained on features in the original feature space?

**Comment by pmavrodiev** [comment]
Sorry @marcotcr it appears I've misread the code. Kind of embarrassing. Sorry for wasting your time and thanks for the quick response.

**Comment by marcotcr** [comment]
No problem. [Here](https://github.com/marcotcr/lime/blob/master/lime/lime_text.py#L473) is an example from text, note how we have `data` (binary) and `inverse_data` (text), and how the model gets the latter.

**Comment by nihaljn** [comment]
My understanding is that for tabular data, the surrogate is trained on features in the original feature space if `discretize_continuous == False`. Is this correct?
