### ISSUE TITLE
Explainable of Siamese Network

### ISSUE THREAD

**Issue by skuehn1988** [marcotcr/lime#459]
Is it possible to have two inputs and to have a explainable of a Siamese Network?

**Comment by arrayslayer** [comment]
Yes it is model agnostic, that is, it works for any model. All you need is the predict function or equivalent of your Siamese network.

**Comment by skuehn1988** [comment]
But in the Siamese Network you have two images as an input (Comparison) and the model. So for the prediction you need 3 inputs. Do you have a example for this?

**Comment by marcotcr** [comment]
This doesn't work out of the box. You would need to either adapt LimeImageExplainer, or do a hack and concatenate both images into one, separating them inside the prediction function. The problem with this hack is that the segmentation could be weird, so you would have to write your own segmentation function (which would separate them before segmenting)
