### ISSUE TITLE
Dealing with Categorical Features

### ISSUE THREAD

**Issue by Dola47** [marcotcr/lime#460]
Hi @marcotcr ,

I would like you to confirm if I am working correctly or not with the categorical features in my dataset. normally, I OneHotEncode the categorical features in my dataset.

First of all, as far as I know the data submitted to the LimeTabularExplainer and explain_instance should be label encoded version of my dataset, however, the predict_fn should take in consideration the OnehotEncoded version of my dataset so I revert back the label encoded dataset to OneHotEncoded dataset inside the predict_fn.

Moreover, for the categorical_features and categorical_names parameters, since, I submit the Explainer with LabelEncoded version of the dataset I return back the indices of the features incase of the label encoded dataset. Of course, the categories are returned as they are supposed to be returned

Is my implementation correct?

**Comment by marcotcr** [comment]
There is an example [here](https://marcotcr.github.io/lime/tutorials/Tutorial%20-%20continuous%20and%20categorical%20features.html) that answers all of your questions, I think. See lines 20-28 for the first question, and lines 12-16 for the second. The ipynb version is [here](https://github.com/marcotcr/lime/blob/master/doc/notebooks/Tutorial%20-%20continuous%20and%20categorical%20features.ipynb)
