### ISSUE TITLE
Is it possible to do incremental training on LimeTabularExplainer?

### ISSUE THREAD

**Issue by apremgeorge** [marcotcr/lime#461]
Hi,
I have a data, I fit a model, store the model, later I get new data, I don't want to retrain with full data, so I fit the new data, may I know is it possible to create explainer as a incremental fit for the new data. 
```
data = [[1, 2], [0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler()
scaler.partial_fit(data)
sc_data = scaler.transform(data)
model1 = IForest(contamination=0.1).fit(sc_data)
explainer = lime.lime_tabular.LimeTabularExplainer(sc_data, 
                                                      mode='classification',
                                                      feature_names=feature_names,
                                                      kernel_width=5,
                                                      random_state=42,
                                                      discretize_continuous=False)
```
I store the model, scaler, explainer for serving purpose, 
after some time i get more data, so fit the new data to the same model,
is it possible for explainer as well? 
```
data2 = [[15, 12], [15, 16], [0, 11], [1, 18]]
scaler = load(scaler)
loaded_model = load(model1)

scaler.partial_fit(data2)
sc_data2 = scaler.transform(data2)
model2 = loaded_model.fit(sc_data2)
explainer = lime.lime_tabular.LimeTabularExplainer(????????????????)
```
Thanks in advance for the inputs.

**Comment by marcotcr** [comment]
You can use the `training_data_stats` parameter (description [here](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L181)).
Best,

**Comment by marcotcr** [comment]
(and just use an empty list as the first parameter)

**Comment by apremgeorge** [comment]
@marcotcr 
Thanks for the reply,
For this do we have to get the data stats from explainer?

**Comment by apremgeorge** [comment]
Hi @marcotcr 
In creating first explainer using training_data_stats=None
```
explainer = lime.lime_tabular.LimeTabularExplainer(sc_data, 
                                                      mode='classification',
                                                      feature_names=feature_names,
                                                      kernel_width=5,
                                                      random_state=42,
                                                      discretize_continuous=False,
                                                      training_data_stats=None)
```
From the data, I saved stats dict
```
descritizer = QuartileDiscretizer(sc_data, [], feature_names, random_state=20)
data_stats = {}
data_stats["means"] = descritizer.means
data_stats["stds"] = descritizer.stds
data_stats["maxs"] = descritizer.maxs
data_stats["mins"] = descritizer.mins
d_bins_revised = {}
index = 0
d_bins = descritizer.bins(sc_data, [0,1])
for bin in d_bins:
    d_bins_revised[index] = bin.tolist()
    index = index+1  
data_stats["bins"] = d_bins_revised
cat_features = np.arange(sc_data.shape[1])
discretized_training_data = descritizer.discretize(sc_data)
feature_values = {}
feature_frequencies = {}
for feature in cat_features:
    column = discretized_training_data[:, feature]
    feature_count = collections.Counter(column)
    values, frequencies = map(list, zip(*(feature_count.items())))
    feature_values[feature] = values
    feature_frequencies[feature] = frequencies
data_stats["feature_values"] = feature_values
data_stats["feature_frequencies"] = feature_frequencies
```
For the sc_data2 explainer, I used the data_stats
```
explainer2 = lime.lime_tabular.LimeTabularExplainer(sc_data2, 
                                                      mode='classification',
                                                      feature_names=feature_names,
                                                      kernel_width=5,
                                                      random_state=42,
                                                      discretize_continuous=False,
                                                      training_data_stats=data_stats)
```
Now I will create stats for the new data sc_data2 as well
now I have 2 dict of stats
So after some more time for more new data, which stats should I use, avg of 2 dict not a right approach
That's why I was wondering is there possibility to extract data stats from saved explainer? or do you suggest anything on this?
Thanks

**Comment by apremgeorge** [comment]
Hi @marcotcr 
May I have some input on the above please, Thanks

**Comment by marcotcr** [comment]
You will have to have a separate object keeping track of the running averages for feature frequencies. I assume you're not updating the discretizer every time, so everything else should stay the same. What you can do is apply the discretizer from the original explainer on the new data and update the frequencies.

**Comment by apremgeorge** [comment]
Thanks for that, just to confirm
Here is the two stats for First data and New data, I used the same discretizer and updated the stats dictionary with the new data frequencies using this function
The frequencies shape different between the two, is that correct, Thanks @marcotcr 
```
def Trained_Explainer_Stats(new_df, trained_data_stats, trained_descritizer):
    data_stats = {}
    data_stats = trained_data_stats.copy()
    cat_features = np.arange(new_df.shape[1])
    discretized_training_data = trained_descritizer.discretize(df)
    feature_frequencies = {}
    for feature in cat_features:
        column = discretized_training_data[:, feature]
        feature_count = collections.Counter(column)
        values, frequencies = map(list, zip(*(feature_count.items())))
        feature_frequencies[feature] = frequencies
    data_stats["feature_frequencies"] = feature_frequencies
    return data_stats, trained_descritizer
```
![image](https://user-images.githubusercontent.com/30790120/83471138-4158b080-a4c7-11ea-8cba-c3132266845f.png)
![image](https://user-images.githubusercontent.com/30790120/83471154-4e759f80-a4c7-11ea-83ac-1583d4ba8bb2.png)

**Comment by marcotcr** [comment]
It looks like you did something wrong, since your frequencies are going down after updating.

**Comment by apremgeorge** [comment]
Whether other data stats should remain same, even though the new data should be having different mean and SD?

**Comment by apremgeorge** [comment]
Hi @marcotcr 
Can I have some inputs please, Thanks

**Comment by apremgeorge** [comment]
Hi @marcotcr,
May I know what could be the mistake above. Thanks

**Comment by marcotcr** [comment]
Hi,
I am not going to take time to debug this, sorry.  You should make sure the raw counts are being updated appropriately (going up), even if relative frequencies are changing. You should be able to come up with a small initial example and update so you can debug what the expected stats are.
Good luck : )

**Comment by apremgeorge** [comment]
the training_data_stats parameters is no use then, the example I tried is the smallest possible one, 

As you mentioned, except frequency all others stats can remain same, but that doesn't look right.

Frequencies can be averaged, so I am not sure of this.
Thanks

**Comment by hanzigs** [comment]
Hi @marcotcr 
I couldn't fix this issue, may I have some help, Thanks
