### ISSUE TITLE
Image Classification Keras Turtorial notebook needs to be updated

### ISSUE THREAD

**Issue by aish-where-ya** [marcotcr/lime#462]
Hello, 
I was using this tutorial to implement LIME for generating explanations for my Breast Cancer Detection model. Upon multiple trials, I was able to get the mask, but the underlying image was blank. Even though `hide_rest` in the `explanation.get_image_and_mask()` function was set to be `False`. 

I found a workaround for this issue. I used a `SegmentationAlgorithm()` function and passed it to the `explainer.explain_instance()` function as a value to the `segmentation_fn` argument. The explanations began to show the mask as well as the underlying image. I would be happy to create a PR for the same.

These will be the updated lines of code - 
```
lime_explainer = lime_image.LimeImageExplainer() 
segmenter = SegmentationAlgorithm('quickshift', kernel_size=1, max_dist=200, ratio=0.2) 
explanation = lime_explainer.explain_instance(transform_img_fn(sample_image2), 
                classifier_fn = model.predict, 
                top_labels=2, 
                hide_color=0, 
                num_samples=1000,
                segmentation_fn=segmenter)
temp, mask = explanation.get_image_and_mask(explanation.top_labels[0], 
                                            positive_only=True, 
                                            num_features=20, 
                                            hide_rest=False)
plt.imshow(mark_boundaries(temp, mask))
```

Please give your feedback on this issue.

**Comment by marcotcr** [comment]
I'm sorry, I don't think I understand what the issue is.
It seems to me that the default `kernel_size=4` didn't work for your Breast Cancer Detection model, so you changed it to `kernel_size=1`. However, `4` does seem to work pretty well in the keras tutorial, i.e. it gives segments that seem reasonable. Are you suggesting we change it to `1` in the tutorial?
Best,
