### ISSUE TITLE
Intances with very different Prediction_local value

### ISSUE THREAD

**Issue by Abdulk084** [marcotcr/lime#464]
For some instances, the Prediction_local value (in case of regression problems) generated by lime is very different than the output of the complex model as shown below.
```

Intercept 2.8149082782686934
Prediction_local [3.20650489]
Right: 5.2020693
```
Do you think it is useful for interpretability as the interpretability parameters are derived from the local model but in this case, the local model is wrong? How can we trust the importance features values generated by a local model which is wrong locally? Or we need to choose such an instance where the local model output is not very different than the complex model output?

**Comment by marcotcr** [comment]
If the local model is not very faithful, it is probably better not to trust the explanation. However, you should not assess faithfulness based only on the prediction_local, but also consider the score in the neighborhood.

Having said that, in general it's a good rule of thumb to not trust explanations that don't predict the point you're trying to explain well.
