### ISSUE TITLE
Getting LIME does not currently support classifier models without scores for LinearSVC

### ISSUE THREAD

**Issue by deveshcode** [marcotcr/lime#465]
`from mosaicml import expai
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets
from mosaicml import *
from mosaicml.constants import MLModelFlavours
import numpy as np
from sklearn.svm import LinearSVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

iris = datasets.load_iris()
X = iris.data
y = iris.target
clf = make_pipeline(StandardScaler(),
                    LinearSVC(random_state=0, tol=1e-5))
clf = clf.fit(X, y)

@scoring_func
def score(model, request):
    payload = request.json["payload"]
    data_list = payload
    data_array = np.asarray(data_list)
    try:
        prediction = model.predict(data_array)
    except:
        prediction = model.predict(data_array.reshape(1, -1))
    return prediction.tolist()

import requests
req = requests.Request()
req.json = {"payload":X[135]}

score(clf,req)
import lime
import lime.lime_tabular

import pandas as pd
import numpy as np

explainer = lime.lime_tabular.LimeTabularExplainer(X,  
mode='classification',training_labels=y,feature_names=iris.feature_names)

i = 1
exp = explainer.explain_instance(X[0], clf.predict, num_features=4)`

Here's my sample code for creating a LIME graph. Am I doing something wrong or is there a workaround for the same ?
Thanks in advance for the help

Here's the error I get
NotImplementedError: LIME does not currently support classifier models without probability scores. If this conflicts with your use case, please let us know: https://github.com/datascienceinc/lime/issues/16

**Comment by marcotcr** [comment]
It doesn't actually have to be a probability score, but you need the output of your model to have 2 dimensions. Even if you only output one number, you need the output to be of shape `(n, 1)` rather than `(n,)`. You can achieve that with a simple reshape.

**Comment by muellerhi** [comment]
Hi, I have the same problem by using a LinearSVC, but I don't know how to shape the result of decision_function right.



    # load text data as Dataframe and transform to list
    data = pd.read_csv("H:\....\Text\wt.csv")
    data["text"] = data["text"].values.astype('U')
    text = data["text"].tolist()

    #load stored pipeline
    pipeline = joblib.load("H:\...\estimator.pkl")
    
    #create Explainer object
    explainer = LimeTextExplainer()
    
   
    def classifier_fn(X):
        vectorized_text_instance =  pipeline.named_steps["Vectorizer"].transform(X)
        decision =                  pipeline.named_steps["Classifier"].decision_function(vectorized_text_instance)
        reshaped_decision =         np.reshape(decision, (len(decision),1))
        return reshaped_decision


    explanation = explainer.explain_instance(text_instance = text[1], classifier_fn = classifier_fn)                                         
    print(explanation)

When running the code I get "Exception has occurred: IndexError
index 1 is out of bounds for axis 1 with size 1"


"decision" looks like this (n,)
[0.21415088681284894, 0.37758657452431055, 0.24526086659482135, 0.2340180632357362, 0.3499690725049086, 0.17553918389692882, 0.3687639869521063, 0.270355815090219, 0.38275617063141876, 0.2756738009682965, 0.17382450827236728, 0.33231740799625287, 0.20680537913124855, 0.08614439855103442, ...]

and "reshaped_decision" looks like this (n,1):
[array([0.21415089]), array([0.37758657]), array([0.24526087]), array([0.23401806]), array([0.34996907]), array([0.17553918]), array([0.36876399]), array([0.27035582]), array([0.38275617]), array([0.2756738]), array([0.17382451]), array([0.33231741]), array([0.20680538]), array([0.0861444]), ...]

Am I missing something? :-)

Thanks in advance

**Comment by marcotcr** [comment]
reshaped_decisions should not be a list of 1d arrays, but a 2d array.
Try `reshaped_decision = np.array(decision).reshape(-1, 1)`

**Comment by muellerhi** [comment]
Thank you very much for your answer. :-)

I have adapted the code accordingly, but the error message appeared again.
This was not due to the .reshape, but is related to issue: https://github.com/marcotcr/lime/issues/428

The code works if it looks like this:

`explanation = explainer.explain_instance(text_instance=text[1], classifier_fn=classifier_fn, labels=(0,))`

 ''' access explanation '''

`explanation_lime = explanation.as_list(label=0)`

My problem is now solved, but I thought that this comment would be helpful for others facing this problem.

**Comment by Hugo-CHI** [comment]
Hi, I have met with some problem when trying to use LIME. I am using the classification tree to build the model, and wanting to see how the feature works. But the error occured like this:
NotImplementedError: LIME does not currently support classifier models without probability scores. If this conflicts with your use case, please let us know: https://github.com/datascienceinc/lime/issues/16
![image](https://user-images.githubusercontent.com/68579887/124681117-70c3c300-defa-11eb-8feb-7a2af33e18c4.png)
I did try to make the output of the method with two dimentions, but still met with another the error:
![image](https://user-images.githubusercontent.com/68579887/124681250-a5377f00-defa-11eb-9e6c-f440a8291844.png)
![image](https://user-images.githubusercontent.com/68579887/124681296-c8622e80-defa-11eb-836c-7f613b12a280.png)
![image](https://user-images.githubusercontent.com/68579887/124681320-d31cc380-defa-11eb-9efe-1d327ffba661.png)
Is there any simple way to reshape the output? Thanks in advance.

**Comment by c1258797185** [comment]
> 'from mosaicml import expaifrom sklearn.ensemble import RandomForestClassifierfrom sklearn import datasets from mosaicml import *from mosaicml.constants import MLModelFlavorsimport numpy as npfrom sklearn.svm import LinearSVCfrom sklearn.pipeline import make_pipelinefrom sklearn.preprocessing import StandardScaler
> 
> iris = datasets.load_iris（）X = iris.datay = iris.targetclf = make_pipeline（StandardScaler（），LinearSVC（random_state=0， tol=1e-5））clf = clf.fit（X， y）
> 
> @scoring_funcdef score（model， request）：payload = request.json[“payload”]data_list = payload data_array = np.asarray（data_list）try：prediction = model.predict（data_array）except：prediction = model.predict（data_array.reshape（1， -1））return prediction.tolist（）
> 
> 导入请求req = 请求。Request（）req.json = {“payload”：X[135]}
> 
> 分数（CLF，req）进口石灰进口lime.lime_tabular
> 
> 导入熊猫作为PD导入NUMPY作为NP
> 
> 解释器 = lime.lime_tabular。LimeTabularExplainer（X，mode='classification'，training_labels=y，feature_names=iris.feature_names）
> 
> i = 1exp = explainer.explain_instance（X[0]， clf.predict， num_features=4）'
> 
> 这是我创建 LIME 图的示例代码。我做错了什么还是有解决方法？提前感谢您的帮助
> 
> 这是我收到的错误 NotImplementError：LIME 目前不支持没有概率分数的分类器模型。如果这与您的用例冲突，请告诉我们：https://github.com/datascienceinc/lime/issues/16

You need to change clf.predict to clf.predict_proba
