### ISSUE TITLE
Should discretize_continuous affect the explanation?

### ISSUE THREAD

**Issue by Zhunaidm** [marcotcr/lime#466]
Hi,

I'm currently running an experiment and I have a model where I know weights 1, 2, 3 add to class 1 and weights 4 and 5 add to class 2.

I'm using the tabular explainer since the features are generated integers between 0 and 10. The problem is that for some reason the explanation shows that weight 3 positively attributes to class 2 which is incorrect. If I set discretize_continuous to false, then the explanation is correct.

Is there a reason this happens?

**Comment by marcotcr** [comment]
See #196, #113 and #202 : )
