### ISSUE TITLE
NotImplementedError: LIME does not currently support classifier models without probability scores

### ISSUE THREAD

**Issue by KiteFlyKid** [marcotcr/lime#467]
When I tried to use sklearn Isolation Forest to explain my result , I got an error as the title.
```python
explainer = lime.lime_tabular.LimeTabularExplainer(Xtrain,mode='classification',training_labels=train_label,feature_names=columns,discretize_continuous=True)
exp = explainer.explain_instance(Xtrain[10], predict_fn=IsolationForest.score_samples, num_features=5)
```
I have replaced ' IsolationForest.score_samples' with  ' IsolationForest.decision_function'
or ' IsolationForest.predict', it remains the same.
I wonder if lime can only be applied on supervised learning or I just have a wrong code.

**Comment by apremgeorge** [comment]
Isolation Forest has predict_proba function which returns probabilities

**Comment by KiteFlyKid** [comment]
![image](https://user-images.githubusercontent.com/45324156/83323139-5f3bd080-a28f-11ea-93f6-e4758f48f423.png)
http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.IsolationForest.html
As seen in the screenshot, in sklearn implementaion, there is no predict-proba

**Comment by apremgeorge** [comment]
try pyod instead of sklearn for anomaly detection

**Comment by KiteFlyKid** [comment]
thx, pyod is quite helpful
