### ISSUE TITLE
Explainer not working properly with ktrain

### ISSUE THREAD

**Issue by rcmcabral** [marcotcr/lime#471]
Hi. I was hoping to use Lime to explain a BERT model trained through ktrain. I am basically following the sample they have on [20 newsgroups](https://colab.research.google.com/drive/1ixOZTKLz4aAa-MtC6dy_sAvc9HujQmHN). The library has a function called `predictor.predict_proba()` that accepts a string or a list/array of strings and outputs probabilities (1 dim if single string, 2 dim if multiple). I thought this would work seamlessly with LIME but my code below (which can be appended directly to the ktrain example) just runs endlessly without any error/warning even if my input is only one sample.

```
import lime
from lime import lime_text
from lime.lime_text import LimeTextExplainer

explainer = LimeTextExplainer(class_names=reloaded_predictor.get_classes())

exp = explainer.explain_instance(test_b.data[0], reloaded_predictor.predict_proba, num_features=10)
exp.show_in_notebook(text = test_b.data[0])
```

The predictor function works well when ran these ways:
```
reloaded_predictor.predict_proba(test_b.data[0])
reloaded_predictor.predict_proba(test_b.data[0:1])
reloaded_predictor.predict_proba(test_b.data[0:1000])
```

One thing I noticed when using it with the explainer is that for one sample, the predict_proba function seems to receive more samples to make predictions on. ktrain shows a progress bar when there are a lot of samples to process. Giving it 1000 samples usually shows "xx/1000" as it processes these. One sample is usually too quick to see. When used with the explainer as in the code above, "xx/5000" shows up. Attached an image below that shows this. Top is a normal `predict_proba` use; bottom was used with the explainer. 

![image](https://user-images.githubusercontent.com/28853530/84057955-143a5f80-a9eb-11ea-9bdc-8cab4bddc1fa.png)

I thought is was being split up into a character array but when I use `explainer.explain_instance(test_b.data[0:1]...` instead, the explainer throws an error of it expecting strings not bytes.

I was just wondering what could have gone wrong between the input and it being passed to the `predict_proba` function and if I'm missing something since it technically should work based on the documentation.

> classifier_fn: classifier prediction probability function, which
>                 takes a list of d strings and outputs a (d, k) numpy array with
>                 prediction probabilities, where k is the number of classes.
>                 For ScikitClassifiers , this is classifier.predict_proba.

Would love to have both libraries work with each other so I'd love any feedback specially if I got something wrong.

**Comment by marcotcr** [comment]
It doesn't seem like there is anything wrong. When explaining an individual prediction, lime will perturb the input instance in various ways and see how the model's prediction changes on the perturbed instances. The `num_samples` argument [controls how many perturbed instances we get predictions on](https://github.com/marcotcr/lime/blob/master/lime/lime_text.py#L395), and the default is `num_samples=5000`. This is why when you call `explain_instance`, you get x/5000.

**Comment by rcmcabral** [comment]
@marcotcr Thanks for the explanation! I misunderstood the `num_samples` parameter. Adjusted it a bit and transferred to GPU to get it to work. Again, thanks!
