### ISSUE TITLE
Not Installing on Python 3.8

### ISSUE THREAD

**Issue by benjaminkaplanphd** [marcotcr/lime#473]
There is a hardcoded version in the setup.py file for Pillow, which is incompatible with Python 3.8.

According to [this](https://pillow.readthedocs.io/en/latest/installation.html#notes) compatibility for version 5.4.1 (hard coded [here](https://github.com/marcotcr/lime/blob/master/setup.py#L17)) ended in 3.7

Please confirm this is a correct diagnosis, and supply a timeline for a fix.

Thank you.

**Comment by simplysaikat** [comment]
I have faced the same issue while installing lime on Python 3.8.2. setup.py file for pillow is not compatible with this python version.

**Comment by marcotcr** [comment]
Fixed by cbaf1d8fe6f6da797ad50ff875f6dada05f517fd
