### ISSUE TITLE
يضهر لي هذا الخطء عند الضغط عى الزر ليبدء التسجيل         TypeError: 'numpy.ndarray' object is not callable

### ISSUE THREAD

**Issue by hanirida** [marcotcr/lime#474]
def predict(audio):
    prob=model.predict(audio.reshape(1,8000,1))
    index=np.argmax(prob[0])
    return classes[index]
samplerate = 16000
duration = 1 #seconds
filename = 'testing.wav'
print("start")
mydata = sd.rec(int(samplerate * duration), samplerate=samplerate,
                channels=1, blocking= False)
print("end")
sd.wait()
sf.write(filename, mydata, samplerate)
#reading the voice commands
samples, sample_rate = librosa.load(filename, sr = 16000)
samples = librosa.resample(samples, sample_rate, 8000)
ipd.Audio(samples, rate=8000)
print(predict(samples))

sample = str(predict(samples))
my_label = tk.Label(window, width=15, height=5, bg='white', 
                    fg='black', text="%s" %(sample))
my_label.grid(row=2, column=1,padx=2,pady=5)

my_button = tk.Button(window, text="ابدء", width=15, height=3,
                      bg='red', fg='black', command=lambda:mydata(sd.rec)) 
my_button.grid(row=2, column=3,padx=2,pady=5)

window.mainloop()

**Comment by marcotcr** [comment]
looks like you have the wrong repo here

**Comment by hanirida** [comment]
ممكن طرقة الحل
