### ISSUE TITLE
Use the original un-scaled data or a scaled dataset?

### ISSUE THREAD

**Issue by kaixiyang** [marcotcr/lime#475]
Hi Marco, 

Could I get some advice on the application of LIME and the use of data scaling? I am using LIME to explain predictions from a classification model that was built using a dataset that was firstly scaled. For LIME, is it recommended to use the original un-scaled data or can a scaled dataset be used?

**Comment by marcotcr** [comment]
We also scale by default, so I would use the scaled data with the understanding that the explanation weights are to be interpreted w.r.t. scaled data.
