### ISSUE TITLE
Right value for top_labels in lime interpretability module for binary image classification

### ISSUE THREAD

**Issue by Abdulk084** [marcotcr/lime#476]
I am using [lime][1] for explaining binary classification images. The output of the prediction is as follows.

    pred_train =array([[0.8700583 ],
           [0.05999151],
           [0.92959476],
           [0.07004735],
           [0.07470205],
           [0.2557885 ]], dtype=float32)
When `pred_train>0.5` then it is classified as `class_1_image` and if `pred_train<0.5` then it is classified as `class_2_image`

As we can see that `pred_train[0]` belongs to `class_1_image`. 

Now I want to explain this prediction, i.e `pred_train[0]` for which I used corresponding `X_train_0` as follows in lime.

    explanation = explainer.explain_instance(X_train_0, new_predict_fn, top_labels=2, hide_color=0, num_samples=10)

My first question is **What should be the value of `top_labels` in binary image classification when the prediction output is a single probability and why?**

The image I want to explain is `X_train_0` which belongs to `class_1_image` as `pred_train[0]>0.5`. The `X_train_0` image is shown below.

![download](https://user-images.githubusercontent.com/31172014/85226998-bc095180-b41d-11ea-9060-9cba6b973c51.png)

Then I used the following code to explain my image.

```
temp, mask = explanation.get_image_and_mask(explanation.top_labels[0], positive_only=True, num_features=5, hide_rest=True)
plt.imshow(mark_boundaries(temp / 2 + 0.5, mask))
```
And obtained the following image as an explanation.
![download (1)](https://user-images.githubusercontent.com/31172014/85227046-0ee30900-b41e-11ea-8280-5123ba24b91d.png)

Here I used `num_features=5`, which means 5 superpixels should be found. **How can I spot these 5 features in my image?**

In case, I spot these 5 features in the image explained, **does that mean that these five features are positively correlated with the probability prediction of this class for this specific image?**

**Can I also find out what is the value of that positive correlation?**

  [1]: https://github.com/marcotcr/lime

**Comment by marcotcr** [comment]
> My first question is What should be the value of top_labels in binary image classification when the prediction output is a single probability and why?

You can just set `labels=(0,)`, it will generate an explanation for your predicted class.

> Here I used num_features=5, which means 5 superpixels should be found. How can I spot these 5 features in my image?

They are the superpixels that are not hidden (gray). Check out [this tutorial](https://marcotcr.github.io/lime/tutorials/Tutorial%20-%20images.html) for other ways of visualizing it.

> In case, I spot these 5 features in the image explained, does that mean that these five features are positively correlated with the probability prediction of this class for this specific image?

It means that hiding these 5 features on average _decreases_ the probability prediction for this class, and thus keeping them has _positive_ weight.

> Can I also find out what is the value of that positive correlation?

Yes, you can look at `explanation.local_exp`. `explanation.segments` contains the mask for each feature index in that map. You can take a look at [this](https://github.com/marcotcr/lime/blob/master/lime/lime_image.py#L33) to see how it is used.
