### ISSUE TITLE
Consistency issue in lime image explanation

### ISSUE THREAD

**Issue by Abdulk084** [marcotcr/lime#477]
Every time I run `explanation.get_image_and_mask`, I get different regions of the image highlighted as green and red. I keep all the parameters even after providing same seed value in `explainer.explain_instance  `.

Some of the results are as under.

**Run_1:**
![run_1](https://user-images.githubusercontent.com/31172014/85247899-a4b87b80-b492-11ea-9ed8-94e5b39cce11.png)

**Run_2:**
![Run_2](https://user-images.githubusercontent.com/31172014/85247924-bdc12c80-b492-11ea-9c62-34800735379a.png)

**Run_3:**
![run_3](https://user-images.githubusercontent.com/31172014/85247957-d03b6600-b492-11ea-8841-f9a402f3f1dc.png)

I used the following parameters for the above explanation.
```
%%time
# Hide color is the color for a superpixel turned OFF. Alternatively, if it is NONE, the superpixel will be replaced by the average of its pixels
explanation = explainer.explain_instance(X_train_0, new_predict_fn, top_labels=2, hide_color=0, num_samples=10, random_seed=10)

temp, mask = explanation.get_image_and_mask(explanation.top_labels[0], positive_only=False, num_features=10, hide_rest=False)
plt.imshow(mark_boundaries(temp / 2 + 0.5, mask))
```

**Comment by marcotcr** [comment]
The `random_seed` only impacts the segmentation (this is a bug in documentation I guess). If you want to get the same explanation again and again, you need to restart the explainer and set `random_state`, or do it by hand.
