### ISSUE TITLE
Undesirable progress bar

### ISSUE THREAD

**Issue by palatos** [marcotcr/lime#480]
Recently I started getting this progress bar when using explain_instance() for image explanations.
![image](https://user-images.githubusercontent.com/49554605/86193169-a5e84900-bb21-11ea-8012-e2dc995e98d5.png)
I have a code that runs this function many times, so these progress bars are generating a lot of unnecessary output and this also seems like it might be slowing the code down a bit.

Is there any way to turn this off? It seems to be a relatively recent behavior. I've been using this particular code for the past 2 years without this happening.

Thanks in advance for any clarification.

**Comment by marcotcr** [comment]
Made it optional in 26f2590da45aa402fc94f046e5d8e6f6cf32b32b
Call explain_instance with `progress_bar=False`

**Comment by palatos** [comment]
Thanks!

**Comment by ngjinshan** [comment]
Hi there, I am receiving an error:
explain_instance() got an unexpected keyword argument 'progress_bar'
