### ISSUE TITLE
plot

### ISSUE THREAD

**Issue by kaixiyang** [marcotcr/lime#481]
Hi Marco,

Could I get some advice on the plot of LIME ? I got the explanation plot for individual instances by using exp.as_pyplot_figure(), I am wondering if there is any other way to get the plots of predicted value from HTML by using python?

**Comment by marcotcr** [comment]
Hi there,
Sorry, we don't have a way of pulling out components from the html visualization. The predicted probabilities should be trivial to plot on your own as a bar chart though.
