### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by Dola47** [marcotcr/lime#486]
Hi All,

I wonder why a lot of people mentioned that LIME has randomness in its explainability as in #67.

I see that for example in LimeTabularExplainer random seed is internally used even if it is not defined by the user. Accordingly, given that also random seed is used in the model and the prediction function yield every call the same probability we will always get the same explanation out of LIME for the same instance for, even if we called it more than once, Am I right? 

I see that the only way to get a different explanation for the same instance is to pass different random_state to the explainer in different calls.

Please, inform me if I am getting this point correctly or not?

**Comment by marcotcr** [comment]
The random seed is set when you initialize the explainer, not when you run `explainer.explain_instance`. If you run that twice on the same data without resetting the seed, you will get mildly different explanations.

**Comment by Dola47** [comment]
@marcotcr  Thanks a lot for your response.

In my case, I am not setting any random seed in the explain_instance function. Instead, I am using a random seed in my model so the prediction of my model is always the same, and a random seed as well in my dataset. Though I am usually getting the same split out of my dataset and I am training my model on the same split of the data and explaining the same set of instances.  

I see that is normal that I am getting the same explanation even I am not applying any random seed in the explain_instance function and that is because of the random seed in my dataset and random seed in my model because then the predictions of the model for the same instance is fixed, and I see that the perturbation of LIME in the data_inverse will be the same for each specific instance because it is based on the dataset which is fixed now. Am I right?

**Comment by marcotcr** [comment]
It is a little surprising that you get the same exact explanations. The perturbations in data_inverse should not be the same, since they depend on calls to random functions, [here](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L511) and [here](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L542)

**Comment by Dola47** [comment]
@marcotcr If I am usually using the same random seed, same training data, same num_samples, and same num_cols is not it okay that I get usually the same explanation?
