### ISSUE TITLE
Fidelity metric

### ISSUE THREAD

**Issue by twi09** [marcotcr/lime#487]
Hi !
I want to compute a fidelity metric with LIME for numerical features. 
The prediction of the local model for an example to explain is define as the sum of the coefficient plus the intercept, so I deduce that the example to explain is a vector of 1. 
How to calculate the prediction of the local model for other points of my dataset ?
(I choose discretization_continuous=True) 
Thank you !

**Comment by marcotcr** [comment]
We compute the score and return it in the explanation under `explanation.score`, see [this](https://github.com/marcotcr/lime/blob/7af1ef2f8267c6097b85ec35323d8d41258e2067/lime/lime_base.py#L194). If you want to actually compute it yourself, you have to scale and discretize the data before applying the explanation as a model, see the lines after [this](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L340).
