### ISSUE TITLE
Mutiple Training Attributes Error for Multi-Class Classification Task with Tabular Explainer

### ISSUE THREAD

**Issue by safieurrahman** [marcotcr/lime#489]
Hi. I am trying to use the LIME recurrent tabular Explainer with a modified CNN model for a multi-class classification task. The said implementation passes the training attributes as [X_a_train, X_t_train] to the model (first layer is embedded layer). The explainer works fine but the 'explain instance' gives the following error when i am stacking the arrays i.e X_a_test[0], X_t_test[0] and passing it to the explainer. 

Alternatively, i can't pass the above arrays as a list as i conventionally do to get predictions from the model as the implementation can't take the transpose of Lists. 

I am new in this area and I'll be very thankful for your guidance. Here is the code,

input1 = X_a_train
input2 = X_t_train

merged_array = np.stack([input1,input2], axis=1)
merged_array= merged_array.transpose(0, 2, 1) //to match the required shape

explainer = lime.lime_tabular.RecurrentTabularExplainer(training_data=merged_array, training_labels=y_a_train, mode='classification',feature_names = features_name)

merged_array_test = np.stack([X_a_test[0], X_t_test[0]], axis=1)

exp = explainer.explain_instance(merged_array_test, classifier_fn = best_model.predict , num_features=2)
exp.show_in_notebook(show_all=True)

![image](https://user-images.githubusercontent.com/14291375/87725510-b7864d80-c7bd-11ea-9c54-2383d6f63fad.png)

**Comment by marcotcr** [comment]
Have you checked out [this](https://github.com/marcotcr/lime/blob/master/doc/notebooks/Lime%20with%20Recurrent%20Neural%20Networks.ipynb) for an example of the input formats?

**Comment by safieurrahman** [comment]
Thankyou for the reply. The issue is, the model (authored by someone else) expects a list of 2 inputs (one input is attribute sequence, other is time) So if i pass the inputs as list to explain_instance, the lime package code in that case, throws an error because it tries to flatten the input by taking transpose as in the figure below. Else the above error occurs

![image](https://user-images.githubusercontent.com/14291375/87836128-5e86ea00-c88f-11ea-8c24-a27f4e9151ba.png)

**Comment by marcotcr** [comment]
You can always write a wrapper around the model's prediction function, and preprocess the data before you give it to the model or the prediction before you output it to LIME. Does this make sense?

**Comment by safieurrahman** [comment]
Thankyou so much. I'll try this. 
If you have any code example for such input, that'd be really helpful.

**Comment by marcotcr** [comment]
See [this](https://github.com/marcotcr/lime/issues/334#issuecomment-500066991), or [this](https://github.com/marcotcr/lime/issues/233#issuecomment-439512801), or [this](https://github.com/marcotcr/lime/issues/172#issuecomment-378424436), or #51

**Comment by marcotcr** [comment]
Actually, [this](https://github.com/marcotcr/lime/issues/267#issuecomment-449122059) may be the most relevant link.

**Comment by safieurrahman** [comment]
Here is an update with a wrapper function. Error still persists.

Code:

input1 = X_a_train
input2 = X_t_train

merged_array = np.stack([input1,input2], axis=1)
merged_array= merged_array.transpose(0, 2, 1) //to match the required shape

explainer = lime.lime_tabular.RecurrentTabularExplainer(training_data=merged_array, training_labels=y_a_train, feature_names = features_name)

merged_array_test = np.stack([X_a_test[0], X_t_test[0]], axis=1) //to get 2d array (13,2) of shape (samples, features)

def classifier_pred(input_data):
    act = input_data[:,0]
    tim = input_data[:,1]
    pred = best_model.predict([act,tim]) //same format which would predict normally but generate error here
    return pred.flatten()

exp = explainer.explain_instance(merged_array_test,classifier_pred(merged_array_test),num_features=2)
exp.show_in_notebook(show_all=True)

![image](https://user-images.githubusercontent.com/14291375/88437803-8fbf6700-ce07-11ea-8c7f-144e61a03c79.png)

Error Explanation:

But both the arrays in the input list have the dimension (13,)

How can this work please? Thanks in advance for your help.

**Comment by safieurrahman** [comment]
Thankyou so much Marco for your help. I have got some progress. I'll need help with just one more thing hopefully.

Code:

```
def classifier_pred(input_data):
    act = input_data[:,0:13]
    tim = input_data[:,13:26]
    preds = best_model.predict([act,tim])
    return preds

merged_array_test = np.hstack((X_a_test[0:1], X_t_test[0:1])) //shape (1,26)
exp = explainer.explain_instance(merged_array_test, classifier_pred, num_features=2)
exp.show_in_notebook(show_all=True)
```

With this code, i get this error;
![image](https://user-images.githubusercontent.com/14291375/88864095-b238f200-d204-11ea-991b-e89227372a68.png)

But when i pass 'classifier_pred(merged_array_test)' as parameter, it gives this error,
![image](https://user-images.githubusercontent.com/14291375/88864284-1e1b5a80-d205-11ea-9d4b-3c80dade395a.png)

I know from the previous issues that the latter is not right, but when i pass a list as X_a_test[0:5], X_t_test[0:5] in merged_array_test, i get shape errors from Lime_Tabular. Could you please guide me what am i doing wrong here? I've consulted the above issues as you mentioned but i'll need some help here. I'll be very grateful.

**Comment by marcotcr** [comment]
`5000` is the default number of perturbed instances. You should make sure your `classifier_pred` takes in an array of instances rather than a single one (I did not check carefully).

**Comment by safieurrahman** [comment]
Thankyou. I tried that too. For an array of instances, i get the following error with this code or with horizontal stack function even

```
merged_array_test = np.stack([X_a_test[0:100], X_t_test[0:100]], axis=1) //100 instances
merged_array_test = merged_array_test.transpose(0, 2, 1) // resulting shape (100,13,2)

exp = explainer.explain_instance(merged_array_test, classifier_pred, num_features=2)
exp.show_in_notebook(show_all=True)
```

![image](https://user-images.githubusercontent.com/14291375/89686017-c7e1a200-d8fd-11ea-8747-5b6ff2bf3001.png)

I am really sorry to trouble you time and time again but this chunk is important to me for my thesis project and that's why i had been bothering you lately.

Best Regards.

**Comment by marcotcr** [comment]
The input to `explainer.explain_instance` should be an (d,) array, i.e. an array with a single instance. The explainer will then perturb it and give a `(5000, d) ` array (5,000 instances) to classifier_pred, i.e. classifier_pred should take as argument a 2d array with shape `(nsamples, dimension)`
