### ISSUE TITLE
Porting of LIME

### ISSUE THREAD

**Issue by thomasp85** [marcotcr/lime#49]
Hi

I'm planing an R port of LIME, and in that regard I just want to give you a heads up and hear whether you would have any problem with this and whether you would object to me using the name "lime" for the package (it could either confuse or help users, idk)

best
Thomas

**Comment by christophM** [comment]
Hi Thomas, I would be interested in helping with the R package. Are you looking for contributors? I program both in R and Python.

**Comment by marcotcr** [comment]
No problem at all. I've had a few people ask me about an R version, and I always tell them I am not going to be the one to do it.
Using the same name is fine, but please link back to the 'official' version (this one). When you have something that works, let me know and I'll link to it from this one too.

**Comment by thomasp85** [comment]
Hi @christophM - I'll let you know once I get something on GH. Contributions are welcome!

**Comment by thomasp85** [comment]
I've just added the WIP code to GitHub (https://github.com/thomasp85/lime). I claim no functionality yet, so you shouldn't link back to it ATM. I'll give an update once I have a stable working framework...
