### ISSUE TITLE
Visualization is not displayed correctly

### ISSUE THREAD

**Issue by opostavnicha** [marcotcr/lime#490]
<img width="412" alt="Screen Shot 2020-07-15 at 3 35 00 PM" src="https://user-images.githubusercontent.com/58147438/87587957-db0fa200-c6b0-11ea-8db8-5eea1ac68644.png">

Greetings! I have been trying to implement explanations for my BERT model and I couldn't get them displayed nicely (letters are overlapping).

**Comment by marcotcr** [comment]
Can you provide a small example we can reproduce? It looks like you're doing multiclass classification, but that your prediction probabilities do not sum to 1.

**Comment by opostavnicha** [comment]
> Can you provide a small example we can reproduce? It looks like you're doing multiclass classification, but that your prediction probabilities do not sum to 1.

Thanks for the tip! Applying softmax solved the issue.
