### ISSUE TITLE
Get feature weights

### ISSUE THREAD

**Issue by bharat-patidar** [marcotcr/lime#491]
Hi,

Thanks for sharing this wonderful repository.

I was just wondering if there exists any API or function call which can give me coefficients/importance of features generated by LIME for the local surrogate model.

Thanks!

**Comment by marcotcr** [comment]
`explanation.as_list`, or `explanation.as_map`

**Comment by bharat-patidar** [comment]
Thanks @marcotcr 
That's what I am looking for!
