### ISSUE TITLE
Mismatch between highest contribution of features and class prediction

### ISSUE THREAD

**Issue by mike1130694** [marcotcr/lime#492]
Hi
I've been reviewing the open and closed issues and documentation to try to find out if the situation I've found is an issue or if I am interpreting something wrong.

My problem is related to these two issues
Issue 438 [https://github.com/marcotcr/lime/issues/438](url)
Issue 343 [https://github.com/marcotcr/lime/issues/343](url)

I am doing a binary classification with two target classes 
0 = Rejected
1 = Approved

The random forest classifier predicts class "Approved" with a probability of 0.79.
the explanation obtained using lime displays the same probabilities

```
rfc.predict(x.loc[[51]])
Out[15]: array([1], dtype=int64)

rfc.predict_proba(x.loc[[51]])
Out[16]: array([[0.2024701, 0.7975299]])

exp.predict_proba
Out[13]: array([0.2024701, 0.7975299])
```

However, as you can see in the image below, most of the feature contributions are negative which would contribute to the prediction being "Rejected" instead of "Approved".

I've been trying to interpret this explanations but I am having problems. According to one of your tutorials

"For categorical features, the feature contribution is always the same as the linear model weight."

I wonder how does the contribution for numerical features is calculated. 
According to this book [https://christophm.github.io/interpretable-ml-book/lime.html](url), "The effect on the prediction is the weight times the actual feature value". Is this information correct?

I am having a problem when limiting the number of features that are display. If I select the top 5 contributions most of them would be negative which is somehow contradictory of the predicted class and the probability.

Could you please give me your thoughts on this situation or clarify me if I am understanding something wrong?

![image](https://user-images.githubusercontent.com/15694432/88090390-ce49ed00-cb8d-11ea-9ed5-be9028e8086a.png)

Thanks in advance

**Comment by marcotcr** [comment]
See #304, #246, maybe #210.  I'm guessing your intercept is high for class approved, let me know if these issues don't solve it for you.
