### ISSUE TITLE
LIME for traffic lane detection

### ISSUE THREAD

**Issue by M-I-Dx** [marcotcr/lime#493]
Is it possible to use LIME on a lane detection model? The input of my model is

![image](https://user-images.githubusercontent.com/52869386/88334516-883c8700-cd4f-11ea-8a5e-dfdc71837910.png)

and the output is 
![image](https://user-images.githubusercontent.com/52869386/88334561-99859380-cd4f-11ea-8d1d-6a06257eefee.png)

If yes, how should I go about doing it?

**Comment by marcotcr** [comment]
You can explain a property of the output that is continuous or categorical (e.g. how many lanes there are, whether a particular super pixel contains a lane, etc), I don't know how you would explain a structured output like what you presented. See #124 too.
