### ISSUE TITLE
num_features for Image explanation

### ISSUE THREAD

**Issue by bharat-patidar** [marcotcr/lime#494]
Hi,
I just want to know, the meaning of _num_features_ parameter for _explain_instance_ method of _LimeImageExplainer_.
What should be the maximum value for this parameter, Is it the number of pixels for a given image?

Thanks

**Comment by marcotcr** [comment]
It's the number of superpixels that will appear in the explanation. I think for images it's best to use all of the superpixels in the explanations and filter out later when visualizing it.
