### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by CVegon** [marcotcr/lime#495]
Hello, i am using Lime for a house pricing prediction, with a different data-set of what you have on GitHub and i wanna ask how can i show the actual price and the features values from XAI, because when i don't normalize my data the XAI looks bad and the bar that show the value of a specific prediction is not there. 
![Capture](https://user-images.githubusercontent.com/37221270/88906216-d7a71980-d25f-11ea-93bf-e429e0fac76c.PNG)

**Comment by marcotcr** [comment]
If I remember correctly, we have a hack in the display where we use the min and max of the training dataset. I think your predicted value _is_ being shown, but it is too small (close to the minimum) for a bar to register. One way to confirm is to get an instance where the prediction is closer to the midrange between (min, max).

**Comment by Edakksm** [comment]
@CVegon, can you please tell me how you were able to show the original unnormalized data in LIME?

**Comment by StijnBerendse** [comment]
@Edakksm Did you ever find out how to do this? I am running into the same issue where normalized data is shown in my explanations.
