### ISSUE TITLE
Lime on Time Series Models?

### ISSUE THREAD

**Issue by shbhmpndy** [marcotcr/lime#496]
I was looking into explaining a variety of models, but when I came across Time Series I was puzzled.

I have 2 questions/concerns.
1. Is there a way to explain models built on time series data by taking time component as a feature? as in which time period/historical data impacted the current result the most? Models like ARIMA, SARIMAX, fbprophet?

2. I tried ignoring the time component and by treating a time series data as a regression with exogenous features, the explanation explained the impact of the features on the forecasted value of next timestamp, my question being is that the right way to explain?

**Comment by marcotcr** [comment]
1. Yes, but it's not easy. You'd have to write some code for perturbations which perturbs things consistently (e.g. if I change the time feature from 'today' to 'yesterday', everything else has to change accordingly. If I perturb some other feature that impacts the time feature, it has to change accordingly)

2. I actually don't know what the right way to explain time series data is. The default we have in [`RecurrentTabularExplainer`](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L579) is to treat each feature in a timestamp as a separate feature, which is clearly not the right thing, but adds the time component (as opposed to what you did).
