### ISSUE TITLE
TabularExplainer Explanations

### ISSUE THREAD

**Issue by Dola47** [marcotcr/lime#497]
Dear All,
 
1- By default, the TabularExplainer uses ridge regression to explain the black-box model.  We submit to this ridge regression the perturbed instances, their predictions, their weights. Then this ridge regression is optimized until it minimizes the loss between it and the black-box model. If all of these are correct, I would like to be sure that what we mean by the weights of the ridge regression model represent our explanations, that the explanations are the betas or the coefficients of the ridge regression model after it has been optimized? [ And the betas is related to K the number of features I needed to be returned in the explanations objects, K=10 features, means we will have 10 betas in our ridge regression, is that correct?]

2- In the case of numerical features, they are perturbed by sampling from a parameterized normal distribution for each feature. As a consequence, we lack the covariance between the features, and our whole space distribution function represents merely the product of several normal distributions. Therefore, we can have certain samples out of our original dataset, is that correct?

3- For the categorical features, sampling is perturbed by the frequency of the appearance of each category in the training distribution. The worst scenario that might come out of this method is that if one of the categories is very rare and is not selected because of bad luck, and since after the sampling phase is finished, we no longer have the original dataset. Consequently, there is no information on this category for the fitting of the interpretable model, is that also correct?

4- If the perturbation depends merely on our dataset statistics, how can we say that our perturbation is usually random for the same dataset?

Many thanks.

**Comment by marcotcr** [comment]
1. Yes, your understanding is correct.
2. It depends on whether you discretize or not, but if you don't your understanding is correct. Notice that there is weighting based on distance to the instance being explained, so you don't quite get a multivariate normal with diagonal covariance matrix in the end.
3. Yes, this is correct. However, notice that if a categorical value is infrequent enough and it is not the value of the instance being explained, its effect would likely wash out even if we did sample from it.
4. I don't understand the question. Saying that the perturbations are random is saying that they are not deterministic, just like we talk about drawing random samples from a uniform distribution with fixed parameters.

I hope this helps.
