### ISSUE TITLE
Heapmap displayed superpixel and superpixel bbox coordinates mismatch

### ISSUE THREAD

**Issue by wyzrxrs** [marcotcr/lime#502]
Hello,
I am trying to obtain the coordinates for the most positive (green) superpixels explained by Lime. 
From the explainer, I would like to look at the values for the 2nd label.

```
ind =  explanation.top_labels[1]
#explanation.local_exp is a dictionary of feature-value tuple
dict(explanation.local_exp[ind])
dict_heatmap = dict(explanation.local_exp[ind])
heatmap = np.vectorize(dict_heatmap.get)(explanation.segments) 
plt.imshow(heatmap, cmap = 'RdBu', vmin  = -heatmap.max(), vmax = heatmap.max())
plt.colorbar()
```

This returns the following as well as the heatmap.
`{73: 8.481317791109838,
 74: -4.06675314187661,
 58: -3.9375791012265053,
...}`

Then I use the following to obtain the superpixel No.73 with its bbox, since it has the highest value.

```
import skimage.io 
import skimage.segmentation
superpixels = skimage.segmentation.quickshift(image_to_explain, kernel_size=4,max_dist=200, ratio=0.2)
#Accessing Individual Superpixel Segmentations with Python
K=skimage.measure.regionprops(superpixels)
print(K[73].bbox)
```

The coordinates returned is (212, 340, 249, 383). 
However, while looking at the heatmap, the coordinates of the bbox do not match the darkest color area. I tried to get K[72].bbox, and it matches.

I verified the quickshift algorithm used by Lime to generate the superpixels, and its parameters. Also verified the order of the coordinates (y_min, x_min, y_max, x_max). But I can't find the reason why the superpixel box coordinates do not match the green area. 

Could you please help with this issue? 
Thanks!

**Comment by marcotcr** [comment]
You can access the segmentation LIME used directly rather than recomputing, `explanation.segments`.  We also have  a bunch of helper functions, check out [this tutorial](https://github.com/marcotcr/lime/blob/master/doc/notebooks/Tutorial%20-%20images%20-%20Pytorch.ipynb)
