### ISSUE TITLE
Issue with Tutorial - Image Classification Keras notebook

### ISSUE THREAD

**Issue by leszekmp** [marcotcr/lime#505]
Tensorflow 2.3.0, Keras 2.4.3, scikit-image==0.17.2, scikit-learn==0.23.1.

Running the notebook without changes, works fine until I hit the step:

%%time
 Hide color is the color for a superpixel turned OFF. Alternatively, if it is NONE, the superpixel will be replaced by the average of its pixels
explanation = explainer.explain_instance(img[0], inet_model.predict, top_labels=8, hide_color=0, num_samples=1000)

Following error comes up:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed exec> in <module>

~\AppData\Roaming\Python\Python37\site-packages\lime\lime_image.py in explain_instance(self, image, classifier_fn, labels, hide_color, top_labels, num_features, num_samples, batch_size, segmentation_fn, distance_metric, model_regressor, random_seed)
    182             segments = segmentation_fn(image)
    183         except ValueError as e:
--> 184             raise e
    185 
    186         fudged_image = image.copy()

~\AppData\Roaming\Python\Python37\site-packages\lime\lime_image.py in explain_instance(self, image, classifier_fn, labels, hide_color, top_labels, num_features, num_samples, batch_size, segmentation_fn, distance_metric, model_regressor, random_seed)
    180                                                     random_seed=random_seed)
    181         try:
--> 182             segments = segmentation_fn(image)
    183         except ValueError as e:
    184             raise e

~\AppData\Roaming\Python\Python37\site-packages\lime\wrappers\scikit_image.py in __call__(self, *args)
    115 
    116     def __call__(self, *args):
--> 117         return self.target_fn(args[0], **self.target_params)

~\AppData\Roaming\Python\Python37\site-packages\skimage\segmentation\_quickshift.py in quickshift(image, ratio, kernel_size, max_dist, return_tree, sigma, convert2lab, random_seed)
     71     segment_mask = _quickshift_cython(
     72         image, kernel_size=kernel_size, max_dist=max_dist,
---> 73         return_tree=return_tree, random_seed=random_seed)
     74     return segment_mask

skimage\segmentation\_quickshift_cy.pyx in skimage.segmentation._quickshift_cy._quickshift_cython()

ValueError: Buffer dtype mismatch, expected 'double' but got 'float'

**Comment by marcotcr** [comment]
Keras or skimage changed a bit since we wrote that tutorial. You just have to do:
`images[0].astype('double')` as the argument, so that it looks like:
```
explanation = explainer.explain_instance(images[0].astype('double'), inet_model.predict, top_labels=5, hide_color=0, num_samples=1000)
```
Updated the tutorial in 91238dd
Thanks
