### ISSUE TITLE
Why lime text explainer does not return Class Label?

### ISSUE THREAD

**Issue by SharathChandra-AV** [marcotcr/lime#510]
Hello Marco,
Saw your article about LIME. Its fantastic...
 I trained few ML.NET classifiers for the text data.
However, when i try to use LimeTextExplainer, it always throws some linkage related errors
    explainer = lt.LimeTextExplainer(class_names=set(df['Label']))

Can you please let me know if there is compatibility between the ML.NET and LIME explainers to make it work?
Thanks
Sharath

**Comment by marcotcr** [comment]
I know nothing about ML.NET, sorry. You should be able to run LIME on regular python though...

**Comment by SharathChandra-AV** [comment]
Oh! My bad. I didnt provide full details.
I used NimbusML , a python module which is actually a wrapper on top of ML.NET classifiers.
So, below is some sample code 
pipe = Npipe([
                NGramFeaturizer(word_feature_extractor=Ngram(weighting = 'Tf')), 
                PcaTransformer(rank = 100),
                FastTreesBinaryClassifier(number_of_trees=200,), # nimbusml learner
               ])
        X = df[textcol]
        Y = df[targetcol]
        pipe.fit(X, Y) 

So, once this classifier gets trained, i am using the probabilities to get the local explanation for a sample text.
Which is where I see LIME is not extracting the explanations and throwing some errors... 
I tried to print the probabilities from the classifiers on the test set, which it printed though correctly...
So just want to check if LIME can work on any kind of classifier as by definition it is MODEL AGNOSTIC...?
Please let me know...

**Comment by marcotcr** [comment]
It should work on any classifier. What error do you get? And what output do you get if you run the following?
```python
pipe(['John is a man', 'John is not a man'])
```

**Comment by SharathChandra-AV** [comment]
I think it failed for both single string and list of strings.
Below are the last lines of errors i got when i run the code:

For a sample document
        sample = 'John is a man'
        explainer = lt.LimeTextExplainer()
        Obj_le = explainer.explain_instance(doc, clf.predict_proba)
        features = Obj_le.as_list()
BridgeRuntimeError: Error: *** System.InvalidOperationException: 'Incompatible features column type: 'Single' vs 'Vector<Single, 100>''

For list of sample documents
samples = ['John is a man','John is a simple man']
explainer = lt.LimeTextExplainer()
Obj_le = explainer.explain_instance(samples, pipe_mlnet.predict_proba)
features = Obj_le.as_list()
TypeError: expected string or bytes-like object

**Comment by marcotcr** [comment]
what output do you get if you run the following?

`pipe(['John is a man', 'John is not a man'])`
