### ISSUE TITLE
Does LIME works with a model having CNN and GRU both in their layers.

### ISSUE THREAD

**Issue by Dipanjan-chatterjee** [marcotcr/lime#511]
Hi All,

I am trying to use LIME in the interpretation of the Bioinformatics problem where I want to find the relevancy of input features on the model's prediction. My model has both CNN and a Bidirectional GRU layer in it. I was wondering if LIME can be applicable in that scenario? Thanks,

-Dipanjan

**Comment by marcotcr** [comment]
LIME is model-agnostic, so it doesn't matter what your model is. What you have to figure out is if the kind of data you have is compatible with the explainers we have available.
