### ISSUE TITLE
LimeTextExplainer returns a lot zeros only explanations

### ISSUE THREAD

**Issue by fuuman** [marcotcr/lime#513]
OS: Manjaro x64
Python: 3.6.11
Lime: 0.1.1.32

I am using LimeTextExplainer to explain instances of different models (Logistic Regression, SVM, XGBoost, etc.).
Explaining round about 800 instances always results in 300-400 explanations that contain zeros only. 

For example:
Instance: ['This', 'ball', 'is', 'red', 'and', 'gold']
Explanation: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

I thought it might be the length of the data instance but it's not. There is no pattern on first view. I have very short instances with "real" explanations and very short with only zeros. Same for long ones.

Code: 
```
explainer = LimeTextExplainer()
exp = explainer.explain_instance(text, clf.predict, num_features=len(text.split()), num_samples=1000)
```

Any idea what I miss?

**Comment by marcotcr** [comment]
Since you're using default parameters, LIME will remove words at random.
Is it the case that the prediction of your model is constant for all variations of 'This ball is red and gold'?
i.e. what output do you get if you run the following?
```python
clf.predict(['This ball', 'This', 'This ball is red', 'This ball is red gold', 'This ball is red and gold'])
```

I suggest using `predict_proba` to get a bit of signal from the prediction probability

**Comment by fuuman** [comment]
@marcotcr So I guess you alluded to `feature_selection` param of the LimeTextExplainer class. 
Which setting do I have to use to solve that? Considering I would want to get explanations even for very short input texts where removing words leads to the same prediction every time.

**Comment by marcotcr** [comment]
The alternative to removing words is using mask tokens, by setting `bow=False`. However, if your model always predicts the same thing and you don't output a prediction probability, there is no way to get any sort of meaningful explanation (which is why I suggested using predict_proba)

**Comment by fuuman** [comment]
I did that. And yes, there are less tweets with no meaningful explanation, but they still exists. Of 800 instances, I have still over 300 instances with explanations containing zeros only (while using predict_proba).

**Comment by marcotcr** [comment]
It could be that your model is not changing prediction probabilities much around those perturbations and / or that the explanation is just the intercept (see #304, for example).
