### ISSUE TITLE
Installing slicer issues

### ISSUE THREAD

**Issue by sreekarreddy21** [marcotcr/lime#514]
I wanted to use "shap", which has failed because of the below error. I tried to install slicer, but the same error has occured. Could you please help with this? 

Collecting slicer==0.0.4
  Could not find a version that satisfies the requirement slicer==0.0.4 (from versions: )
No matching distribution found for slicer==0.0.4

**Comment by marcotcr** [comment]
perhaps try posting this on the [shap repo](https://github.com/slundberg/shap)
