### ISSUE TITLE
What can we interpret  the x-axis in the LIME graph in case of regression & classification?

### ISSUE THREAD

**Issue by husnain25** [marcotcr/lime#515]
I reproduced this graph from official tutorial. I cannot understand how can I interpret the values on the  x-axis in this case? Could you please also explain how can I interpret these values in case of classification too? Thanks.
@marcotcr 
![lime graph](https://user-images.githubusercontent.com/66378401/94774907-34e25700-03d8-11eb-9525-24e397c3fe58.PNG)

**Comment by marcotcr** [comment]
See #113
