### ISSUE TITLE
Question regarding the interpretration of word probability contributions

### ISSUE THREAD

**Issue by jusugac1** [marcotcr/lime#516]
Hello all,

I have a question regarding the individual interpretation for word probability contributions using LIME. I obtained the following figure (I removed the words as I am not authorized to share any data):

![image](https://user-images.githubusercontent.com/32885492/94827388-a76b2b00-0408-11eb-8b70-aa04dc94f284.png)

There, we can see that the class "Recessive Disturbance" (in orange) has a total probability of 0.02. However, there are three words appearing in the top 10 that contribute to this class and whose independent probability contributions are larger than 0.02. Then, how is this possible that the class probability is inferior to independent probability contributions?

Thank you for your answer,

J.

**Comment by marcotcr** [comment]
We don't really guarantee that the sum of everything will be the outcome, but it should be close.
Anyway, to answer your question: you just need the sum of the intercept and the weights for the blue features to be more than 1. You can imagine an extreme example where the intercept is 0.5, the prediction is 0.5, and two features with contribution (+0.6) and (-0.6) cancel out.

**Comment by jusugac1** [comment]
Hello Marco,

Thank you for your answer. I have just a question, what do you call the intercept? What I understand is that, in my case, the sum for the blue features is giving more than 1, thus cancelling the 'extra' sum for the orange features. However, I'd like to understand what you call 'intercept'.

Have a nice day,

J.

**Comment by marcotcr** [comment]
`exp.intercept` will give you the 'base rate', as it were
