### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'as_matrix'

### ISSUE THREAD

**Issue by nicolezk1** [marcotcr/lime#517]
When I tried executing the code from https://marcotcr.github.io/lime/tutorials/Tutorial_H2O_continuous_and_cat.html, I received the following error:

> -------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-50-06bce9068369> in <module>
>       4 # exp = explainer.explain_instance(test[i], rf.predict_proba, num_features=2, top_labels=1)
>       5 
> ----> 6 exp = explainer.explain_instance(test_numpy_array[i], h2o_drf_wrapper.predict_proba, num_features=2, top_labels=1)
> 
> ~/miniconda3/envs/safety/lib/python3.8/site-packages/lime/lime_tabular.py in explain_instance(self, data_row, predict_fn, labels, top_labels, num_features, num_samples, distance_metric, model_regressor)
>     353         ).ravel()
>     354 
> --> 355         yss = predict_fn(inverse)
>     356 
>     357         # for classification, the model needs to provide a list of tuples - classes
> 
> <ipython-input-28-a4e858799e91> in predict_proba(self, this_array)
>      22         # the first column is the class labels, the rest are probabilities for
>      23         # each class
> ---> 24         self.predictions = self.predictions.iloc[:,1:].as_matrix()
>      25         return self.predictions
> 
> ~/miniconda3/envs/safety/lib/python3.8/site-packages/pandas/core/generic.py in __getattr__(self, name)
>    5128             if self._info_axis._can_hold_identifiers_and_holds_name(name):
>    5129                 return self[name]
> -> 5130             return object.__getattribute__(self, name)
>    5131 
>    5132     def __setattr__(self, name: str, value) -> None:
> 
> AttributeError: 'DataFrame' object has no attribute 'as_matrix'

I believe it's beacuse of my pandas version (1.1.1). From what I've read here: https://stackoverflow.com/questions/60164560/attributeerror-series-object-has-no-attribute-as-matrix-why-is-it-error , the `as_matrix` method is deprecated since version 0.23.0

I suggest changing the code from `as_matrix()` to `to_numpy()` in this case, to provide support for later versions of pandas. Is this something being worked on already?

**Comment by marcotcr** [comment]
I should probably just remove this tutorial instead of trying to keep it current. The predict_fn in this case has nothing to do with LIME anyway.

Thanks,

**Comment by 6littlestar7** [comment]
thanks its working
