### ISSUE TITLE
Get training data

### ISSUE THREAD

**Issue by filipe-tatarli** [marcotcr/lime#518]
Hi, 

How do I get the distorted data that LIME creates ? I mean, I'm running this piece of code ...

```
exp = explainer.explain_instance(observation2.values[0]
                                 ,predict_fn
                                 ,num_features=10
                                 ,num_samples = 100)
```
... so I imagine that LIME would create 100 new inputs with disturbed data. Is it possible to get this 100 new records ?

Thanks, 

Filipe

**Comment by marcotcr** [comment]
We don't return the perturbation data with the explanation. If you want to take a peak, check out [these lines ](https://github.com/marcotcr/lime/blob/master/lime/lime_text.py#L413)for LimeText and [these ones ](https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L346) for LimeTabular
