### ISSUE TITLE
LimeTabularExplainer for 3D Input

### ISSUE THREAD

**Issue by GlorianY** [marcotcr/lime#519]
I am working on a regression problem with LSTM (TensorFlow 2.0). 
As we all know, the input shape of LSTM is 3D which composed of (#samples * #timestep * #features).

When I try to use my training data (3D input shape) on the training_data parameter of LimeTabularExplainer, I got an error::
```
IndexError: boolean index did not match indexed array along dimension 1; dimension is 1 but corresponding boolean dimension is 13
```
Note that, 13 is the number of features.

My question is, how to use LimeTabularExplainer when the shape of both my training data and test data is 3D?

**Comment by marcotcr** [comment]
Check [this](https://github.com/marcotcr/lime/blob/master/doc/notebooks/Lime%20with%20Recurrent%20Neural%20Networks.ipynb) out

**Comment by GlorianY** [comment]
Thanks! Apologies that I missed it in the documentation.
