### ISSUE TITLE
Keras Image Binary Classifier Error

### ISSUE THREAD

**Issue by connor11son** [marcotcr/lime#520]
Hi there, I am trying write an explainer for a simple binary image classifier in Keras.

Here is my model:

    model = Sequential()
    model.add(layers.Conv2D(filters = 24, kernel_size = (3,3), padding='valid', activation = 'relu', input_shape = (227,227,3)))
    model.add(layers.MaxPool2D(strides = (2,2), pool_size = (3,3)))
    model.add(layers.Flatten())
    model.add(layers.Dense(128, activation = 'relu'))
    model.add(layers.Dense(64, activation = 'relu'))
    model.add(layers.Dense(1, activation = 'sigmoid'))

    optimizer = tf.keras.optimizers.SGD()
    loss = 'binary_crossentropy'
    model.compile(optimizer = optimizer, loss = loss, metrics=['accuracy'])
    model.fit(x = train_generator, epochs=1000)

And here is my explainer:

    def predict_fn(x):
        model.predict(img.reshape(1,227,227,3)*1./255)

    explainer = lime_image.LimeImageExplainer()
    explanation = explainer.explain_instance(img, predict_fn(img), top_labels=1, hide_color=0, num_samples=100)

And here is the error:

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <timed exec> in <module>

    ~\Anaconda3\lib\site-packages\lime\lime_image.py in explain_instance(self, image, classifier_fn, labels, hide_color, top_labels, num_features, num_samples, batch_size, segmentation_fn, distance_metric, model_regressor, random_seed)
    198         data, labels = self.data_labels(image, fudged_image, segments,
    199                                         classifier_fn, num_samples,
    --> 200                                         batch_size=batch_size)
        201 
    202         distances = sklearn.metrics.pairwise_distances(

    ~\Anaconda3\lib\site-packages\lime\lime_image.py in data_labels(self, image, fudged_image, segments, classifier_fn, 
        num_samples, batch_size)
        259             imgs.append(temp)
        260             if len(imgs) == batch_size:
    --> 261                 preds = classifier_fn(np.array(imgs))
        262                 labels.extend(preds)
        263                 imgs = []

    TypeError: 'NoneType' object is not callable

Thank you!

**Comment by marcotcr** [comment]
```python
explanation = explainer.explain_instance(img, predict_fn(img), top_labels=1, hide_color=0, num_samples=100)
```
should instead be
```python
explanation = explainer.explain_instance(img, predict_fn, top_labels=1, hide_color=0, num_samples=100)
```
Also, your `predict_fn` should not take one image, but N Images (i.e. no need to reshape)
