### ISSUE TITLE
how to validate lime explanation on images

### ISSUE THREAD

**Issue by dsvrsec** [marcotcr/lime#522]
Is there any way to validate lime explanation on images? and is there any way to quantify this explanation,if possible.

**Comment by marcotcr** [comment]
I don't know what you mean by 'validate'. You can certainly create perturbed instances, get predictions, and verify that the explanation indeed is faithful to what the model is doing (or you can look at `explanation.score` to get a summary). Whether the explanation is useful or not is another story - it depends on how you are using it, whether the perturbation function we are using makes sense for the application (masking superpixels with grey), etc.
