### ISSUE TITLE
How to set number of samples parameter

### ISSUE THREAD

**Issue by dsvrsec** [marcotcr/lime#524]
Are there any best practices to set the number of samples parameter for a particular image explanation and does this depend on features of image(like colour etc) which is given as input

**Comment by marcotcr** [comment]
It depends on the number of superpixels in the image, and on the behavior of your model. It really depends, but a rule of thumb is that you should use at least ~10 per superpixel, which typically means setting it to ~1000

**Comment by dsvrsec** [comment]
I assume that number of super pixels is automatically selected by segmentation algorithm.Then, is there any way to know this before itself

**Comment by marcotcr** [comment]
I guess the only way is to run the segmentation algorithm beforehand, i.e. [these lines](https://github.com/marcotcr/lime/blob/master/lime/lime_image.py#L179).
