### ISSUE TITLE
Question about the data format for the function :  explain_instance_with_data

### ISSUE THREAD

**Issue by wil0u** [marcotcr/lime#525]
Hello, 

My question is the following : can we feed "scipy.sparse.csr_matrix" type (in other words : sparse matrices) for the argument : "neighborhood_data"  ?

Thanks in advance

**Comment by marcotcr** [comment]
I think it will probably work, depending on what other parameters you use. It depends if the models in `feature_selection` and `regressor` work with sparse matrix, but I think most sklearn stuff does.
