### ISSUE TITLE
LIME on medical images 

### ISSUE THREAD

**Issue by salujarohit** [marcotcr/lime#527]
Hi, 
I am working to generate explanations for a binary medical image classifier that classifies in vivo gastral images as either bleeding or non bleeding ( this is useful in medical diagnostics). The lime explanations are working reasonably well with the bleeding images ( they are highlighting the red bleeding part in the image) but they don't seem to be working well with non - bleeding images. The important pixels in the nonbleeding case are getting highlighted for very few images, for most of the images LIME is showing no explanation ( num_instances is 2500, num_features is 10). Could you please help me understand the reason? The explanations for non bleeding images are attached below.

<img width="1207" alt="Screenshot 2020-10-23 at 2 06 13" src="https://user-images.githubusercontent.com/20887328/96927304-7d22ff80-14d4-11eb-82bc-b1360bbd6945.png">

**Comment by salujarohit** [comment]
![Uploading Screenshot 2020-10-23 at 2.06.13.png…]()

**Comment by palatos** [comment]
I have observed similar behavior before in my research, on a different medical imaging classification problem. It was also a binary problem, but I was using a pretrained model, not trained by myself.
I imagine you trained the network with the healthy images being class '0'.
Just to be sure, could you train the network again from scratch, but switching the labels? Meaning, making the healthy class be '1', and then post the same results of this image again?

Also, if you are using some option like "positives_only" it's worth checking if you are generating the explanations for the correct label. Are all of the images presented true positives (i.e. correct predictions)?

**Comment by marcotcr** [comment]
I'm guessing that there is probably a large class imbalance (where most images are non-bleeding)? If so, this would explain why you get empty explanations (basically just intercept)
