### ISSUE TITLE
Does LIME work with scikit-multilearn?

### ISSUE THREAD

**Issue by Bsingstad** [marcotcr/lime#532]
I just wonder if LIME works with scikit-multilearn?

**Comment by marcotcr** [comment]
You can use it to explain the prediction of a particular label, or a combination of labels (but you have to specify what the output is). See #374

**Comment by Bsingstad** [comment]
Thanks! Yes, I found a way to use it

**Comment by Rajan316** [comment]
Can you please explain how did you use LIME with scikit mulitlearn
