### ISSUE TITLE
Handling missing values

### ISSUE THREAD

**Issue by j-adamczyk** [marcotcr/lime#535]
In the issue #122 it was explained that handling missing values e.g. for XGBoost is possible, but not yet implemented. In the R port of LIME the same problem arose and, if I understand correctly, it was handled (see (this issue)[https://github.com/thomasp85/lime/issues/8] and (https://github.com/thomasp85/lime/commit/2d806431537dd9d95a4106ecd1ab00232853ad6a)[this fix]). Can the same be done for Python version?
A very important use case for this feature motivating its importance is as follows: in medical applications not always all measurements from dataset are available, due to privacy concerns, lack of time and/or money during the visit etc., and new vectors for classification often have missing values. Using LIME can satisfy legal requirements of model explainability, making less inpterpretable but highly accurate tree ensembles like XGBoost a very viable option.

**Comment by marcotcr** [comment]
I guess my comment back from 2017 still applies:
> Anyway, this is not something I can see myself working on soon. If you are interested, we'll take a pull request : )
The fact that 3 years have elapsed since then and we got no other requests for this feature indicates to me that there is no pressing need for it.
