### ISSUE TITLE
Explainer - directly using the 2d array of prediction probabilities

### ISSUE THREAD

**Issue by icelandszt** [marcotcr/lime#536]
Hi!

Thanks for this amazing work! 

I am trying to interpret a fine-tuned BERT model. I already trained the model and prepared a 2d array of prediction probabilities for my test set. This is what I'm trying to do:

`explainer = lime.lime_tabular.LimeTabularExplainer(training_data = X_train.values, 
                                                   mode = 'classification',
                                                   training_labels = train['label']
                                                   )
idx = 1
exp = explainer.explain_instance(test[idx], prob, num_features=10, num_samples=5000)`

where _prob_ looks something like this: [[0.278 0.722]]

When I'm running this, I'm getting the following error:

`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-68-77ea6ceb8368> in <module>
      1 explainer = lime.lime_tabular.LimeTabularExplainer(training_data = X_train.values, 
      2                                                    mode = 'classification',
----> 3                                                    training_labels = train['label']
      4                                                    )

/opt/anaconda3/lib/python3.7/site-packages/lime/lime_tabular.py in __init__(self, training_data, mode, training_labels, feature_names, categorical_features, categorical_names, kernel_width, kernel, verbose, class_names, feature_selection, discretize_continuous, discretizer, sample_around_instance, random_state, training_data_stats)
    198             categorical_features = []
    199         if feature_names is None:
--> 200             feature_names = [str(i) for i in range(training_data.shape[1])]
    201 
    202         self.categorical_features = list(categorical_features)

IndexError: tuple index out of range`

My training dataset has 2 columns: the label and the text. I tried adding in the _explainer_ `feature_names = ['label','text']` but the error persists. I'm not sure what I'm doing wrong or if I misunderstood something.

Also, is this a valid approach? Can I directly use the 2d array of prediction probabilities?

Thank you for your time! 
(If you think that the question is not suitable here I can delete the post and move it to StackOverflow)

**Comment by anouar1991** [comment]
I suggest using LimeTextExplainer instead of tabular.
[this tutorial might help](https://marcotcr.github.io/lime/tutorials/Lime%20-%20basic%20usage%2C%20two%20class%20case.html)

**Comment by marcotcr** [comment]
Yep, you want to use LimeTextExplainer.
