### ISSUE TITLE
Does LIME work with Seq2Seq LSTM model?

### ISSUE THREAD

**Issue by azadetabaie** [marcotcr/lime#541]
Hi,
Thanks for the great package!

I'm working with a LSTM sequence to sequence classification model. The model takes the input of shape (n_samples, n_timesteps, n_features) and generates the output probability in this form: (n_samples, n_timesteps, 1). Basically, I need to calculate the contribution of each feature at each timestep.

Does LIME work with this type of model? 

Thanks!

**Comment by marcotcr** [comment]
Check [this ](https://github.com/marcotcr/lime/blob/master/doc/notebooks/Lime%20with%20Recurrent%20Neural%20Networks.ipynb)out.
