### ISSUE TITLE
Is it possible to explain with only part of the features?

### ISSUE THREAD

**Issue by alexnanchen** [marcotcr/lime#543]
We have a use case  that when doing predictions, not all features are interpretable from a human perspective, but some are.

Is it possible to obtain predictions with all features but have explanation with only the explainable ones? In the "explain_instance" method of the  "LimeTabularExplainer" class, we can give the number of features but not their indices.

Many thanks.

Alexandre

**Comment by marcotcr** [comment]
See #414. The short answer is: it's possible, but not supported by default.
