### ISSUE TITLE
Example for 5.3

### ISSUE THREAD

**Issue by drcooksy** [marcotcr/lime#544]
Hi, is there documentation or examples out there for implementing from your paper section 5.3 Should I trust this prediction? I can only find the data_trusting.py and would like to base my code more off of some real examples with real data but can't find any anywhere. Thank you!

**Comment by spook95** [comment]
Hi
I’m very sorry iv been in hospital give me a call call tomorrow if free thanks adam

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by drcooksy** [comment]
This looks like a clear phish ^ don't click
