### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'categorical_features', Then I renamed it from __doc__, but still not working.

### ISSUE THREAD

**Issue by rakib06** [marcotcr/lime#545]
https://marcotcr.github.io/lime/tutorials/Tutorial%20-%20continuous%20and%20categorical%20features.html

encoder = sklearn.preprocessing.OneHotEncoder(categories=categorical_features)
![image](https://user-images.githubusercontent.com/34921424/100542289-1e8b3700-3273-11eb-9cae-62e235a8bf7f.png)
![image](https://user-images.githubusercontent.com/34921424/100542305-38c51500-3273-11eb-993a-697e2772b001.png)

`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-48-1174f001a4b5> in <module>
----> 1 encoder = sklearn.preprocessing.OneHotEncoder(categorical_features=categorical_features)

/usr/local/venvs/rkb_320_projects/CNN/env/lib64/python3.6/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

TypeError: __init__() got an unexpected keyword argument 'categorical_features'

`

**Comment by Mbehbahani** [comment]
I have the same problem

**Comment by Mbehbahani** [comment]
this page can be useful:

https://stackoverflow.com/questions/59476165/typeerror-init-got-an-unexpected-keyword-argument-categorical-features

**Comment by marcotcr** [comment]
I guess the interface changed in a breaking way. For the mushroom example, you can just set `categories='auto'`. The "Numerical and Categorical features in the same dataset" example needs more changes

**Comment by sbbsangam1998** [comment]
> I guess the interface changed in a breaking way. For the mushroom example, you can just set `categories='auto'`. The "Numerical and Categorical features in the same dataset" example needs more changes

Not resolved
