### ISSUE TITLE
Allow explainers to be pickled

### ISSUE THREAD

**Issue by dstilesr** [marcotcr/lime#546]
I am using lime version lime==0.2.0.1, and I am not able to pickle explainers. I think the problem is down to the use of some lambda functions in BaseDiscretizer constructor.
Code snippet that causes the error:
```python
import pickle
from lime import lime_tabular

exp = lime_tabular.LimeTabularExplainer(xtrain.values, feature_names=list(xtrain.columns))
with open("explainer.pickle", "wb") as f:
    pickle.dump(exp, f)
```
xtrain is a pandas DataFrame.

Error message:
`AttributeError: Can't pickle local object 'BaseDiscretizer.__init__.<locals>.<lambda>'`

**Comment by marcotcr** [comment]
See #195
