### ISSUE TITLE
show_in_notebook: No values

### ISSUE THREAD

**Issue by ajhepburn** [marcotcr/lime#547]
I have a problem displaying the probabilities with the TextExplainer. I can get the results for my binary classification task no problem, and can even get a heatmap of the importance of various features, but it doesn't seem to render in the figure (See below).

![image](https://user-images.githubusercontent.com/16597333/102023729-5f13a600-3d85-11eb-8a2f-c8ea790e12dc.png)

It may also be worth noting my values are very small, but I have used softmax in my custom classifier function:

```
[('injures', 3.2518712539036796e-05),
 ('Colorado', 3.1514523742135344e-05),
 ('shooting', 2.005093602027747e-05),
 ('School', 1.9409140907887182e-05),
 ('2', 1.745366909007012e-05),
 ('in', 3.913960051192847e-06)]
```

I suppose a better question would be, is there a way I can normalize these values?

**Comment by marcotcr** [comment]
It doesn't show up because your weights are all very small (as you noted). Your prediction probability is also zero for both labels, so I'm guessing there is a problem with your prediction function: if you used softmax, the probabilities should sum to one.

**Comment by ajhepburn** [comment]
My probabilities do sum to one, it just doesn't seem to carry onto `show_in_notebook`. Using the tutorial example, I get:

```
Document id: 3
Probability(Location) = 0.7975525
True class: Location
```
