### ISSUE TITLE
LimeTabularExplainer.explain_instance - Performance improvement request

### ISSUE THREAD

**Issue by navula2** [marcotcr/lime#550]
We are using LIME to get the explanation for the input data row with 20 features. Our requirement is to invoke this explanation method `LimeTabularExplainer.explain_instance` from another application via REST API. Our expectation is to have this response time within in `150 milliseconds`.

When the `num_samples = 5000`, the `LimeTabularExplainer.explain_instance` method is taking about `5 seconds`.  Based on the suggestions mentioned in the issue [How to make LIME run faster](https://github.com/marcotcr/lime/issues/361), we reduced `num_samples = 1000` and explain_instance method is taking about `1 second`. Reducing the samples even further  `num_samples = 500`, the response is approximately `554 milli seconds`. Reducing the sample size results in better performance but the feature weights are changing drastically. For example  when number of samples are 5000, the feature that is contributing 2.8% towards the predicted result, became negative value (not contributing anymore) when the sample size is reduced to 500.

Here is the breakdown of the results.

Sample size | Response time (mills)
--  | --
5000 | 5600
1000 | 1054
500 | 554
300 |  374
200 | 243

I tuned my application code and only the bottleneck at this point is the response from `explain_instance`. Are there any plans to improve this performance in near future releases? Do you suggest any optimum sample size without drastic change in the explanation results?

**Comment by marcotcr** [comment]
The performance depends on how fast your model predicts
