### ISSUE TITLE
lime for all samples

### ISSUE THREAD

**Issue by amaa11** [marcotcr/lime#557]
Dear all,

Assuming I have 200 samples and 11 features.
I want to apply lime for all samples and then mean their ranks to have like a global lime for all samples (as the case in SHAP).
Is that possible?
I tried to output the lime as map and list in lime, but it is hard to extract the ranks and find them mean for all samples.
Any idea?
Does anyone did it before?
Regards

**Comment by marcotcr** [comment]
I don't understand why it is hard, so I'll close the issue : )
