### ISSUE TITLE
How to resolve the error!!

### ISSUE THREAD

**Issue by akshay-gupta123** [marcotcr/lime#563]
Here is my code:
```
import face_detection
from lime import lime_image
detector1 = face_detection.build_detector('DSFDDetector',confidence_threshold=0.3,nms_iou_threshold=0.3)
def batch_img(images):
    pred = []
    for img in images:
      result = detector1.detect(img)
      results = [[i,1-i] for i in result[:,4]]
      pred.append(results)
    return np.array(pred)
image = cv2.imread('/content/image-mask-estimate/data/sample-images/2.jpg')[:,:,::-1]
explainer = lime_image.LimeImageExplainer()
x = np.array(image)
explanation = explainer.explain_instance(x, batch_img , top_labels=5, hide_color=0, num_samples=10)
```
I am getting this error:
```
/usr/local/lib/python3.6/dist-packages/lime/lime_base.py in explain_instance_with_data(self, neighborhood_data, neighborhood_labels, distances, label, num_features, feature_selection, model_regressor)
    180 
    181         weights = self.kernel_fn(distances)
--> 182         labels_column = neighborhood_labels[:, label]
    183         used_features = self.feature_selection(neighborhood_data,
    184                                                labels_column,

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by saraswat40** [comment]
@akshay-gupta123 did you find a solution to this? I am also running into this. Thanks

**Comment by akshay-gupta123** [comment]
@saraswat40 LIME expects a fixed 2D output, but due to annotation model predicts different number of outputs.
Try to fix the output size, it will work.

**Comment by saraswat40** [comment]
@akshay-gupta123 thanks for responding. Yes, I think I got past this problem.

**Comment by setthawut8** [comment]
@akshay-gupta123 @saraswat40 hi I got the same problem for multiclass text classification.

`"IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed"`

an example of the prediction based as a below image
![Screenshot 2022-07-27 150626](https://user-images.githubusercontent.com/75829649/181195589-ac513775-7182-4185-aae0-f4a753564923.png)

and codes for the lime as a below image.
![Screenshot 2022-07-27 150927](https://user-images.githubusercontent.com/75829649/181196126-9a16c5a7-dacf-4021-ba9f-4b66acc40f28.png)

how to turn above prediction (or output) to be 2D output as you did or can I have your addressed codes.

Thank you for your helps.

**Comment by Ra1491** [comment]
Did you solve this problem?

**Comment by oussema9999** [comment]
> @saraswat40 LIME expects a fixed 2D output, but due to annotation model predicts different number of outputs. Try to fix the output size, it will work.

can you please explain more ?
