### ISSUE TITLE
The API reference seems to be broken.

### ISSUE THREAD

**Issue by ytfksw** [marcotcr/lime#565]
The API reference seems to be broken. For example, the API says that LimeImageExplainer has parameters such as "training_data", "training_labels" etc.
https://lime-ml.readthedocs.io/en/latest/lime.html#lime.lime_image.LimeImageExplainer

On the other hand, there are no such parameters in the docstring of LimeImageExplainer.  
https://github.com/marcotcr/lime/blob/a2c7a6fb70bce2e089cb146a31f483bf218875eb/lime/lime_image.py#L89-L116

**Comment by ytfksw** [comment]
I found the version in the page bottom of the API documentation and that is created at this hash commit 95a948bb.

I think it is better to update the the API documentation.

**Comment by kennysong** [comment]
The second paragraph of the docstring is also wrong. Looks like it was incorrectly copied from `LimeTabularExplainer`. Definitely confused me for a few minutes.

**Comment by marcotcr** [comment]
I think I fixed it now
