### ISSUE TITLE
Describe the parameters that are TODO in docstring

### ISSUE THREAD

**Issue by ytfksw** [marcotcr/lime#566]
There are two parameters in the docstring of LimeImageExplainer.explain_instance that are not explained and TODO.
https://github.com/marcotcr/lime/blob/a2c7a6fb70bce2e089cb146a31f483bf218875eb/lime/lime_image.py#L152-L159

**Comment by marcotcr** [comment]
415d18e8139509a50b8f7482e92d5b0557d8c3cc
