### ISSUE TITLE
Callback function to handle progress updates while LIME is working

### ISSUE THREAD

**Issue by haimat** [marcotcr/lime#569]
We have developed a GUI application for training and testing our TF models.
Now I would like to integrate your LIME library into this application.
Therefore I don't need the progress bar in STDOUT, but instead implemented in our GUI.

Is there any way to get the progress of the operation from the `LimeImageExplainer` while running, e.g. via a callback function?

**Comment by marcotcr** [comment]
Sorry, we don't support that, you'd have to do it yourself : )
