### ISSUE TITLE
LIME for time series data

### ISSUE THREAD

**Issue by emanuel-metzenthin** [marcotcr/lime#575]
Hi everyone,

a few years ago I wrote an [extension to LIME](https://github.com/emanuel-metzenthin/Lime-For-Time), which samples around and explains time series.

This repo gained some traction over time. This is why I think it would make sense to integrate it into the main LIME repository in order to enable more users to use it.

Is this a functionality the LIME package would benefit from, in your opinion? If so, I would offer to work on the integration.

Cheers

**Comment by weslai** [comment]
I think it would be nice!

**Comment by marcotcr** [comment]
Since I'm not actively developing LIME anymore (just maintaining, and even that just barely, as evidenced by the time it takes me to respond to issues), I think it's best to keep any extensions in separate repos.
Thanks!
