### ISSUE TITLE
How Can I Save Plot

### ISSUE THREAD

**Issue by imrankhan441** [marcotcr/lime#577]
is any way to save this type of plot?

![pbl](https://user-images.githubusercontent.com/26671669/107929212-8b28ee80-6fa3-11eb-936e-f62caa409ead.png)

**Comment by MariaSheikh** [comment]
To save lime explanation, 

exp = explainer.explain_instance(x_test.iloc[50], clf3.predict_proba)
exp.save_to_file('temp.html')
