### ISSUE TITLE
Lime working with YoloV4 - Image classification

### ISSUE THREAD

**Issue by saraswat40** [marcotcr/lime#579]
Hello,

I'm trying to get Lime to work with YoloV4. Here is the notebook: https://github.com/saraswat40/Golang-Regex-Tutorial/blob/master/Lime_YoloV4.ipynb

As far as I can tell this doesn't work. 

Please let me know if I am missing something.

Thanks

**Comment by marcotcr** [comment]
Er, sorry, I can't go debug other people's notebooks
