### ISSUE TITLE
NoneType Object is not Iterable

### ISSUE THREAD

**Issue by daw454** [marcotcr/lime#580]
I'm trying to apply Recurrent Tabular Explainar from LIME, however, I keep on getting the output that NoneType is not iterable. This even persists for this simple minimal example:

```

from lime import lime_tabular

x_train = np.random.randint(0, 6249, size=(10, 6249,1))
yy_train = np.random.randint(0, 10, size=(10,1))

explainer = lime_tabular.RecurrentTabularExplainer(x_train, training_labels=yy_train)
```

Can you tell me what's wrong? Kind regards,

**Comment by marcotcr** [comment]
There was a bug, fixed in 38a3646
