### ISSUE TITLE
Is there a way to change the weights of already existing explanation?

### ISSUE THREAD

**Issue by Rocyzas** [marcotcr/lime#581]
Hello,
I am using LimeTabularExplainer on the classification task. It predicts classes and numerates important features correctly.
However, it seems to fail to explain each instance correctly, by always pointing feature 'bars' towards the wrong class (even though it predicts and ranks important features correctly).
I am using an SVC classifier from the scikit-learn library on the synthetic dataset, where '1' and '3' are the most important features.

I checked both the output and explanation.as_list(label) and it seems that the explanation 'bars' should be reversed for all predictions it makes (or at least it seems to be about right if I would reverse them).
If that is the case, perhaps it is possible to multiply each weighted feature by -1, so that it rotates?
If that is not possible or I should not do that, could you advise how am I supposed to fix this?

```

    # X - training data without labels
    # y: [0,1]
    # Two class names AD and HC
    # Columns: ['0', '1', '2', '3']
    explainer = LimeTabularExplainer(X, mode = 'classification',
                                        training_labels=y,
                                        feature_selection= 'auto',
                                        class_names=class_names,
                                        feature_names = columns,
                                        discretize_continuous=False)
   
 # rows - rows that need to be explained
    for i in range(len(rows)):
        explanation = explainer.explain_instance(rows[i],
                                    clf.predict_proba,
                                    top_labels=1, # top_labels=1
                                    num_features=len(columns))
        html_data = explanation.as_html()
        HTML(data=html_data)
```

![HCAD3](https://user-images.githubusercontent.com/75904217/109871480-e92c2600-7c73-11eb-9a7b-bf44f456d6ad.png)
![HCAD2](https://user-images.githubusercontent.com/75904217/109871484-e9c4bc80-7c73-11eb-93e7-d6f564aad4f7.png)
![HCAD1](https://user-images.githubusercontent.com/75904217/109871486-ea5d5300-7c73-11eb-8a4f-212b560b6243.png)
![FISVC](https://user-images.githubusercontent.com/75904217/109871798-3c9e7400-7c74-11eb-8d2e-fa96049bcc86.png)

Versions:
python=3.7.5
lime=0.2.0.1

I am new to the lime library, so I might have made a silly mistake. Sorry if that's the case.

**Comment by marcotcr** [comment]
I think there is a bug if you call `top_labels=1` when there are only two labels. When you have binary classification, I suggest just not using that argument. Please comment if this doesn't solve your issue.
