### ISSUE TITLE
Blank heatmap for LIME for image classification

### ISSUE THREAD

**Issue by OnkarMulay** [marcotcr/lime#583]
![image](https://user-images.githubusercontent.com/47315377/110674352-cfe92380-81f7-11eb-908e-bc32873bb2c9.png)

**Why do I get a blank lime plot ??
even though I get a heatmap for the intermediate layer of the CNN (Inception V3) model...**

![image](https://user-images.githubusercontent.com/47315377/110674542-0030c200-81f8-11eb-942c-bc0772b0f955.png)

**Comment by marcotcr** [comment]
Er, I don't know, I don't really use this kind of heatmap. Maybe check if the weights in explanation.local_exp are very low
