### ISSUE TITLE
Documentation mismatch

### ISSUE THREAD

**Issue by yqtianust** [marcotcr/lime#586]
The documentation in https://lime-ml.readthedocs.io/ is different from the comments in the code.

For example, https://lime-ml.readthedocs.io/en/latest/lime.html#lime.lime_image.LimeImageExplainer and https://github.com/marcotcr/lime/blob/master/lime/lime_image.py#L90.

The former one has too many parameters that do not exist in the code.

**Comment by marcotcr** [comment]
I think I fixed this
