### ISSUE TITLE
Selection of Kernel width

### ISSUE THREAD

**Issue by dsvrsec** [marcotcr/lime#587]
Hi, Can you please suggest on what should be the kernel width for a specific image and how to derive it.Thank you

**Comment by CarlosGuemS** [comment]
Hi, maybe this is answer is unsatisfactory to you, but seeing nobody is answering you...

The issue of the kernel width is an open one and there is no easy solution. There are some methods like OptiLIME that focuses in how obtaining the kernel width for a given problem. I'll link you the paper, and I hope it is helpful: https://arxiv.org/abs/2006.05714

**Comment by marcotcr** [comment]
see #222
