### ISSUE TITLE
Is there way explain_instance can return multiple data points?

### ISSUE THREAD

**Issue by lymphocyte** [marcotcr/lime#589]
Currently i use a for loop to get the explanations one by one like this:

exp = explainer.explain_instance(full_predict_data[i], predict_fn, num_features=5,num_samples=100)

And it's pretty slow to do so, Is there a way that I can get results of the whole datasets?

Thanks in advance.

**Comment by marcotcr** [comment]
Nope, that's the way to do it.
sorry,
