### ISSUE TITLE
Areas encouraging the top prediction are not shown

### ISSUE THREAD

**Issue by naladog** [marcotcr/lime#595]
I used the CIFAR10 dataset for a classification problem.
In some samples the explanations are plotted fine, like in the following case of a blur bird image:
![Figure_1](https://user-images.githubusercontent.com/47301513/115459212-15e9cc00-a227-11eb-8581-2328cf646608.png)

In some other cases though, the boundaries are not shown at all. For example in the following airplane image:
![Figure_2](https://user-images.githubusercontent.com/47301513/115459433-55b0b380-a227-11eb-9144-76cb10995587.png)

The estimated probability of being a plane is very high (0.99) and for some reason the mask array is the following:
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=int64)

Do you have any ideas what could be the issue?
Thank you very much for your time.

**Comment by marcotcr** [comment]
Ugh, sorry, I have no idea from the information you provided, other than maybe the segmentation function doesn't work for this kind of image. You should try the segmentation function out to make sure it produces reasonable segments.
