### ISSUE TITLE
ModuleNotFoundError: No module named 'lime.lime_tabular'; 'lime' is not a package

### ISSUE THREAD

**Issue by kamadforge** [marcotcr/lime#599]
When I run a script with

import lime.lime_tabular

I get an error

ModuleNotFoundError: No module named 'lime.lime_tabular'; 'lime' is not a package

This happens with the newest version 0.2.0.1 (tried to install both through pip and from the Github source)

**Comment by kamadforge** [comment]
Nevermind, I called my script "lime".

**Comment by wyctorfogos** [comment]
Great!
