### ISSUE TITLE
pick step?

### ISSUE THREAD

**Issue by JonathanRBates** [marcotcr/lime#60]
Nice work! Is the "pick step" from your paper implemented in this package?

**Comment by marcotcr** [comment]
Er, not yet. I've been meaning to, but have been too busy. There is an old version (code is bad) [here](https://github.com/marcotcr/lime-experiments/blob/master/compare_classifiers.py#L51).

**Comment by jarandaf** [comment]
Any update on this?

**Comment by WillRNaylor** [comment]
Am also interested in this.

Also, thanks for the lovely work.

**Comment by tmoerman** [comment]
+1 for this feature

thanks for the excellent work so far

**Comment by marcotcr** [comment]
closed by #206
