### ISSUE TITLE
Lime, Model Probability Inconsistency

### ISSUE THREAD

**Issue by demirbilek95** [marcotcr/lime#603]
Hi,
I am trying to explain the result of binary classification model. One thing caught my attention. When I compare the probability value (local approximation) with the model probability (predict_proba) they are not even close to each other. Does it mean that my data is also nonlinear in local perspective and LIME fails to approximate it at all?

`sklearn_gbt = GradientBoostingClassifier()`
`sklearn_gbt.fit(X_train, y_train)`

`explainer = lime.lime_tabular.LimeTabularExplainer(X_test.values, feature_names=data.columns[:21], class_names=["0","1"], discretize_continuous=True)`

`exp = explainer.explain_instance(j, sklearn_gbt.predict_proba, num_features=5)`
`print("Lime prob:",exp.local_pred, "Model prob:", exp.predict_proba )`

I tried for different rows, here there are some examples.

Lime prob: [0.45712761] Model prob: [0.99997 0.00003]
Lime prob: [0.40718732] Model prob: [0.99997 0.00003]
Lime prob: [0.45504765] Model prob: [0.99997 0.00003]
Lime prob: [0.48966282] Model prob: [0.0003563 0.9996437]
Lime prob: [0.50822079] Model prob: [0.99997 0.00003]
Lime prob: [0.5010786] Model prob: [0.99997 0.00003]
Lime prob: [0.46968156] Model prob: [0.99997 0.00003]
Lime prob: [0.50447798] Model prob: [0.99997 0.00003]
Lime prob: [0.47282811] Model prob: [0.99996554 0.00003446]

Sorry I am unable to give information about the data but if it's needed I can give more detail about the steps that I followed.
Thanks in advance!

**Comment by demirbilek95** [comment]
I found another issue (https://github.com/marcotcr/lime/issues/209) with the same problem and kernel_width parameter suggestion works. I have two questions related to this issue:
- What does this parameter do exactly? I couldn't find too much information in documentation.
- I may misunderstand the local fidelity, doesn't this issue violate this principle?

Thank you so much in advance for the help :)

**Comment by marcotcr** [comment]
Yes, if we can't produce an explanation that has probabilities close to your model the explanations are not locally faithful. The kernel width parameter is describing what 'local' means
