### ISSUE TITLE
There is a new technique called Quantitative Input Influence (QII), it is very similar to lime especially in explaining the image classification model, but could you please help me in understanding the key difference between LIME and QII?

### ISSUE THREAD

**Issue by man0007** [marcotcr/lime#608]
QII Paper: https://people.umass.edu/yzick/papers/transparency.oakland16.pdf

Code base: https://github.com/hovinh/QII

**Comment by man0007** [comment]
QII Paper: https://people.umass.edu/yzick/papers/transparency.oakland16.pdf

Code base: https://github.com/hovinh/QII

**Comment by marcotcr** [comment]
Sorry, you'll have to read both papers and learn by yourself : )
