### ISSUE TITLE
How to get stats in Model retraining using training_data_stats in LimeTabularExplainer?

### ISSUE THREAD

**Issue by hanzigs** [marcotcr/lime#613]
After creating first model and explainer (1st), and generating data stats using QuartileDiscretizer, 
For Retraining
In next model and explainer (2nd), we use training_data_stats in LimeTabularExplainer, 
how to create data stats from the 3rd explainer for future retraining?

data stats will have means, stds, maxs, mins, feature_values and feature_frequencies
1. whether all to be updated or only feature_frequencies?
2. How to update?

Thanks

**Comment by marcotcr** [comment]
Didn't we have this conversation in #461? :)

I don't  know if I have anything new to add there...
