### ISSUE TITLE
explain_instance can't be passed in keyarg "sampling_method"

### ISSUE THREAD

**Issue by triper1022** [marcotcr/lime#619]
Hi~

When I ran the notebook, [Latin Hypercube Sampling.ipynb ](https://github.com/marcotcr/lime/blob/master/doc/notebooks/Latin%20Hypercube%20Sampling.ipynb)

I found that 
**lime.lime_tabular.LimeTabularExplainer.explain_instance()**
can't be passed in _keyarg "sampling_method"._
If I remove the keyarg, It works.

I have checked the source code, but I can't find the reason.

I put [the notebook](https://github.com/triper1022/lime/blob/keyarg_missing/Latin%20Hypercube%20Sampling.ipynb) I ran into my forked repo.
If you have time, please check it, thanks!

**Comment by marcotcr** [comment]
Which version of lime are you running?

**Comment by triper1022** [comment]
lime-0.2.0.1

**Comment by marcotcr** [comment]
We probably haven't incorporated that feature in the pypi version yet, but it should work if you install from source (clone the repo and run `pip install -e .`
