### ISSUE TITLE
Unable to disable progress_bar

### ISSUE THREAD

**Issue by ngjinshan** [marcotcr/lime#622]
explain_instance() got an unexpected keyword argument 'progress_bar' when i tried to set progress_bar=False
![1](https://user-images.githubusercontent.com/59447774/125167398-d782fe00-e1d2-11eb-91f8-3b7c771479be.PNG)
![2](https://user-images.githubusercontent.com/59447774/125167401-d8b42b00-e1d2-11eb-8c50-fd29b1fe3cf2.PNG)

**Comment by marcotcr** [comment]
Try cloning the repository and installing with `pip install -e .`
