### ISSUE TITLE
LIME for Two Images in Input of Different Size

### ISSUE THREAD

**Issue by OnkarMulay** [marcotcr/lime#625]
I want to run LIME for **LIME for Two Images in Input of Different Size**...
How should I look for it?

Can LIME perform something like this?

-Thanks
Onkar

**Comment by marcotcr** [comment]
Is it the case that your input is a pair of images? If so, you'd have to write a custom perturbation function, the one we have only perturbs one image. Alternatively, if you can concatenate the images, you can have your prediction function split them when making the prediction.

If all you mean is that you want to get separate explanations for images of different sizes, that should just work out of the box.
