### ISSUE TITLE
Lime is only using the first probability to generate results

### ISSUE THREAD

**Issue by osiast** [marcotcr/lime#628]
I studied Lime and implemented it in my pytorch model. However, I noticed something strange: As seen in the image, Lime is only using the first probability (of the 5000 generated by default) to generate the graph. I'm confused, why does this happen? Is it correct?

```
feature_names = list(X_train_fold[0].head(0))

explainer = LimeTabularExplainer(X_train_fold[0],
                                 feature_names=feature_names,
                                 class_names=['is_recid'],
                                 discretize_continuous=False, 
                                 mode='classification')


i = np.random.randint(0, X_test_fold[0].shape[0])
data_row = np.array(X_train_fold[0].values[i])

exp = explainer.explain_instance(data_row, my_predict_proba, num_features=5, top_labels=1)

exp.show_in_notebook(show_table=True, show_all=False)
```

![image](https://user-images.githubusercontent.com/2292984/127310401-41a2aa41-d72f-4275-93f7-de68d2ed13a1.png)

**Comment by marcotcr** [comment]
This is the expected behavior. We are showing the model prediction probabilities on the `data_row` you want to explain. The explanation is supposed to summarize the behavior on the other 4,999 perturbed samples.
