### ISSUE TITLE
LIME for RNN - padding (dummy) records

### ISSUE THREAD

**Issue by OmarMHamed** [marcotcr/lime#630]
Hello Marcotr,
I am working on a time-series problem with variable sequence length, Is there a way to inform LIME about the padding (dummy) timesteps so it can ignore them when generating the explanation?

**Comment by marcotcr** [comment]
You can try writing a wrapper that does the ignoring for you, i.e. you can hide whatever you don't want LIME to perturb and add it back in the prediction function.
