### ISSUE TITLE
LIME time consumption

### ISSUE THREAD

**Issue by jithincheriyan** [marcotcr/lime#632]
Hi,

I am trying to use LIME to interpret my BERT model. The model prediction is good, and the prediction does not take much time to return the prediction probabilities. However, the LIME explainer takes nearly 10 minutes to make the explanation for a single comment. Is there anything wrong from my side or does LIME take that much time for interpretation? 

Please find my code below:

def Lime_BERT_explanation(comment):
    # path = "H:\\test"
    # test_df = pd.read_csv(path + ".csv", encoding="ISO-8859-1")
    # Comment_Text = test_df.Comment_Text.tolist()
    # print(len(Comment_Text))
    # for comment in Comment_Text:
    print(comment)
    bert_exp = explainer.explain_instance(str(comment),
                                          BERT_predict,
                                          num_features=6,
                                          labels=label_names
                                          )
    print(bert_exp.as_list())

if __name__ == '__main__':
    # Lime_ML_explanation()
    comment="Hello idiot"
    # add this to test a single comment
    Comment_Text = []
    Comment_Text.append(comment)          # where Comment is the comment to be tested
    print(BERT_predict(Comment_Text))
    Lime_BERT_explanation(Comment_Text)

Here BERT_predict is the BERT module which returns the prediction probalbilities.

Thank you

**Comment by marcotcr** [comment]
The default value for `num_samples` (i.e. how many perturbed samples you get, and how many times BERT gets called) in `explain_instance` is `5000`. I'm guessing your model takes 10 minutes to make that many predictions. If you're dealing with short texts (e.g. sentences), you can just use a smaller number of samples

**Comment by jithincheriyan** [comment]
Hi,

Thank you for the reply. But when I set num_samples to a lower number, say 100, it ends up with a new error:
" labels_column = neighborhood_labels[:, label]
TypeError: list indices must be integers or slices, not tuple".

What can we do to make it work?

Regards,
Jithin
