### ISSUE TITLE
Exposing distances vector in ret_exp

### ISSUE THREAD

**Issue by ihadanny** [marcotcr/lime#64]
Can the return object for explain_instance expose the distances vector? or at least the mean and variance of the distances? 
This can be useful when analyzing performance - providing insights if there's a relation between the mean distance of the explained row and the local model score...

**Comment by marcotcr** [comment]
Would you please elaborate?
Let's say that there is a correlation - score goes up with the mean distance function. It seems to me that the only people who would use that are people coming up with different perturbation functions, and those people are not using TabularExplainer anyway - they would be using the BaseExplainer.
