### ISSUE TITLE
Explanation show in notebook for non-English text

### ISSUE THREAD

**Issue by abedkhooli** [marcotcr/lime#66]
For non-English text (ex. Arabic), show_in_notebook(text=True) displays encoding instead of actual words. Is there an option in save_to_file (or some template) that fixes this? The same words (top right in capture) are show correctly. 

![capture](https://cloud.githubusercontent.com/assets/11407254/26211926/7b4d8f68-3bfc-11e7-8358-06263b4ee94c.PNG)

**Comment by marcotcr** [comment]
Er, sorry, I don't know what to do about this. Is it just unicode text?
Also, is the word splitting working correctly, and do these explanations make any sense?

**Comment by abedkhooli** [comment]
It was highlighting one char encoding and showing char encoding (ascii) for the sentence.
I fixed it by editing 3 source files (may require refactoring some text functionality but I am not a coding expert). The files are explanation.py, lime_text.py and lime_tabular.py 
Basically added ensure_ascii = False to json.dumps for text objects and changed .encode('ascii' ... to encode('utf-8', ... in lime_text.py:
text = (self.indexed_string.raw_string()
                .encode('utf-8', 'xmlcharrefreplace').decode())
HTH

**Comment by dreamgonfly** [comment]
I had the same problem and had to spend some time fixing it before I found this issue. So I opened a pull request to reflect the fix to the repository. I hope my pull request closes this issue.
