### ISSUE TITLE
How to force repeatability

### ISSUE THREAD

**Issue by Huxwell** [marcotcr/lime#67]
Hi! The tool idea is great, but I have problems with repeatability.
When I re-run the same code, i get slightly different areas highlighed.
Can I force this to stop (set some random state to fixed value)?
I think, that lack of repeatability is an obstacle for making people (doctors or patients) believe in model reliability.

**Comment by rlphilli** [comment]
The tabular and image explanations rely on calls to random.normal and random.randint, respectively. You could probably use random.seed to set an initial random seed and that might help you get reproduceable results. Alternatively, you might try to simply increase the number of samples for a given explanation to find more consistent results.

**Comment by Huxwell** [comment]
Is it better to increase num_features or num_samples to achieve this?

**Comment by marcotcr** [comment]
Increasing the number of samples might help, but it is not guaranteed - if two features are equally good at explaining, LIME may pick an arbitrary one. If you really want the results to always be the same, fixing the random seed is the way to go.

**Comment by caterpillars** [comment]
I added this following code and ran explain_instance twice at the same data point, I still get different results. 

import random
random.seed(16)
exp.explain_instance(X_bin[index], clf_bin.predict_proba,num_features=5).as_list()
exp.explain_instance(X_bin[index], clf_bin.predict_proba,num_features=5).as_list()

where exp = LimeTabularExplainer.

Is there anything that I did wrong?

**Comment by marcotcr** [comment]
the randomness is inside explain_instance, so you need to call random.seed before calling explain_instance each time.
You could encapsulate it:
```
def explain(instance, predict_fn, **kwargs):
  np.random.seed(16)
  return exp.explain_instance(instance, predict_fn, **kwargs)
```
