### ISSUE TITLE
What is explain_instance() "text" argument supposed to be?

### ISSUE THREAD

**Issue by another1s** [marcotcr/lime#671]
According to the official documents, explain_instance() takes "raw text string to be explained" as the input of "text" argument. 
Intuitively, it should be an single instance of raw text, but I just encountered a similar error reported in #35. 

I followed some of the mentioned solutions in that relevant issue by dynamically changing "num_samples" to my data samples number, but I still could not make my code work ----- it reports "TypeError expected string or bytes-like object"  in lime/lime_text.py  at line 114.

It seems like there exist a contradiction that explain_instance() only takes raw string object as input; however, plain string object is not compatible with any "num_samples" except 1.

I am quite confused. May I get a demo that clarify what text supposed to be.

**Comment by evanli2060** [comment]
Having the same issue as you. Did you manage to figure out what was the problem?

**Comment by another1s** [comment]
> Having the same issue as you. Did you manage to figure out what was the problem?

I finally figure it out: num_samples is not referred to the number of input samples, but the number of sentence created as perturbed input..

in conclusion, explain_instance tasks one sentence per iteration but your model_pred api which should  satisfy batch data.
