### ISSUE TITLE
lime can't handle xgboost model with large feature size?

### ISSUE THREAD

**Issue by fxc123** [marcotcr/lime#72]
I have a xgboost model with 50k features, and after a plenty long time, it reports the following error:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-72-cc77dd341889> in <module>()
----> 1 explainer = lime.lime_tabular.LimeTabularExplainer(arr3, feature_names=feats, class_names=["0","1","2"], discretize_continuous=True)

/usr/local/lib/python3.6/site-packages/lime/lime_tabular.py in __init__(self, training_data, training_labels, feature_names, categorical_features, categorical_names, kernel_width, verbose, class_names, feature_selection, discretize_continuous, discretizer)
    138                 self.discretizer = QuartileDiscretizer(
    139                     training_data, self.categorical_features, feature_names,
--> 140                     labels=training_labels)
    141             elif discretizer == 'decile':
    142                 self.discretizer = DecileDiscretizer(

/usr/local/lib/python3.6/site-packages/lime/discretize.py in __init__(self, data, categorical_features, feature_names, labels)
    123 
    124         BaseDiscretizer.__init__(self, data, categorical_features,
--> 125                                  feature_names, labels=labels)
    126 
    127     def bins(self, data, labels):

/usr/local/lib/python3.6/site-packages/lime/discretize.py in __init__(self, data, categorical_features, feature_names, labels)
     49             n_bins = qts.shape[0]  # Actually number of borders (= #bins-1)
     50             boundaries = np.min(data[:, feature]), np.max(data[:, feature])
---> 51             name = feature_names[feature]
     52 
     53             self.names[feature] = ['%s <= %.2f' % (name, qts[0])]

IndexError: list index out of range

**Comment by marcotcr** [comment]
I need a bit more information. Is 'feats' the same length as arr3.shape[1]? That seems to be the problem, not the number of classes.

**Comment by fxc123** [comment]
@marcotcr Yes, the feats lengths is the same as arr3.shape[1], Is that a problem? What's the correct  practice?

**Comment by marcotcr** [comment]
It should be the same. I thought it could be different because of the error you are getting. I don't know what it is, but if you could try running it on a reduced version of the array:
`lime.lime_tabular.LimeTabularExplainer(arr3[:10], feature_names=feats, class_names=["0","1","2"], discretize_continuous=True)`
and the error still persists, maybe you could share the first few rows of your data?

**Comment by fxc123** [comment]
The arr3 is the training data used for the xgboost model, it is 46829 cols, like this:
array([ 0.     ,  0.     ,  0.     , ...,  0.25687,  0.     ,  0.     ])

I apologize that the error I paste above maybe not the original callstack ...
