### ISSUE TITLE
Random Segmentation

### ISSUE THREAD

**Issue by NanqingD** [marcotcr/lime#75]
Hi, it is more like a suggestion or question than a bug actually. So when I deal with some pictures which are complicated than ImageNet, the segmentation seems to be different for same picture each time. Currently, I am not 100% sure, it is totally due to the picture quality. I am reading your original paper, but not fully understand it. Do you have randomness in your algorithm design which may lead to such result?

**Comment by marcotcr** [comment]
Do you have an example? The segmentation should be deterministic, but the explanations are not.
