### ISSUE TITLE
filter features favor one particular class

### ISSUE THREAD

**Issue by caterpillars** [marcotcr/lime#76]
Hi,

I am wondering if there is a way to list only features that favor one particular class. For example, only the features labeled in 'orange' in the .show_in_notebook() output?

Thanks!

**Comment by marcotcr** [comment]
We don't have that as an option, but you do something like:

```
import copy
exp2 = copy.deepcopy(exp)
label = 1 # whatever label you want here
exp2.local_exp[label] = [x for x in exp2.local_exp[label] if x[1] > 0] # or < 0, if you want the blue bars
exp2.show_in_notebook()

```
