### ISSUE TITLE
LimeImageExplainer.explain_instance requires top_labels argument and ignores labels argument

### ISSUE THREAD

**Issue by CPapadim** [marcotcr/lime#78]
When running `explain_instance` if top_labels is set to `None`  then `top` won't be defined in the subsequent `for` loop, causing an error.

In addition, the labels argument gets immediately overwritten by `self.data_labels` output before it's used.

**Comment by marcotcr** [comment]
Fixed in 9ab754b40d7aca0b27e070dd733d570053e38ae5.
Thanks,
