### ISSUE TITLE
Unstable explanations when numbers of bins is changed

### ISSUE THREAD

**Issue by MassimilianoGrassiDataScience** [marcotcr/lime#85]
Hi Marco and thanks for your interesting work. Carlos really intrigued me about LIME when he presented it last year at the NIPS conference.

I’ve been playing a bit with it (actually with an R implementation; https://github.com/thomasp85/lime/) but varying the number of bins used to discretize the continuos predictors, as well as using such predictors in a continuous way, results in quite different explanations for the prediction. The changes are both in the highest ranked predictors and in their contributions (sometimes even reversed). I manly tried it in models trained to perform a dichotomous prediction (medical) starting from 16 predictors, nearly two-thirds of which are continuous, a sample size of 123 subjects and high performance achieved at least with SVM rbf kernel (AUC = 0.96).

Do you have some suggestion to provide some more stable explanations?

Thank you!

**Comment by marcotcr** [comment]
Hello. Can you share a notebook with an example? Since I don't maintain or use the R implementation, it's hard for me to know if it's an implementation problem or a conceptual one.

**Comment by MassimilianoGrassiDataScience** [comment]
I implemented the (kind of) same algorithm in Python, so I could use your native package and avoid any potential implementation problems. 

As far as I could see, I can just ask for 4 (quartile) and 10 (decile) bins in the discretization of continuous variables in your implementation. This is an example: 

no discretization
![unknown-2](https://user-images.githubusercontent.com/10517372/28827775-e2aad0f0-76ce-11e7-8cc4-938c46301bd7.jpg)

quartiles
![unknown-3](https://user-images.githubusercontent.com/10517372/28827795-f3bd1b14-76ce-11e7-86e6-1d04e747504c.jpg)

deciles
![unknown-4](https://user-images.githubusercontent.com/10517372/28827807-03b33972-76cf-11e7-9e4a-78a2d80c0bce.jpg)

Thanks you!

**Comment by marcotcr** [comment]
since all of the weights are small enough to be explained by noise, I have two guesses:
1. Your kernel width is too small, which makes the intercept explain everything
2. You have very high class imbalance and this particular example is predicted in the majority class, so that the intercept explains everything.
