### ISSUE TITLE
Getting tabular data from the explanation function

### ISSUE THREAD

**Issue by sathyaanurag** [marcotcr/lime#86]
Hello,

 I have implemented L.I.M.E in R and Python. In R it is possible to get a summary of all the details in tabular format, where in python I am unable to find a equivalent functionality, as I want to get the summary and build explanation visualizations using d3.js. I tried using the as_html and jasonize functions (which I saw in the source-code). Can you please tell me if this approach is okay or if you have any suggestions to get the raw values from explanation function so that it can be used externally also.

Thank you,
Sathya

**Comment by marcotcr** [comment]
I'm sorry, your question is not clear. Did you take a look at [this tutorial](https://marcotcr.github.io/lime/tutorials/Tutorial%20-%20continuous%20and%20categorical%20features.html)?
