### ISSUE TITLE
Minor doc issue with LimeTabularExplainer

### ISSUE THREAD

**Issue by ianozsvald** [marcotcr/lime#87]
The doc string is poorly rendered here: http://lime-ml.readthedocs.io/en/latest/lime.html The documentation shows:

* kernel_width – kernel width for the exponential kernel.
* None, defaults to sqrt (If) –
* verbose – if true, print local prediction values from linear model

The `None` is a part of the `kernel` parameter. I don't know the Sphinx rendering process, I'm guessing the line here is in error (possibly an extraneous carriage return?): https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L126

Additional rendering errors occur for:

* https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L228
* https://github.com/marcotcr/lime/blob/master/lime/lime_tabular.py#L241

**Comment by marcotcr** [comment]
Fixed it, thank you.
