### ISSUE TITLE
Explaining binary features that depend on more than just text

### ISSUE THREAD

**Issue by desilinguist** [marcotcr/lime#93]
I have a somewhat different situation that is not covered by any of the tutorials. I am using an SVC with the following **binary** features: word n-grams, character n-grams, and syntactic dependency n-grams. I think the ideal way of going about this is to basically use `TextExplainer` if I understand correctly. However, in that case, I have to basically have a custom vectorizer that not only binary-counts the n-grams (that come from the text directly) but also parses the text and binary-counts the syntactic n-grams after parsing. This seems pretty inefficient though (having the vectorizer parse the text). 

The other option is to pretend that the **active** binary features are categorical features (the inactive ones are ignored) and have possible values of 0 and 1 and then use a `TabularExplainer` instead. 

@marcotcr have you come across a situation like this before when using Lime? Any guidance would be much appreciated.

**Comment by marcotcr** [comment]
If you pretend that they are categorical features, you can generate nonsensical feature vectors (e.g. bigram count for 'do not' is one where unigram count for 'do' is 0). Using TextExplainer will give you a perturbation distribution (which is nice), even if inefficient. However, if you want syntactic dependency stuff or n-gram stuff to appear in explanations, you will have to write your own explainer and include that in the interpretable representation.

**Comment by desilinguist** [comment]
Thanks @marctocr! I see your point about the categorical features. Ah, TextExplainer _only_ works with words? So I'd basically have to figure out how to do the perturbation computations for n-grams and dependency parses and use those?

**Comment by marcotcr** [comment]
Correct.

**Comment by desilinguist** [comment]
Thanks! I'll work on that and keep you posted.
